/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AdminControllerCheckAdminPathParams = {
    /**
     * @description Solana wallet address to check
     * @type string
    */
    walletAddress: string;
};

/**
 * @description Returns admin status
*/
export type AdminControllerCheckAdmin200 = any;

export type AdminControllerCheckAdminQueryResponse = AdminControllerCheckAdmin200;

export type AdminControllerCheckAdminQuery = {
    Response: AdminControllerCheckAdmin200;
    PathParams: AdminControllerCheckAdminPathParams;
    Errors: any;
};