/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ArticleControllerRemovePathParams = {
    /**
     * @type string
    */
    id: string;
};

export type ArticleControllerRemove200 = any;

export type ArticleControllerRemoveMutationResponse = ArticleControllerRemove200;

export type ArticleControllerRemoveMutation = {
    Response: ArticleControllerRemove200;
    PathParams: ArticleControllerRemovePathParams;
    Errors: any;
};