/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ArticleControllerFindAllQueryParams = {
    /**
     * @type number | undefined
    */
    page?: number;
    /**
     * @type number | undefined
    */
    limit?: number;
};

export type ArticleControllerFindAll200 = any;

export type ArticleControllerFindAllQueryResponse = ArticleControllerFindAll200;

export type ArticleControllerFindAllQuery = {
    Response: ArticleControllerFindAll200;
    QueryParams: ArticleControllerFindAllQueryParams;
    Errors: any;
};