/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ArticleControllerFindBySlugPathParams = {
    /**
     * @type string
    */
    slug: string;
};

export type ArticleControllerFindBySlug200 = any;

export type ArticleControllerFindBySlugQueryResponse = ArticleControllerFindBySlug200;

export type ArticleControllerFindBySlugQuery = {
    Response: ArticleControllerFindBySlug200;
    PathParams: ArticleControllerFindBySlugPathParams;
    Errors: any;
};