/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetNonceDto } from "@/lib/api-client/types/get-nonce-dto";

export type AuthControllerDevLogin201 = any;

export type AuthControllerDevLoginMutationRequest = GetNonceDto;

export type AuthControllerDevLoginMutationResponse = AuthControllerDevLogin201;

export type AuthControllerDevLoginMutation = {
    Response: AuthControllerDevLogin201;
    Request: AuthControllerDevLoginMutationRequest;
    Errors: any;
};