/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetNonceDto } from "@/lib/api-client/types/get-nonce-dto";

export type AuthControllerGetNonce201 = any;

export type AuthControllerGetNonceMutationRequest = GetNonceDto;

export type AuthControllerGetNonceMutationResponse = AuthControllerGetNonce201;

export type AuthControllerGetNonceMutation = {
    Response: AuthControllerGetNonce201;
    Request: AuthControllerGetNonceMutationRequest;
    Errors: any;
};