/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type BlogControllerFindBySlugPathParams = {
    /**
     * @type string
    */
    slug: string;
};

export type BlogControllerFindBySlug200 = any;

export type BlogControllerFindBySlugQueryResponse = BlogControllerFindBySlug200;

export type BlogControllerFindBySlugQuery = {
    Response: BlogControllerFindBySlug200;
    PathParams: BlogControllerFindBySlugPathParams;
    Errors: any;
};