/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateBlogDto } from "@/lib/api-client/types/create-blog-dto";

export type BlogControllerCreate201 = any;

export type BlogControllerCreateMutationRequest = CreateBlogDto;

export type BlogControllerCreateMutationResponse = BlogControllerCreate201;

export type BlogControllerCreateMutation = {
    Response: BlogControllerCreate201;
    Request: BlogControllerCreateMutationRequest;
    Errors: any;
};