/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type BlogControllerRemovePathParams = {
    /**
     * @type string
    */
    id: string;
};

export type BlogControllerRemove200 = any;

export type BlogControllerRemoveMutationResponse = BlogControllerRemove200;

export type BlogControllerRemoveMutation = {
    Response: BlogControllerRemove200;
    PathParams: BlogControllerRemovePathParams;
    Errors: any;
};