/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SendMessageDto } from "@/lib/api-client/types/send-message-dto";

export type ChatControllerSendMessage201 = any;

export type ChatControllerSendMessageMutationRequest = SendMessageDto;

export type ChatControllerSendMessageMutationResponse = ChatControllerSendMessage201;

export type ChatControllerSendMessageMutation = {
    Response: ChatControllerSendMessage201;
    Request: ChatControllerSendMessageMutationRequest;
    Errors: any;
};