/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CloudinaryUploadControllerUpload201 = any;

export type CloudinaryUploadControllerUploadMutationResponse = CloudinaryUploadControllerUpload201;

export type CloudinaryUploadControllerUploadMutation = {
    Response: CloudinaryUploadControllerUpload201;
    Errors: any;
};