/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CommentControllerCreate201 = any;

export type CommentControllerCreateMutationRequest = {
    /**
     * @type string
    */
    content: string;
    /**
     * @type string
    */
    marketId: string;
    /**
     * @type string
    */
    parentId?: string | null;
    /**
     * @description Array of image URLs (upload images first using /upload/images endpoint)
     * @type array | undefined
    */
    images?: string[];
};

export type CommentControllerCreateMutationResponse = CommentControllerCreate201;

export type CommentControllerCreateMutation = {
    Response: CommentControllerCreate201;
    Request: CommentControllerCreateMutationRequest;
    Errors: any;
};