/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CommentControllerFindRepliesPathParams = {
    /**
     * @type string
    */
    commentId: string;
};

export type CommentControllerFindRepliesQueryParams = {
    /**
     * @type number | undefined
    */
    page?: number;
    /**
     * @type number | undefined
    */
    limit?: number;
};

export type CommentControllerFindReplies200 = any;

export type CommentControllerFindRepliesQueryResponse = CommentControllerFindReplies200;

export type CommentControllerFindRepliesQuery = {
    Response: CommentControllerFindReplies200;
    PathParams: CommentControllerFindRepliesPathParams;
    QueryParams: CommentControllerFindRepliesQueryParams;
    Errors: any;
};