/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CommentControllerFindOnePathParams = {
    /**
     * @type string
    */
    id: string;
};

export type CommentControllerFindOne200 = any;

export type CommentControllerFindOneQueryResponse = CommentControllerFindOne200;

export type CommentControllerFindOneQuery = {
    Response: CommentControllerFindOne200;
    PathParams: CommentControllerFindOnePathParams;
    Errors: any;
};