/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CommentControllerFindByUserPathParams = {
    /**
     * @type string
    */
    userId: string;
};

export type CommentControllerFindByUserQueryParams = {
    /**
     * @type number | undefined
    */
    page?: number;
    /**
     * @type number | undefined
    */
    limit?: number;
};

export type CommentControllerFindByUser200 = any;

export type CommentControllerFindByUserQueryResponse = CommentControllerFindByUser200;

export type CommentControllerFindByUserQuery = {
    Response: CommentControllerFindByUser200;
    PathParams: CommentControllerFindByUserPathParams;
    QueryParams: CommentControllerFindByUserQueryParams;
    Errors: any;
};