/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateMarketDto = {
    /**
     * @description External market ID (PDA) from blockchain
     * @type string
    */
    marketId: string;
    /**
     * @description Market title
     * @type string
    */
    title: string;
    /**
     * @description Market description
     * @type string | undefined
    */
    description?: string;
    /**
     * @description Market question
     * @type string | undefined
    */
    question?: string;
    /**
     * @description Market slug for URL
     * @type string | undefined
    */
    slug?: string;
    /**
     * @description Market image URL
     * @type string | undefined
    */
    imageUrl?: string;
    /**
     * @description Market source
     * @type string | undefined
    */
    source?: string;
    /**
     * @description Market category
     * @type string | undefined
    */
    category?: string;
    /**
     * @description Creator wallet address
     * @type string | undefined
    */
    creatorWallet?: string;
    /**
     * @description YES token mint address
     * @type string | undefined
    */
    yesTokenMint?: string;
    /**
     * @description NO token mint address
     * @type string | undefined
    */
    noTokenMint?: string;
    /**
     * @description Market start date (ISO string)
     * @type string | undefined
    */
    startDate?: string;
    /**
     * @description Market end date (ISO string)
     * @type string | undefined
    */
    endDate?: string;
    /**
     * @description Token symbol for news lookup
     * @type string | undefined
    */
    tokenSymbol?: string;
    /**
     * @description Token mint address on Solana
     * @type string | undefined
    */
    tokenAddress?: string;
    /**
     * @description Polymarket condition ID
     * @type string | undefined
    */
    polymarketConditionId?: string;
    /**
     * @description Polymarket event slug
     * @type string | undefined
    */
    polymarketSlug?: string;
    /**
     * @description Polymarket market ID
     * @type string | undefined
    */
    polymarketMarketId?: string;
    /**
     * @description Resolution source (e.g. \"Polymarket UMA Oracle\", \"Switchboard\", \"Admin\")
     * @type string | undefined
    */
    resolutionSource?: string;
    /**
     * @description Kalshi event ticker (for auto-resolution)
     * @type string | undefined
    */
    kalshiEventTicker?: string;
    /**
     * @description Kalshi market ticker (for auto-resolution)
     * @type string | undefined
    */
    kalshiMarketTicker?: string;
    /**
     * @description Parent market ID (for sub-markets)
     * @type string | undefined
    */
    parentMarketId?: string;
    /**
     * @description Outcome label (e.g. candidate name)
     * @type string | undefined
    */
    outcomeLabel?: string;
    /**
     * @description Sort order within parent market
     * @type number | undefined
    */
    sortOrder?: number;
    /**
     * @description Whether this is a multi-outcome parent market
     * @type boolean | undefined
    */
    isMultiOutcome?: boolean;
    /**
     * @description Whether sub-markets are mutually exclusive
     * @type boolean | undefined
    */
    mutuallyExclusive?: boolean;
    /**
     * @description On-chain group PDA
     * @type string | undefined
    */
    groupPda?: string;
};