/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const createMarketX402DtoComparisonTypeEnum = {
    "0": 0,
    "1": 1,
    "2": 2
} as const;

export type CreateMarketX402DtoComparisonTypeEnumKey = (typeof createMarketX402DtoComparisonTypeEnum)[keyof typeof createMarketX402DtoComparisonTypeEnum];

export const createMarketX402DtoMarketVersionEnum = {
    "0": 0,
    "1": 1
} as const;

export type CreateMarketX402DtoMarketVersionEnumKey = (typeof createMarketX402DtoMarketVersionEnum)[keyof typeof createMarketX402DtoMarketVersionEnum];

export type CreateMarketX402Dto = {
    /**
     * @description Token mint address (base58 pubkey)
     * @type string
    */
    token_mint: string;
    /**
     * @description Market question
     * @maxLength 100
     * @type string
    */
    question: string;
    /**
     * @description Market name
     * @maxLength 32
     * @type string
    */
    market_name: string;
    /**
     * @description URL slug for the market
     * @maxLength 128
     * @type string
    */
    slug: string;
    /**
     * @description Market image URL
     * @maxLength 256
     * @type string | undefined
    */
    image_url?: string;
    /**
     * @description Source of the market
     * @maxLength 32
     * @type string | undefined
    */
    source?: string;
    /**
     * @description Market category
     * @maxLength 32
     * @type string
    */
    category: string;
    /**
     * @description Market end date (unix timestamp)
     * @type number
    */
    end_date: number;
    /**
     * @description Oracle feed address (base58 pubkey)
     * @type string | undefined
    */
    oracle_feed?: string;
    /**
     * @description Price target for oracle resolution
     * @type number | undefined
    */
    price_target?: number;
    /**
     * @description Comparison type for oracle (0=GT, 1=LT, 2=EQ)
     * @type number | undefined
    */
    comparison_type?: CreateMarketX402DtoComparisonTypeEnumKey;
    /**
     * @description Market version: 0 = Parimutuel (legacy), 1 = Conditional Token Framework
     * @default 0
     * @type number | undefined
    */
    market_version?: CreateMarketX402DtoMarketVersionEnumKey;
    /**
     * @description SOL collateral per YES+NO token pair (required when market_version=1)
     * @default 1
     * @type number | undefined
    */
    collateral_per_pair?: number;
};