/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateSnapshotDto = {
    /**
     * @description Market PDA (Solana public key)
     * @type string
    */
    marketId: string;
    /**
     * @description YES probability as percentage (0-100)
     * @type number
    */
    yesPrice: number;
    /**
     * @description NO probability as percentage (0-100)
     * @type number
    */
    noPrice: number;
};