/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateArticleDto = {
    /**
     * @description Article title
     * @type string
    */
    title: string;
    /**
     * @description URL-friendly slug
     * @type string
    */
    slug: string;
    /**
     * @description Short description
     * @type string
    */
    description: string;
    /**
     * @description Image URL (Cloudinary)
     * @type string
    */
    imageUrl: string;
    /**
     * @description Link to original X post
     * @type string
    */
    tweetUrl: string;
    /**
     * @description Whether this article is featured
     * @default false
     * @type boolean | undefined
    */
    featured?: boolean;
};