/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const createEventDtoEventTypeEnum = {
    SIGNUP: "SIGNUP",
    WALLET_CONNECT: "WALLET_CONNECT",
    TRADE_INITIATED: "TRADE_INITIATED",
    TRADE_CONFIRMED: "TRADE_CONFIRMED",
    TRADE_FAILED: "TRADE_FAILED"
} as const;

export type CreateEventDtoEventTypeEnumKey = (typeof createEventDtoEventTypeEnum)[keyof typeof createEventDtoEventTypeEnum];

export type CreateEventDto = {
    /**
     * @description Type of analytics event
     * @type string
    */
    eventType: CreateEventDtoEventTypeEnumKey;
    /**
     * @description Wallet address associated with the event
     * @type string
    */
    walletAddress: string;
    /**
     * @description Market ID for trade events
     * @type string | undefined
    */
    marketId?: string;
    /**
     * @description Additional metadata for the event
     * @type object | undefined
    */
    metadata?: object;
};