/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetNonceDto = {
    /**
     * @description Solana wallet address
     * @type string
    */
    walletAddress: string;
};