/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GraduationControllerGetTrendingQueryParams = {
    /**
     * @description Number of trending tokens to return
     * @type number | undefined
    */
    limit?: number;
};

/**
 * @description List of trending tokens with bonding progress
*/
export type GraduationControllerGetTrending200 = any;

export type GraduationControllerGetTrendingQueryResponse = GraduationControllerGetTrending200;

export type GraduationControllerGetTrendingQuery = {
    Response: GraduationControllerGetTrending200;
    QueryParams: GraduationControllerGetTrendingQueryParams;
    Errors: any;
};