/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type KalshiControllerGetEventByTickerPathParams = {
    /**
     * @type string
    */
    ticker: string;
};

export type KalshiControllerGetEventByTicker200 = any;

export type KalshiControllerGetEventByTickerQueryResponse = KalshiControllerGetEventByTicker200;

export type KalshiControllerGetEventByTickerQuery = {
    Response: KalshiControllerGetEventByTicker200;
    PathParams: KalshiControllerGetEventByTickerPathParams;
    Errors: any;
};