/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateMarketDto } from "@/lib/api-client/types/update-market-dto";

export type MarketControllerUpdatePathParams = {
    /**
     * @type string
    */
    id: string;
};

export type MarketControllerUpdate200 = any;

export type MarketControllerUpdateMutationRequest = UpdateMarketDto;

export type MarketControllerUpdateMutationResponse = MarketControllerUpdate200;

export type MarketControllerUpdateMutation = {
    Response: MarketControllerUpdate200;
    Request: MarketControllerUpdateMutationRequest;
    PathParams: MarketControllerUpdatePathParams;
    Errors: any;
};