/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MarketControllerRemovePathParams = {
    /**
     * @type string
    */
    id: string;
};

export type MarketControllerRemove200 = any;

export type MarketControllerRemoveMutationResponse = MarketControllerRemove200;

export type MarketControllerRemoveMutation = {
    Response: MarketControllerRemove200;
    PathParams: MarketControllerRemovePathParams;
    Errors: any;
};