/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const marketControllerFindAllQueryParamsCategoryEnum = {
    Crypto: "Crypto",
    Politics: "Politics",
    Sports: "Sports",
    Entertainment: "Entertainment",
    Science: "Science"
} as const;

export type MarketControllerFindAllQueryParamsCategoryEnumKey = (typeof marketControllerFindAllQueryParamsCategoryEnum)[keyof typeof marketControllerFindAllQueryParamsCategoryEnum];

export const marketControllerFindAllQueryParamsSortEnum = {
    newest: "newest",
    oldest: "oldest",
    volume: "volume",
    ending_soon: "ending_soon"
} as const;

export type MarketControllerFindAllQueryParamsSortEnumKey = (typeof marketControllerFindAllQueryParamsSortEnum)[keyof typeof marketControllerFindAllQueryParamsSortEnum];

export const marketControllerFindAllQueryParamsStatusEnum = {
    active: "active",
    resolved: "resolved",
    cancelled: "cancelled"
} as const;

export type MarketControllerFindAllQueryParamsStatusEnumKey = (typeof marketControllerFindAllQueryParamsStatusEnum)[keyof typeof marketControllerFindAllQueryParamsStatusEnum];

export type MarketControllerFindAllQueryParams = {
    /**
     * @minLength 1
     * @default 1
     * @type number | undefined
    */
    page?: number;
    /**
     * @minLength 1
     * @maxLength 100
     * @default 20
     * @type number | undefined
    */
    limit?: number;
    /**
     * @description Search title, question, description
     * @type string | undefined
    */
    search?: string;
    /**
     * @type string | undefined
    */
    category?: MarketControllerFindAllQueryParamsCategoryEnumKey;
    /**
     * @default "newest"
     * @type string | undefined
    */
    sort?: MarketControllerFindAllQueryParamsSortEnumKey;
    /**
     * @type string | undefined
    */
    status?: MarketControllerFindAllQueryParamsStatusEnumKey;
    /**
     * @description Include sub-markets in listing (admin use)
     * @type boolean | undefined
    */
    includeSubMarkets?: boolean;
};

export type MarketControllerFindAll200 = any;

export type MarketControllerFindAllQueryResponse = MarketControllerFindAll200;

export type MarketControllerFindAllQuery = {
    Response: MarketControllerFindAll200;
    QueryParams: MarketControllerFindAllQueryParams;
    Errors: any;
};