/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateMarketDto } from "@/lib/api-client/types/create-market-dto";

export type MarketControllerCreate201 = any;

export type MarketControllerCreateMutationRequest = CreateMarketDto;

export type MarketControllerCreateMutationResponse = MarketControllerCreate201;

export type MarketControllerCreateMutation = {
    Response: MarketControllerCreate201;
    Request: MarketControllerCreateMutationRequest;
    Errors: any;
};