/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MarketControllerFindOnePathParams = {
    /**
     * @type string
    */
    id: string;
};

export type MarketControllerFindOne200 = any;

export type MarketControllerFindOneQueryResponse = MarketControllerFindOne200;

export type MarketControllerFindOneQuery = {
    Response: MarketControllerFindOne200;
    PathParams: MarketControllerFindOnePathParams;
    Errors: any;
};