/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MarketControllerFindBySlugPathParams = {
    /**
     * @type string
    */
    slug: string;
};

export type MarketControllerFindBySlug200 = any;

export type MarketControllerFindBySlugQueryResponse = MarketControllerFindBySlug200;

export type MarketControllerFindBySlugQuery = {
    Response: MarketControllerFindBySlug200;
    PathParams: MarketControllerFindBySlugPathParams;
    Errors: any;
};