/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MetricsControllerGetDailyMetricsQueryParams = {
    /**
     * @description Number of days to fetch (default: 30)
     * @minLength 1
     * @maxLength 365
     * @type number | undefined
    */
    days?: number;
};

/**
 * @description Daily metrics array
*/
export type MetricsControllerGetDailyMetrics200 = any;

/**
 * @description Not an admin
*/
export type MetricsControllerGetDailyMetrics403 = any;

export type MetricsControllerGetDailyMetricsQueryResponse = MetricsControllerGetDailyMetrics200;

export type MetricsControllerGetDailyMetricsQuery = {
    Response: MetricsControllerGetDailyMetrics200;
    QueryParams: MetricsControllerGetDailyMetricsQueryParams;
    Errors: MetricsControllerGetDailyMetrics403;
};