/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type NotificationControllerGetUnreadCount200 = any;

export type NotificationControllerGetUnreadCountQueryResponse = NotificationControllerGetUnreadCount200;

export type NotificationControllerGetUnreadCountQuery = {
    Response: NotificationControllerGetUnreadCount200;
    Errors: any;
};