/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateNotificationPrefsDto } from "@/lib/api-client/types/update-notification-prefs-dto";

export type NotificationControllerUpdatePreferences200 = any;

export type NotificationControllerUpdatePreferencesMutationRequest = UpdateNotificationPrefsDto;

export type NotificationControllerUpdatePreferencesMutationResponse = NotificationControllerUpdatePreferences200;

export type NotificationControllerUpdatePreferencesMutation = {
    Response: NotificationControllerUpdatePreferences200;
    Request: NotificationControllerUpdatePreferencesMutationRequest;
    Errors: any;
};