/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateEmailDto } from "@/lib/api-client/types/update-email-dto";

export type NotificationControllerSetEmail200 = any;

export type NotificationControllerSetEmailMutationRequest = UpdateEmailDto;

export type NotificationControllerSetEmailMutationResponse = NotificationControllerSetEmail200;

export type NotificationControllerSetEmailMutation = {
    Response: NotificationControllerSetEmail200;
    Request: NotificationControllerSetEmailMutationRequest;
    Errors: any;
};