/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type NotificationControllerGetPreferences200 = any;

export type NotificationControllerGetPreferencesQueryResponse = NotificationControllerGetPreferences200;

export type NotificationControllerGetPreferencesQuery = {
    Response: NotificationControllerGetPreferences200;
    Errors: any;
};