/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const polymarketControllerGetEventsQueryParamsOrderEnum = {
    volume24hr: "volume24hr",
    liquidity: "liquidity",
    updatedAt: "updatedAt"
} as const;

export type PolymarketControllerGetEventsQueryParamsOrderEnumKey = (typeof polymarketControllerGetEventsQueryParamsOrderEnum)[keyof typeof polymarketControllerGetEventsQueryParamsOrderEnum];

export type PolymarketControllerGetEventsQueryParams = {
    /**
     * @default 25
     * @type number | undefined
    */
    limit?: number;
    /**
     * @default 0
     * @type number | undefined
    */
    offset?: number;
    /**
     * @default "volume24hr"
     * @type string | undefined
    */
    order?: PolymarketControllerGetEventsQueryParamsOrderEnumKey;
};

export type PolymarketControllerGetEvents200 = any;

export type PolymarketControllerGetEventsQueryResponse = PolymarketControllerGetEvents200;

export type PolymarketControllerGetEventsQuery = {
    Response: PolymarketControllerGetEvents200;
    QueryParams: PolymarketControllerGetEventsQueryParams;
    Errors: any;
};