/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PortfolioControllerGetHistoryPathParams = {
    /**
     * @description Wallet address (Solana public key)
     * @type string
    */
    wallet: string;
};

export type PortfolioControllerGetHistoryQueryParams = {
    /**
     * @description Page number
     * @minLength 1
     * @default 1
     * @type number | undefined
    */
    page?: number;
    /**
     * @description Number of items per page
     * @minLength 1
     * @maxLength 100
     * @default 20
     * @type number | undefined
    */
    limit?: number;
    /**
     * @description Filter by event type (TRADE_CONFIRMED, TRADE_INITIATED, TRADE_FAILED)
     * @type string | undefined
    */
    eventType?: string;
    /**
     * @description Filter by market ID (on-chain PDA)
     * @type string | undefined
    */
    marketId?: string;
};

export type PortfolioControllerGetHistory200 = any;

export type PortfolioControllerGetHistoryQueryResponse = PortfolioControllerGetHistory200;

export type PortfolioControllerGetHistoryQuery = {
    Response: PortfolioControllerGetHistory200;
    PathParams: PortfolioControllerGetHistoryPathParams;
    QueryParams: PortfolioControllerGetHistoryQueryParams;
    Errors: any;
};