/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PortfolioControllerRemoveFromWatchlistPathParams = {
    /**
     * @description On-chain market PDA
     * @type string
    */
    marketId: string;
};

export type PortfolioControllerRemoveFromWatchlist200 = any;

export type PortfolioControllerRemoveFromWatchlistMutationResponse = PortfolioControllerRemoveFromWatchlist200;

export type PortfolioControllerRemoveFromWatchlistMutation = {
    Response: PortfolioControllerRemoveFromWatchlist200;
    PathParams: PortfolioControllerRemoveFromWatchlistPathParams;
    Errors: any;
};