/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type StoreCommitmentDto = {
    /**
     * @description Shielded pool address
     * @type string
    */
    poolAddress: string;
    /**
     * @description Associated market address
     * @type string
    */
    marketAddress: string;
    /**
     * @description The commitment hash
     * @type string
    */
    commitment: string;
    /**
     * @description Position in the Merkle tree
     * @type number
    */
    leafIndex: number;
    /**
     * @description Batch number
     * @type number
    */
    batchNumber: number;
    /**
     * @description On-chain transaction signature
     * @type string | undefined
    */
    transactionId?: string;
};