/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type StoreNoteDto = {
    /**
     * @description Shielded pool address
     * @type string
    */
    poolAddress: string;
    /**
     * @description The commitment hash that this note corresponds to
     * @type string
    */
    commitment: string;
    /**
     * @description Encrypted note data (JSON encrypted client-side)
     * @type string
    */
    encryptedData: string;
    /**
     * @description Type of note: shield, swap, split
     * @type string | undefined
    */
    noteType?: string;
};