/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TokenDataControllerGetHoldersPathParams = {
    /**
     * @description Solana token mint address
     * @type string
    */
    mint: string;
};

export type TokenDataControllerGetHoldersQueryParams = {
    /**
     * @description Number of top holders to return
     * @type number | undefined
    */
    limit?: number;
};

/**
 * @description Top token holders from Solana RPC
*/
export type TokenDataControllerGetHolders200 = any;

export type TokenDataControllerGetHoldersQueryResponse = TokenDataControllerGetHolders200;

export type TokenDataControllerGetHoldersQuery = {
    Response: TokenDataControllerGetHolders200;
    PathParams: TokenDataControllerGetHoldersPathParams;
    QueryParams: TokenDataControllerGetHoldersQueryParams;
    Errors: any;
};