/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TokenDataControllerGetOhlcvPathParams = {
    /**
     * @description Solana token mint address
     * @type string
    */
    mint: string;
};

export const tokenDataControllerGetOhlcvQueryParamsTimeframeEnum = {
    "1m": "1m",
    "5m": "5m",
    "15m": "15m",
    "1h": "1h",
    "4h": "4h",
    "1d": "1d"
} as const;

export type TokenDataControllerGetOhlcvQueryParamsTimeframeEnumKey = (typeof tokenDataControllerGetOhlcvQueryParamsTimeframeEnum)[keyof typeof tokenDataControllerGetOhlcvQueryParamsTimeframeEnum];

export type TokenDataControllerGetOhlcvQueryParams = {
    /**
     * @description Candlestick timeframe
     * @type string | undefined
    */
    timeframe?: TokenDataControllerGetOhlcvQueryParamsTimeframeEnumKey;
    /**
     * @description Number of candles to return
     * @type number | undefined
    */
    limit?: number;
};

/**
 * @description OHLCV data from GeckoTerminal
*/
export type TokenDataControllerGetOhlcv200 = any;

export type TokenDataControllerGetOhlcvQueryResponse = TokenDataControllerGetOhlcv200;

export type TokenDataControllerGetOhlcvQuery = {
    Response: TokenDataControllerGetOhlcv200;
    PathParams: TokenDataControllerGetOhlcvPathParams;
    QueryParams: TokenDataControllerGetOhlcvQueryParams;
    Errors: any;
};