/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const updateMarketDtoStatusEnum = {
    active: "active",
    resolved: "resolved",
    cancelled: "cancelled"
} as const;

export type UpdateMarketDtoStatusEnumKey = (typeof updateMarketDtoStatusEnum)[keyof typeof updateMarketDtoStatusEnum];

export type UpdateMarketDto = {
    /**
     * @description Market title
     * @type string | undefined
    */
    title?: string;
    /**
     * @description Market description
     * @type string | undefined
    */
    description?: string;
    /**
     * @description Market question
     * @type string | undefined
    */
    question?: string;
    /**
     * @description Market slug
     * @type string | undefined
    */
    slug?: string;
    /**
     * @description Market image URL
     * @type string | undefined
    */
    imageUrl?: string;
    /**
     * @description Market source
     * @type string | undefined
    */
    source?: string;
    /**
     * @description Market category
     * @type string | undefined
    */
    category?: string;
    /**
     * @description Market status
     * @type string | undefined
    */
    status?: UpdateMarketDtoStatusEnumKey;
    /**
     * @description Market start date (ISO string)
     * @type string | undefined
    */
    startDate?: string;
    /**
     * @description Market end date (ISO string)
     * @type string | undefined
    */
    endDate?: string;
    /**
     * @description Token symbol for news lookup
     * @type string | undefined
    */
    tokenSymbol?: string;
    /**
     * @description Token mint address on Solana
     * @type string | undefined
    */
    tokenAddress?: string;
};