/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateNotificationPrefsDto = {
    /**
     * @description Notify when a market you participated in resolves
     * @type boolean | undefined
    */
    marketResolved?: boolean;
    /**
     * @description Notify when a new market is created in a followed category
     * @type boolean | undefined
    */
    newMarketInCategory?: boolean;
    /**
     * @description Notify when someone replies to your comment
     * @type boolean | undefined
    */
    commentReply?: boolean;
    /**
     * @description Receive a weekly digest email
     * @type boolean | undefined
    */
    weeklyDigest?: boolean;
    /**
     * @description Category names to follow for new market notifications
     * @type array | undefined
    */
    followedCategories?: string[];
};