/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UploadControllerUploadImages201 = any;

export type UploadControllerUploadImagesMutationResponse = UploadControllerUploadImages201;

export type UploadControllerUploadImagesMutation = {
    Response: UploadControllerUploadImages201;
    Errors: any;
};