/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateProfileDto } from "@/lib/api-client/types/update-profile-dto";

/**
 * @description Profile updated successfully
*/
export type UserControllerUpdateProfile200 = any;

/**
 * @description Unauthorized
*/
export type UserControllerUpdateProfile401 = any;

export type UserControllerUpdateProfileMutationRequest = UpdateProfileDto;

export type UserControllerUpdateProfileMutationResponse = UserControllerUpdateProfile200;

export type UserControllerUpdateProfileMutation = {
    Response: UserControllerUpdateProfile200;
    Request: UserControllerUpdateProfileMutationRequest;
    Errors: UserControllerUpdateProfile401;
};