/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type VerifySignatureDto = {
    /**
     * @description Solana wallet address
     * @type string
    */
    walletAddress: string;
    /**
     * @description Signed message (base58 encoded)
     * @type string
    */
    signature: string;
    /**
     * @description Original message that was signed
     * @type string
    */
    message: string;
};