/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type X402ControllerGetPositionsQueryParams = {
    /**
     * @description Comma-separated commitment hashes
     * @type string
    */
    commitment_hash: string;
};

/**
 * @description Position details
*/
export type X402ControllerGetPositions200 = any;

export type X402ControllerGetPositionsQueryResponse = X402ControllerGetPositions200;

export type X402ControllerGetPositionsQuery = {
    Response: X402ControllerGetPositions200;
    QueryParams: X402ControllerGetPositionsQueryParams;
    Errors: any;
};