/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type X402ControllerGetPriceHistoryPathParams = {
    /**
     * @description Market ID (on-chain PDA address)
     * @type string
    */
    id: string;
};

export type X402ControllerGetPriceHistoryQueryParams = {
    /**
     * @description Time range: 1d, 1w, or all
     * @type string | undefined
    */
    range?: string;
};

/**
 * @description Price history snapshots
*/
export type X402ControllerGetPriceHistory200 = any;

export type X402ControllerGetPriceHistoryQueryResponse = X402ControllerGetPriceHistory200;

export type X402ControllerGetPriceHistoryQuery = {
    Response: X402ControllerGetPriceHistory200;
    PathParams: X402ControllerGetPriceHistoryPathParams;
    QueryParams: X402ControllerGetPriceHistoryQueryParams;
    Errors: any;
};