/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type X402ControllerGetPrivacyProofPathParams = {
    /**
     * @description Market ID (on-chain PDA address)
     * @type string
    */
    id: string;
};

export type X402ControllerGetPrivacyProofQueryParams = {
    /**
     * @description Commitment hash (hex string, 64 characters)
     * @type string
    */
    commitment_hash: string;
};

export const dataOutcomeEnum2 = {
    YES: "YES",
    NO: "NO"
} as const;

export type DataOutcomeEnum2Key = (typeof dataOutcomeEnum2)[keyof typeof dataOutcomeEnum2];

/**
 * @description Privacy proof generated
*/
export type X402ControllerGetPrivacyProof200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type boolean | undefined
        */
        position_exists?: boolean;
        /**
         * @type string | undefined
        */
        outcome?: DataOutcomeEnum2Key;
        /**
         * @type string | undefined
        */
        amount_range?: string;
        /**
         * @type string | undefined
        */
        merkle_root?: string;
        /**
         * @type array | undefined
        */
        proof_path?: string[];
    };
};

/**
 * @description Payment required
*/
export type X402ControllerGetPrivacyProof402 = any;

/**
 * @description Commitment not found
*/
export type X402ControllerGetPrivacyProof404 = any;

export type X402ControllerGetPrivacyProofQueryResponse = X402ControllerGetPrivacyProof200;

export type X402ControllerGetPrivacyProofQuery = {
    Response: X402ControllerGetPrivacyProof200;
    PathParams: X402ControllerGetPrivacyProofPathParams;
    QueryParams: X402ControllerGetPrivacyProofQueryParams;
    Errors: X402ControllerGetPrivacyProof402 | X402ControllerGetPrivacyProof404;
};