/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type X402ControllerGetTradeHistoryQueryParams = {
    /**
     * @description Comma-separated commitment hashes
     * @type string
    */
    commitment_hash: string;
};

/**
 * @description Trade history
*/
export type X402ControllerGetTradeHistory200 = any;

export type X402ControllerGetTradeHistoryQueryResponse = X402ControllerGetTradeHistory200;

export type X402ControllerGetTradeHistoryQuery = {
    Response: X402ControllerGetTradeHistory200;
    QueryParams: X402ControllerGetTradeHistoryQueryParams;
    Errors: any;
};