/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type X402ControllerGetMarketDetailPathParams = {
    /**
     * @description Market ID (on-chain PDA address)
     * @type string
    */
    id: string;
};

/**
 * @description Market detail
*/
export type X402ControllerGetMarketDetail200 = any;

/**
 * @description Market not found
*/
export type X402ControllerGetMarketDetail404 = any;

export type X402ControllerGetMarketDetailQueryResponse = X402ControllerGetMarketDetail200;

export type X402ControllerGetMarketDetailQuery = {
    Response: X402ControllerGetMarketDetail200;
    PathParams: X402ControllerGetMarketDetailPathParams;
    Errors: X402ControllerGetMarketDetail404;
};