/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateMarketX402Dto } from "@/lib/api-client/types/create-market-x402-dto";

/**
 * @description Market created successfully
*/
export type X402ControllerCreateMarket200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type string | undefined
        */
        market_id?: string;
        /**
         * @type string | undefined
        */
        yes_token_mint?: string;
        /**
         * @type string | undefined
        */
        no_token_mint?: string;
        /**
         * @type string | undefined
        */
        tx_signature?: string;
        /**
         * @type string | undefined
        */
        question?: string;
        /**
         * @type number | undefined
        */
        end_date?: number;
    };
};

/**
 * @description Invalid request body
*/
export type X402ControllerCreateMarket400 = any;

/**
 * @description Payment required — send x402 USDC payment header
*/
export type X402ControllerCreateMarket402 = any;

export type X402ControllerCreateMarketMutationRequest = CreateMarketX402Dto;

export type X402ControllerCreateMarketMutationResponse = X402ControllerCreateMarket200;

export type X402ControllerCreateMarketMutation = {
    Response: X402ControllerCreateMarket200;
    Request: X402ControllerCreateMarketMutationRequest;
    Errors: X402ControllerCreateMarket400 | X402ControllerCreateMarket402;
};