/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description API endpoint catalog
*/
export type X402ControllerGetX402Info200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type string | undefined
        */
        name?: string;
        /**
         * @type string | undefined
        */
        description?: string;
        /**
         * @type array | undefined
        */
        endpoints?: {
            /**
             * @type string | undefined
            */
            path?: string;
            /**
             * @type string | undefined
            */
            method?: string;
            /**
             * @type string | undefined
            */
            price?: string;
            /**
             * @type number | undefined
            */
            price_usdc?: number;
            /**
             * @type string | undefined
            */
            description?: string;
        }[];
        /**
         * @type string | undefined
        */
        network?: string;
        /**
         * @type string | undefined
        */
        payment_token?: string;
    };
};

export type X402ControllerGetX402InfoQueryResponse = X402ControllerGetX402Info200;

export type X402ControllerGetX402InfoQuery = {
    Response: X402ControllerGetX402Info200;
    Errors: any;
};