/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Server health status
*/
export type X402ControllerHealth200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type string | undefined
        */
        status?: string;
        /**
         * @type string | undefined
        */
        version?: string;
        /**
         * @type string | undefined
        */
        network?: string;
        /**
         * @type number | undefined
        */
        uptime?: number;
        /**
         * @type number | undefined
        */
        market_count?: number;
    };
};

export type X402ControllerHealthQueryResponse = X402ControllerHealth200;

export type X402ControllerHealthQuery = {
    Response: X402ControllerHealth200;
    Errors: any;
};