/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type X402ControllerGetMarketNewsPathParams = {
    /**
     * @description Market ID (on-chain PDA address)
     * @type string
    */
    id: string;
};

/**
 * @description Market news
*/
export type X402ControllerGetMarketNews200 = any;

/**
 * @description Payment required
*/
export type X402ControllerGetMarketNews402 = any;

export type X402ControllerGetMarketNewsQueryResponse = X402ControllerGetMarketNews200;

export type X402ControllerGetMarketNewsQuery = {
    Response: X402ControllerGetMarketNews200;
    PathParams: X402ControllerGetMarketNewsPathParams;
    Errors: X402ControllerGetMarketNews402;
};