/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GenerateProofDto } from "@/lib/api-client/types/generate-proof-dto";

export type ZkControllerGenerateProof201 = any;

export type ZkControllerGenerateProofMutationRequest = GenerateProofDto;

export type ZkControllerGenerateProofMutationResponse = ZkControllerGenerateProof201;

export type ZkControllerGenerateProofMutation = {
    Response: ZkControllerGenerateProof201;
    Request: ZkControllerGenerateProofMutationRequest;
    Errors: any;
};