/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ZkControllerDeleteNotePathParams = {
    /**
     * @description Commitment hash
     * @type string
    */
    commitment: string;
};

export type ZkControllerDeleteNote200 = any;

export type ZkControllerDeleteNoteMutationResponse = ZkControllerDeleteNote200;

export type ZkControllerDeleteNoteMutation = {
    Response: ZkControllerDeleteNote200;
    PathParams: ZkControllerDeleteNotePathParams;
    Errors: any;
};