/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ZkControllerGetNotesQueryParams = {
    /**
     * @description Filter by pool address
     * @type string | undefined
    */
    poolAddress?: string;
    /**
     * @description Only return unspent notes
     * @type boolean | undefined
    */
    unspentOnly?: boolean;
};

export type ZkControllerGetNotes200 = any;

export type ZkControllerGetNotesQueryResponse = ZkControllerGetNotes200;

export type ZkControllerGetNotesQuery = {
    Response: ZkControllerGetNotes200;
    QueryParams: ZkControllerGetNotesQueryParams;
    Errors: any;
};