/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ZkControllerGetMerkleTreePathParams = {
    /**
     * @description Shielded pool address
     * @type string
    */
    poolAddress: string;
};

export type ZkControllerGetMerkleTree200 = any;

export type ZkControllerGetMerkleTreeQueryResponse = ZkControllerGetMerkleTree200;

export type ZkControllerGetMerkleTreeQuery = {
    Response: ZkControllerGetMerkleTree200;
    PathParams: ZkControllerGetMerkleTreePathParams;
    Errors: any;
};