/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ZkControllerGetNoteByCommitmentPathParams = {
    /**
     * @description Commitment hash
     * @type string
    */
    commitment: string;
};

export type ZkControllerGetNoteByCommitment200 = any;

export type ZkControllerGetNoteByCommitmentQueryResponse = ZkControllerGetNoteByCommitment200;

export type ZkControllerGetNoteByCommitmentQuery = {
    Response: ZkControllerGetNoteByCommitment200;
    PathParams: ZkControllerGetNoteByCommitmentPathParams;
    Errors: any;
};