/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StoreNullifierDto } from "@/lib/api-client/types/store-nullifier-dto";

export type ZkControllerMarkNullifierUsed201 = any;

export type ZkControllerMarkNullifierUsedMutationRequest = StoreNullifierDto;

export type ZkControllerMarkNullifierUsedMutationResponse = ZkControllerMarkNullifierUsed201;

export type ZkControllerMarkNullifierUsedMutation = {
    Response: ZkControllerMarkNullifierUsed201;
    Request: ZkControllerMarkNullifierUsedMutationRequest;
    Errors: any;
};