/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ZkControllerGetCommitmentsByBatchPathParams = {
    /**
     * @description Shielded pool address
     * @type string
    */
    poolAddress: string;
    /**
     * @description Batch number
     * @type string
    */
    batchNumber: string;
};

export type ZkControllerGetCommitmentsByBatch200 = any;

export type ZkControllerGetCommitmentsByBatchQueryResponse = ZkControllerGetCommitmentsByBatch200;

export type ZkControllerGetCommitmentsByBatchQuery = {
    Response: ZkControllerGetCommitmentsByBatch200;
    PathParams: ZkControllerGetCommitmentsByBatchPathParams;
    Errors: any;
};