/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StoreCommitmentDto } from "@/lib/api-client/types/store-commitment-dto";

export type ZkControllerStoreCommitment201 = any;

export type ZkControllerStoreCommitmentMutationRequest = StoreCommitmentDto;

export type ZkControllerStoreCommitmentMutationResponse = ZkControllerStoreCommitment201;

export type ZkControllerStoreCommitmentMutation = {
    Response: ZkControllerStoreCommitment201;
    Request: ZkControllerStoreCommitmentMutationRequest;
    Errors: any;
};