/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ZkControllerStoreCommitments201 = any;

export type ZkControllerStoreCommitmentsMutationRequest = string[];

export type ZkControllerStoreCommitmentsMutationResponse = ZkControllerStoreCommitments201;

export type ZkControllerStoreCommitmentsMutation = {
    Response: ZkControllerStoreCommitments201;
    Request: ZkControllerStoreCommitmentsMutationRequest;
    Errors: any;
};