/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ZkControllerGetLatestBatchSnapshotPathParams = {
    /**
     * @description Shielded pool address
     * @type string
    */
    poolAddress: string;
};

export type ZkControllerGetLatestBatchSnapshot200 = any;

export type ZkControllerGetLatestBatchSnapshotQueryResponse = ZkControllerGetLatestBatchSnapshot200;

export type ZkControllerGetLatestBatchSnapshotQuery = {
    Response: ZkControllerGetLatestBatchSnapshot200;
    PathParams: ZkControllerGetLatestBatchSnapshotPathParams;
    Errors: any;
};