/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ZkControllerMarkNoteSpentPathParams = {
    /**
     * @description Commitment hash
     * @type string
    */
    commitment: string;
};

export type ZkControllerMarkNoteSpent200 = any;

export type ZkControllerMarkNoteSpentMutationResponse = ZkControllerMarkNoteSpent200;

export type ZkControllerMarkNoteSpentMutation = {
    Response: ZkControllerMarkNoteSpent200;
    PathParams: ZkControllerMarkNoteSpentPathParams;
    Errors: any;
};