/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StoreNoteDto } from "@/lib/api-client/types/store-note-dto";

export type ZkControllerStoreNote201 = any;

export type ZkControllerStoreNoteMutationRequest = StoreNoteDto;

export type ZkControllerStoreNoteMutationResponse = ZkControllerStoreNote201;

export type ZkControllerStoreNoteMutation = {
    Response: ZkControllerStoreNote201;
    Request: ZkControllerStoreNoteMutationRequest;
    Errors: any;
};