/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { MetricsControllerGetDailyMetricsQueryResponse, MetricsControllerGetDailyMetricsQueryParams, MetricsControllerGetDailyMetrics403 } from "@/lib/api-client/types/metrics-controller-get-daily-metrics";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { metricsControllerGetDailyMetrics } from "@/lib/api-client/client/metrics-controller-get-daily-metrics";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const metricsControllerGetDailyMetricsQueryKey = (params: MetricsControllerGetDailyMetricsQueryParams = {}) => [{ url: '/api/metrics/daily' }, ...(params ? [params] : [])] as const

export type MetricsControllerGetDailyMetricsQueryKey = ReturnType<typeof metricsControllerGetDailyMetricsQueryKey>

export function metricsControllerGetDailyMetricsQueryOptions(params?: MetricsControllerGetDailyMetricsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = metricsControllerGetDailyMetricsQueryKey(params)
        return queryOptions<MetricsControllerGetDailyMetricsQueryResponse, ResponseErrorConfig<MetricsControllerGetDailyMetrics403>, MetricsControllerGetDailyMetricsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return metricsControllerGetDailyMetrics(params, config)
         },
        })

}

/**
 * @summary Get daily metrics for charts (requires admin)
 * {@link /api/metrics/daily}
 */
export function useMetricsControllerGetDailyMetrics<TData = MetricsControllerGetDailyMetricsQueryResponse, TQueryData = MetricsControllerGetDailyMetricsQueryResponse, TQueryKey extends QueryKey = MetricsControllerGetDailyMetricsQueryKey>(params?: MetricsControllerGetDailyMetricsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<MetricsControllerGetDailyMetricsQueryResponse, ResponseErrorConfig<MetricsControllerGetDailyMetrics403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? metricsControllerGetDailyMetricsQueryKey(params)
         

         const query = useQuery({
          ...metricsControllerGetDailyMetricsQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<MetricsControllerGetDailyMetrics403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}