/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerIsNullifierUsedQueryResponse, ZkControllerIsNullifierUsedPathParams } from "@/lib/api-client/types/zk-controller-is-nullifier-used";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { zkControllerIsNullifierUsed } from "@/lib/api-client/client/zk-controller-is-nullifier-used";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const zkControllerIsNullifierUsedSuspenseQueryKey = (poolAddress: ZkControllerIsNullifierUsedPathParams["poolAddress"], nullifierHash: ZkControllerIsNullifierUsedPathParams["nullifierHash"]) => [{ url: '/api/zk/nullifiers/:poolAddress/:nullifierHash', params: {poolAddress:poolAddress,nullifierHash:nullifierHash} }] as const

export type ZkControllerIsNullifierUsedSuspenseQueryKey = ReturnType<typeof zkControllerIsNullifierUsedSuspenseQueryKey>

export function zkControllerIsNullifierUsedSuspenseQueryOptions(poolAddress: ZkControllerIsNullifierUsedPathParams["poolAddress"], nullifierHash: ZkControllerIsNullifierUsedPathParams["nullifierHash"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerIsNullifierUsedSuspenseQueryKey(poolAddress, nullifierHash)
        return queryOptions<ZkControllerIsNullifierUsedQueryResponse, ResponseErrorConfig<Error>, ZkControllerIsNullifierUsedQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress&& nullifierHash),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerIsNullifierUsed(poolAddress, nullifierHash, config)
         },
        })

}

/**
 * @summary Check if a nullifier has been used
 * {@link /api/zk/nullifiers/:poolAddress/:nullifierHash}
 */
export function useZkControllerIsNullifierUsedSuspense<TData = ZkControllerIsNullifierUsedQueryResponse, TQueryKey extends QueryKey = ZkControllerIsNullifierUsedSuspenseQueryKey>(poolAddress: ZkControllerIsNullifierUsedPathParams["poolAddress"], nullifierHash: ZkControllerIsNullifierUsedPathParams["nullifierHash"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ZkControllerIsNullifierUsedQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerIsNullifierUsedSuspenseQueryKey(poolAddress, nullifierHash)
         

         const query = useSuspenseQuery({
          ...zkControllerIsNullifierUsedSuspenseQueryOptions(poolAddress, nullifierHash, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}