/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminControllerListAdminsQueryResponse, AdminControllerListAdmins403 } from "@/lib/api-client/types/admin-controller-list-admins";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { adminControllerListAdmins } from "@/lib/api-client/client/admin-controller-list-admins";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const adminControllerListAdminsQueryKey = () => [{ url: '/api/admin/list' }] as const

export type AdminControllerListAdminsQueryKey = ReturnType<typeof adminControllerListAdminsQueryKey>

export function adminControllerListAdminsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerListAdminsQueryKey()
        return queryOptions<AdminControllerListAdminsQueryResponse, ResponseErrorConfig<AdminControllerListAdmins403>, AdminControllerListAdminsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return adminControllerListAdmins(config)
         },
        })

}

/**
 * @summary Get all admins (requires admin)
 * {@link /api/admin/list}
 */
export function useAdminControllerListAdmins<TData = AdminControllerListAdminsQueryResponse, TQueryData = AdminControllerListAdminsQueryResponse, TQueryKey extends QueryKey = AdminControllerListAdminsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<AdminControllerListAdminsQueryResponse, ResponseErrorConfig<AdminControllerListAdmins403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? adminControllerListAdminsQueryKey()
         

         const query = useQuery({
          ...adminControllerListAdminsQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<AdminControllerListAdmins403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}