/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { X402ControllerGetPositionsQueryResponse, X402ControllerGetPositionsQueryParams } from "@/lib/api-client/types/x402-controller-get-positions";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { x402ControllerGetPositions } from "@/lib/api-client/client/x402-controller-get-positions";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const x402ControllerGetPositionsQueryKey = (params: X402ControllerGetPositionsQueryParams) => [{ url: '/api/v1/positions' }, ...(params ? [params] : [])] as const

export type X402ControllerGetPositionsQueryKey = ReturnType<typeof x402ControllerGetPositionsQueryKey>

export function x402ControllerGetPositionsQueryOptions(params: X402ControllerGetPositionsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = x402ControllerGetPositionsQueryKey(params)
        return queryOptions<X402ControllerGetPositionsQueryResponse, ResponseErrorConfig<Error>, X402ControllerGetPositionsQueryResponse, typeof queryKey>({
         enabled: !!(params),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return x402ControllerGetPositions(params, config)
         },
        })

}

/**
 * @description Returns position details for given commitment hashes with current valuations.
 * @summary Get positions by commitment hashes (free)
 * {@link /api/v1/positions}
 */
export function useX402ControllerGetPositions<TData = X402ControllerGetPositionsQueryResponse, TQueryData = X402ControllerGetPositionsQueryResponse, TQueryKey extends QueryKey = X402ControllerGetPositionsQueryKey>(params: X402ControllerGetPositionsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<X402ControllerGetPositionsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? x402ControllerGetPositionsQueryKey(params)
         

         const query = useQuery({
          ...x402ControllerGetPositionsQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}