/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { NotificationControllerSetEmailMutationRequest, NotificationControllerSetEmailMutationResponse } from "@/lib/api-client/types/notification-controller-set-email";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { notificationControllerSetEmail } from "@/lib/api-client/client/notification-controller-set-email";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const notificationControllerSetEmailMutationKey = () => [{ url: '/api/notifications/email' }] as const

export type NotificationControllerSetEmailMutationKey = ReturnType<typeof notificationControllerSetEmailMutationKey>

export function notificationControllerSetEmailMutationOptions<TContext = unknown>(config: Partial<RequestConfig<NotificationControllerSetEmailMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = notificationControllerSetEmailMutationKey()
        return mutationOptions<NotificationControllerSetEmailMutationResponse, ResponseErrorConfig<Error>, {data: NotificationControllerSetEmailMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return notificationControllerSetEmail(data, config)
          },
        })

}

/**
 * @summary Set or update email for notifications (triggers verification)
 * {@link /api/notifications/email}
 */
export function useNotificationControllerSetEmail<TContext>(options: 
{
  mutation?: UseMutationOptions<NotificationControllerSetEmailMutationResponse, ResponseErrorConfig<Error>, {data: NotificationControllerSetEmailMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<NotificationControllerSetEmailMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? notificationControllerSetEmailMutationKey()

          const baseOptions = notificationControllerSetEmailMutationOptions(config) as UseMutationOptions<NotificationControllerSetEmailMutationResponse, ResponseErrorConfig<Error>, {data: NotificationControllerSetEmailMutationRequest}, TContext>
          

          return useMutation<NotificationControllerSetEmailMutationResponse, ResponseErrorConfig<Error>, {data: NotificationControllerSetEmailMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<NotificationControllerSetEmailMutationResponse, ResponseErrorConfig<Error>, {data: NotificationControllerSetEmailMutationRequest}, TContext>
      
}