/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerStoreBatchSnapshotMutationRequest, ZkControllerStoreBatchSnapshotMutationResponse } from "@/lib/api-client/types/zk-controller-store-batch-snapshot";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { zkControllerStoreBatchSnapshot } from "@/lib/api-client/client/zk-controller-store-batch-snapshot";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const zkControllerStoreBatchSnapshotMutationKey = () => [{ url: '/api/zk/batch-snapshots' }] as const

export type ZkControllerStoreBatchSnapshotMutationKey = ReturnType<typeof zkControllerStoreBatchSnapshotMutationKey>

export function zkControllerStoreBatchSnapshotMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ZkControllerStoreBatchSnapshotMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = zkControllerStoreBatchSnapshotMutationKey()
        return mutationOptions<ZkControllerStoreBatchSnapshotMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreBatchSnapshotMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return zkControllerStoreBatchSnapshot(data, config)
          },
        })

}

/**
 * @summary Store a batch snapshot (called when batch is finalized on-chain)
 * {@link /api/zk/batch-snapshots}
 */
export function useZkControllerStoreBatchSnapshot<TContext>(options: 
{
  mutation?: UseMutationOptions<ZkControllerStoreBatchSnapshotMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreBatchSnapshotMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ZkControllerStoreBatchSnapshotMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? zkControllerStoreBatchSnapshotMutationKey()

          const baseOptions = zkControllerStoreBatchSnapshotMutationOptions(config) as UseMutationOptions<ZkControllerStoreBatchSnapshotMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreBatchSnapshotMutationRequest}, TContext>
          

          return useMutation<ZkControllerStoreBatchSnapshotMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreBatchSnapshotMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ZkControllerStoreBatchSnapshotMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreBatchSnapshotMutationRequest}, TContext>
      
}