/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetBatchSnapshotsQueryResponse, ZkControllerGetBatchSnapshotsPathParams } from "@/lib/api-client/types/zk-controller-get-batch-snapshots";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { zkControllerGetBatchSnapshots } from "@/lib/api-client/client/zk-controller-get-batch-snapshots";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const zkControllerGetBatchSnapshotsSuspenseQueryKey = (poolAddress: ZkControllerGetBatchSnapshotsPathParams["poolAddress"]) => [{ url: '/api/zk/batch-snapshots/:poolAddress', params: {poolAddress:poolAddress} }] as const

export type ZkControllerGetBatchSnapshotsSuspenseQueryKey = ReturnType<typeof zkControllerGetBatchSnapshotsSuspenseQueryKey>

export function zkControllerGetBatchSnapshotsSuspenseQueryOptions(poolAddress: ZkControllerGetBatchSnapshotsPathParams["poolAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetBatchSnapshotsSuspenseQueryKey(poolAddress)
        return queryOptions<ZkControllerGetBatchSnapshotsQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetBatchSnapshotsQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetBatchSnapshots(poolAddress, config)
         },
        })

}

/**
 * @summary Get all batch snapshots for a pool
 * {@link /api/zk/batch-snapshots/:poolAddress}
 */
export function useZkControllerGetBatchSnapshotsSuspense<TData = ZkControllerGetBatchSnapshotsQueryResponse, TQueryKey extends QueryKey = ZkControllerGetBatchSnapshotsSuspenseQueryKey>(poolAddress: ZkControllerGetBatchSnapshotsPathParams["poolAddress"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ZkControllerGetBatchSnapshotsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetBatchSnapshotsSuspenseQueryKey(poolAddress)
         

         const query = useSuspenseQuery({
          ...zkControllerGetBatchSnapshotsSuspenseQueryOptions(poolAddress, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}