/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { X402ControllerGetMarketNewsQueryResponse, X402ControllerGetMarketNewsPathParams, X402ControllerGetMarketNews402 } from "@/lib/api-client/types/x402-controller-get-market-news";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { x402ControllerGetMarketNews } from "@/lib/api-client/client/x402-controller-get-market-news";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const x402ControllerGetMarketNewsSuspenseQueryKey = (id: X402ControllerGetMarketNewsPathParams["id"]) => [{ url: '/api/v1/markets/:id/news', params: {id:id} }] as const

export type X402ControllerGetMarketNewsSuspenseQueryKey = ReturnType<typeof x402ControllerGetMarketNewsSuspenseQueryKey>

export function x402ControllerGetMarketNewsSuspenseQueryOptions(id: X402ControllerGetMarketNewsPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = x402ControllerGetMarketNewsSuspenseQueryKey(id)
        return queryOptions<X402ControllerGetMarketNewsQueryResponse, ResponseErrorConfig<X402ControllerGetMarketNews402>, X402ControllerGetMarketNewsQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return x402ControllerGetMarketNews(id, config)
         },
        })

}

/**
 * @description Returns news articles related to this market.
 * @summary Get market news (x402 paid: $0.01)
 * {@link /api/v1/markets/:id/news}
 */
export function useX402ControllerGetMarketNewsSuspense<TData = X402ControllerGetMarketNewsQueryResponse, TQueryKey extends QueryKey = X402ControllerGetMarketNewsSuspenseQueryKey>(id: X402ControllerGetMarketNewsPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<X402ControllerGetMarketNewsQueryResponse, ResponseErrorConfig<X402ControllerGetMarketNews402>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? x402ControllerGetMarketNewsSuspenseQueryKey(id)
         

         const query = useSuspenseQuery({
          ...x402ControllerGetMarketNewsSuspenseQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<X402ControllerGetMarketNews402>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}