/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AppControllerGetHelloQueryResponse } from "@/lib/api-client/types/app-controller-get-hello";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { appControllerGetHello } from "@/lib/api-client/client/app-controller-get-hello";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const appControllerGetHelloSuspenseQueryKey = () => [{ url: '/api' }] as const

export type AppControllerGetHelloSuspenseQueryKey = ReturnType<typeof appControllerGetHelloSuspenseQueryKey>

export function appControllerGetHelloSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = appControllerGetHelloSuspenseQueryKey()
        return queryOptions<AppControllerGetHelloQueryResponse, ResponseErrorConfig<Error>, AppControllerGetHelloQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return appControllerGetHello(config)
         },
        })

}

/**
 * {@link /api}
 */
export function useAppControllerGetHelloSuspense<TData = AppControllerGetHelloQueryResponse, TQueryKey extends QueryKey = AppControllerGetHelloSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AppControllerGetHelloQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? appControllerGetHelloSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...appControllerGetHelloSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}