/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { BlogControllerFindBySlugQueryResponse, BlogControllerFindBySlugPathParams } from "@/lib/api-client/types/blog-controller-find-by-slug";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { blogControllerFindBySlug } from "@/lib/api-client/client/blog-controller-find-by-slug";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const blogControllerFindBySlugQueryKey = (slug: BlogControllerFindBySlugPathParams["slug"]) => [{ url: '/api/blogs/:slug', params: {slug:slug} }] as const

export type BlogControllerFindBySlugQueryKey = ReturnType<typeof blogControllerFindBySlugQueryKey>

export function blogControllerFindBySlugQueryOptions(slug: BlogControllerFindBySlugPathParams["slug"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = blogControllerFindBySlugQueryKey(slug)
        return queryOptions<BlogControllerFindBySlugQueryResponse, ResponseErrorConfig<Error>, BlogControllerFindBySlugQueryResponse, typeof queryKey>({
         enabled: !!(slug),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return blogControllerFindBySlug(slug, config)
         },
        })

}

/**
 * @summary Get a blog post by slug
 * {@link /api/blogs/:slug}
 */
export function useBlogControllerFindBySlug<TData = BlogControllerFindBySlugQueryResponse, TQueryData = BlogControllerFindBySlugQueryResponse, TQueryKey extends QueryKey = BlogControllerFindBySlugQueryKey>(slug: BlogControllerFindBySlugPathParams["slug"], options: 
{
  query?: Partial<QueryObserverOptions<BlogControllerFindBySlugQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? blogControllerFindBySlugQueryKey(slug)
         

         const query = useQuery({
          ...blogControllerFindBySlugQueryOptions(slug, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}