/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { NotificationControllerVerifyEmailQueryResponse, NotificationControllerVerifyEmailQueryParams } from "@/lib/api-client/types/notification-controller-verify-email";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { notificationControllerVerifyEmail } from "@/lib/api-client/client/notification-controller-verify-email";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const notificationControllerVerifyEmailQueryKey = (params: NotificationControllerVerifyEmailQueryParams) => [{ url: '/api/notifications/email/verify' }, ...(params ? [params] : [])] as const

export type NotificationControllerVerifyEmailQueryKey = ReturnType<typeof notificationControllerVerifyEmailQueryKey>

export function notificationControllerVerifyEmailQueryOptions(params: NotificationControllerVerifyEmailQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = notificationControllerVerifyEmailQueryKey(params)
        return queryOptions<NotificationControllerVerifyEmailQueryResponse, ResponseErrorConfig<Error>, NotificationControllerVerifyEmailQueryResponse, typeof queryKey>({
         enabled: !!(params),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return notificationControllerVerifyEmail(params, config)
         },
        })

}

/**
 * @summary Verify email via signed token
 * {@link /api/notifications/email/verify}
 */
export function useNotificationControllerVerifyEmail<TData = NotificationControllerVerifyEmailQueryResponse, TQueryData = NotificationControllerVerifyEmailQueryResponse, TQueryKey extends QueryKey = NotificationControllerVerifyEmailQueryKey>(params: NotificationControllerVerifyEmailQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<NotificationControllerVerifyEmailQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? notificationControllerVerifyEmailQueryKey(params)
         

         const query = useQuery({
          ...notificationControllerVerifyEmailQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}