/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetNotesQueryResponse, ZkControllerGetNotesQueryParams } from "@/lib/api-client/types/zk-controller-get-notes";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { zkControllerGetNotes } from "@/lib/api-client/client/zk-controller-get-notes";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const zkControllerGetNotesQueryKey = (params: ZkControllerGetNotesQueryParams = {}) => [{ url: '/api/zk/notes' }, ...(params ? [params] : [])] as const

export type ZkControllerGetNotesQueryKey = ReturnType<typeof zkControllerGetNotesQueryKey>

export function zkControllerGetNotesQueryOptions(params?: ZkControllerGetNotesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetNotesQueryKey(params)
        return queryOptions<ZkControllerGetNotesQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetNotesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetNotes(params, config)
         },
        })

}

/**
 * @summary Get user's encrypted notes
 * {@link /api/zk/notes}
 */
export function useZkControllerGetNotes<TData = ZkControllerGetNotesQueryResponse, TQueryData = ZkControllerGetNotesQueryResponse, TQueryKey extends QueryKey = ZkControllerGetNotesQueryKey>(params?: ZkControllerGetNotesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ZkControllerGetNotesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetNotesQueryKey(params)
         

         const query = useQuery({
          ...zkControllerGetNotesQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}