/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerStoreCommitmentMutationRequest, ZkControllerStoreCommitmentMutationResponse } from "@/lib/api-client/types/zk-controller-store-commitment";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { zkControllerStoreCommitment } from "@/lib/api-client/client/zk-controller-store-commitment";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const zkControllerStoreCommitmentMutationKey = () => [{ url: '/api/zk/commitments' }] as const

export type ZkControllerStoreCommitmentMutationKey = ReturnType<typeof zkControllerStoreCommitmentMutationKey>

export function zkControllerStoreCommitmentMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ZkControllerStoreCommitmentMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = zkControllerStoreCommitmentMutationKey()
        return mutationOptions<ZkControllerStoreCommitmentMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreCommitmentMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return zkControllerStoreCommitment(data, config)
          },
        })

}

/**
 * @summary Index a new commitment (called after on-chain tx)
 * {@link /api/zk/commitments}
 */
export function useZkControllerStoreCommitment<TContext>(options: 
{
  mutation?: UseMutationOptions<ZkControllerStoreCommitmentMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreCommitmentMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ZkControllerStoreCommitmentMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? zkControllerStoreCommitmentMutationKey()

          const baseOptions = zkControllerStoreCommitmentMutationOptions(config) as UseMutationOptions<ZkControllerStoreCommitmentMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreCommitmentMutationRequest}, TContext>
          

          return useMutation<ZkControllerStoreCommitmentMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreCommitmentMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ZkControllerStoreCommitmentMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreCommitmentMutationRequest}, TContext>
      
}