/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminControllerCheckAdminQueryResponse, AdminControllerCheckAdminPathParams } from "@/lib/api-client/types/admin-controller-check-admin";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminControllerCheckAdmin } from "@/lib/api-client/client/admin-controller-check-admin";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminControllerCheckAdminSuspenseQueryKey = (walletAddress: AdminControllerCheckAdminPathParams["walletAddress"]) => [{ url: '/api/admin/check/:walletAddress', params: {walletAddress:walletAddress} }] as const

export type AdminControllerCheckAdminSuspenseQueryKey = ReturnType<typeof adminControllerCheckAdminSuspenseQueryKey>

export function adminControllerCheckAdminSuspenseQueryOptions(walletAddress: AdminControllerCheckAdminPathParams["walletAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerCheckAdminSuspenseQueryKey(walletAddress)
        return queryOptions<AdminControllerCheckAdminQueryResponse, ResponseErrorConfig<Error>, AdminControllerCheckAdminQueryResponse, typeof queryKey>({
         enabled: !!(walletAddress),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return adminControllerCheckAdmin(walletAddress, config)
         },
        })

}

/**
 * @summary Check if a wallet address is an admin
 * {@link /api/admin/check/:walletAddress}
 */
export function useAdminControllerCheckAdminSuspense<TData = AdminControllerCheckAdminQueryResponse, TQueryKey extends QueryKey = AdminControllerCheckAdminSuspenseQueryKey>(walletAddress: AdminControllerCheckAdminPathParams["walletAddress"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminControllerCheckAdminQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? adminControllerCheckAdminSuspenseQueryKey(walletAddress)
         

         const query = useSuspenseQuery({
          ...adminControllerCheckAdminSuspenseQueryOptions(walletAddress, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}