/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { X402ControllerResolveMarketQueryResponse, X402ControllerResolveMarketPathParams, X402ControllerResolveMarket400, X402ControllerResolveMarket402 } from "@/lib/api-client/types/x402-controller-resolve-market";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { x402ControllerResolveMarket } from "@/lib/api-client/client/x402-controller-resolve-market";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const x402ControllerResolveMarketSuspenseQueryKey = (id: X402ControllerResolveMarketPathParams["id"]) => [{ url: '/api/v1/markets/:id/resolve', params: {id:id} }] as const

export type X402ControllerResolveMarketSuspenseQueryKey = ReturnType<typeof x402ControllerResolveMarketSuspenseQueryKey>

export function x402ControllerResolveMarketSuspenseQueryOptions(id: X402ControllerResolveMarketPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = x402ControllerResolveMarketSuspenseQueryKey(id)
        return queryOptions<X402ControllerResolveMarketQueryResponse, ResponseErrorConfig<X402ControllerResolveMarket400 | X402ControllerResolveMarket402>, X402ControllerResolveMarketQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return x402ControllerResolveMarket(id, config)
         },
        })

}

/**
 * @description Triggers oracle-based market resolution. Returns resolution result or reason if not yet resolvable.
 * @summary Resolve a market via oracle (x402 paid: $0.05)
 * {@link /api/v1/markets/:id/resolve}
 */
export function useX402ControllerResolveMarketSuspense<TData = X402ControllerResolveMarketQueryResponse, TQueryKey extends QueryKey = X402ControllerResolveMarketSuspenseQueryKey>(id: X402ControllerResolveMarketPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<X402ControllerResolveMarketQueryResponse, ResponseErrorConfig<X402ControllerResolveMarket400 | X402ControllerResolveMarket402>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? x402ControllerResolveMarketSuspenseQueryKey(id)
         

         const query = useSuspenseQuery({
          ...x402ControllerResolveMarketSuspenseQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<X402ControllerResolveMarket400 | X402ControllerResolveMarket402>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}