/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ChatControllerGetHistoryQueryResponse, ChatControllerGetHistoryPathParams } from "@/lib/api-client/types/chat-controller-get-history";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { chatControllerGetHistory } from "@/lib/api-client/client/chat-controller-get-history";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const chatControllerGetHistorySuspenseQueryKey = (id: ChatControllerGetHistoryPathParams["id"]) => [{ url: '/api/chat/history/:id', params: {id:id} }] as const

export type ChatControllerGetHistorySuspenseQueryKey = ReturnType<typeof chatControllerGetHistorySuspenseQueryKey>

export function chatControllerGetHistorySuspenseQueryOptions(id: ChatControllerGetHistoryPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = chatControllerGetHistorySuspenseQueryKey(id)
        return queryOptions<ChatControllerGetHistoryQueryResponse, ResponseErrorConfig<Error>, ChatControllerGetHistoryQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return chatControllerGetHistory(id, config)
         },
        })

}

/**
 * {@link /api/chat/history/:id}
 */
export function useChatControllerGetHistorySuspense<TData = ChatControllerGetHistoryQueryResponse, TQueryKey extends QueryKey = ChatControllerGetHistorySuspenseQueryKey>(id: ChatControllerGetHistoryPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ChatControllerGetHistoryQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? chatControllerGetHistorySuspenseQueryKey(id)
         

         const query = useSuspenseQuery({
          ...chatControllerGetHistorySuspenseQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}