/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PortfolioControllerGetWatchlistQueryResponse } from "@/lib/api-client/types/portfolio-controller-get-watchlist";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { portfolioControllerGetWatchlist } from "@/lib/api-client/client/portfolio-controller-get-watchlist";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const portfolioControllerGetWatchlistSuspenseQueryKey = () => [{ url: '/api/portfolio/watchlist' }] as const

export type PortfolioControllerGetWatchlistSuspenseQueryKey = ReturnType<typeof portfolioControllerGetWatchlistSuspenseQueryKey>

export function portfolioControllerGetWatchlistSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = portfolioControllerGetWatchlistSuspenseQueryKey()
        return queryOptions<PortfolioControllerGetWatchlistQueryResponse, ResponseErrorConfig<Error>, PortfolioControllerGetWatchlistQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return portfolioControllerGetWatchlist(config)
         },
        })

}

/**
 * @summary Get user watchlist
 * {@link /api/portfolio/watchlist}
 */
export function usePortfolioControllerGetWatchlistSuspense<TData = PortfolioControllerGetWatchlistQueryResponse, TQueryKey extends QueryKey = PortfolioControllerGetWatchlistSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<PortfolioControllerGetWatchlistQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? portfolioControllerGetWatchlistSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...portfolioControllerGetWatchlistSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}