/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { X402ControllerCreateMarketMutationRequest, X402ControllerCreateMarketMutationResponse, X402ControllerCreateMarket400, X402ControllerCreateMarket402 } from "@/lib/api-client/types/x402-controller-create-market";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { x402ControllerCreateMarket } from "@/lib/api-client/client/x402-controller-create-market";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const x402ControllerCreateMarketMutationKey = () => [{ url: '/api/v1/markets/create' }] as const

export type X402ControllerCreateMarketMutationKey = ReturnType<typeof x402ControllerCreateMarketMutationKey>

export function x402ControllerCreateMarketMutationOptions<TContext = unknown>(config: Partial<RequestConfig<X402ControllerCreateMarketMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = x402ControllerCreateMarketMutationKey()
        return mutationOptions<X402ControllerCreateMarketMutationResponse, ResponseErrorConfig<X402ControllerCreateMarket400 | X402ControllerCreateMarket402>, {data: X402ControllerCreateMarketMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return x402ControllerCreateMarket(data, config)
          },
        })

}

/**
 * @description Creates a new prediction market on-chain for a PumpFun token. Requires x402 USDC payment of $0.50.
 * @summary Create a prediction market (x402 paid: $0.50)
 * {@link /api/v1/markets/create}
 */
export function useX402ControllerCreateMarket<TContext>(options: 
{
  mutation?: UseMutationOptions<X402ControllerCreateMarketMutationResponse, ResponseErrorConfig<X402ControllerCreateMarket400 | X402ControllerCreateMarket402>, {data: X402ControllerCreateMarketMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<X402ControllerCreateMarketMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? x402ControllerCreateMarketMutationKey()

          const baseOptions = x402ControllerCreateMarketMutationOptions(config) as UseMutationOptions<X402ControllerCreateMarketMutationResponse, ResponseErrorConfig<X402ControllerCreateMarket400 | X402ControllerCreateMarket402>, {data: X402ControllerCreateMarketMutationRequest}, TContext>
          

          return useMutation<X402ControllerCreateMarketMutationResponse, ResponseErrorConfig<X402ControllerCreateMarket400 | X402ControllerCreateMarket402>, {data: X402ControllerCreateMarketMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<X402ControllerCreateMarketMutationResponse, ResponseErrorConfig<X402ControllerCreateMarket400 | X402ControllerCreateMarket402>, {data: X402ControllerCreateMarketMutationRequest}, TContext>
      
}