/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TokenDataControllerGetBinanceTokensQueryResponse } from "@/lib/api-client/types/token-data-controller-get-binance-tokens";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { tokenDataControllerGetBinanceTokens } from "@/lib/api-client/client/token-data-controller-get-binance-tokens";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const tokenDataControllerGetBinanceTokensSuspenseQueryKey = () => [{ url: '/api/token-data/binance/tokens' }] as const

export type TokenDataControllerGetBinanceTokensSuspenseQueryKey = ReturnType<typeof tokenDataControllerGetBinanceTokensSuspenseQueryKey>

export function tokenDataControllerGetBinanceTokensSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = tokenDataControllerGetBinanceTokensSuspenseQueryKey()
        return queryOptions<TokenDataControllerGetBinanceTokensQueryResponse, ResponseErrorConfig<Error>, TokenDataControllerGetBinanceTokensQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return tokenDataControllerGetBinanceTokens(config)
         },
        })

}

/**
 * @summary Get all Binance USDT trading pairs with token names
 * {@link /api/token-data/binance/tokens}
 */
export function useTokenDataControllerGetBinanceTokensSuspense<TData = TokenDataControllerGetBinanceTokensQueryResponse, TQueryKey extends QueryKey = TokenDataControllerGetBinanceTokensSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<TokenDataControllerGetBinanceTokensQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? tokenDataControllerGetBinanceTokensSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...tokenDataControllerGetBinanceTokensSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}