/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { X402ControllerGetPrivacyProofQueryResponse, X402ControllerGetPrivacyProofPathParams, X402ControllerGetPrivacyProofQueryParams, X402ControllerGetPrivacyProof402, X402ControllerGetPrivacyProof404 } from "@/lib/api-client/types/x402-controller-get-privacy-proof";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { x402ControllerGetPrivacyProof } from "@/lib/api-client/client/x402-controller-get-privacy-proof";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const x402ControllerGetPrivacyProofSuspenseQueryKey = (id: X402ControllerGetPrivacyProofPathParams["id"], params: X402ControllerGetPrivacyProofQueryParams) => [{ url: '/api/v1/markets/:id/privacy-proof', params: {id:id} }, ...(params ? [params] : [])] as const

export type X402ControllerGetPrivacyProofSuspenseQueryKey = ReturnType<typeof x402ControllerGetPrivacyProofSuspenseQueryKey>

export function x402ControllerGetPrivacyProofSuspenseQueryOptions(id: X402ControllerGetPrivacyProofPathParams["id"], params: X402ControllerGetPrivacyProofQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = x402ControllerGetPrivacyProofSuspenseQueryKey(id, params)
        return queryOptions<X402ControllerGetPrivacyProofQueryResponse, ResponseErrorConfig<X402ControllerGetPrivacyProof402 | X402ControllerGetPrivacyProof404>, X402ControllerGetPrivacyProofQueryResponse, typeof queryKey>({
         enabled: !!(id&& params),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return x402ControllerGetPrivacyProof(id, params, config)
         },
        })

}

/**
 * @description Generates a ZK Merkle inclusion proof for a prediction position identified by commitment hash.
 * @summary Get privacy proof for a position (x402 paid: $0.10)
 * {@link /api/v1/markets/:id/privacy-proof}
 */
export function useX402ControllerGetPrivacyProofSuspense<TData = X402ControllerGetPrivacyProofQueryResponse, TQueryKey extends QueryKey = X402ControllerGetPrivacyProofSuspenseQueryKey>(id: X402ControllerGetPrivacyProofPathParams["id"], params: X402ControllerGetPrivacyProofQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<X402ControllerGetPrivacyProofQueryResponse, ResponseErrorConfig<X402ControllerGetPrivacyProof402 | X402ControllerGetPrivacyProof404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? x402ControllerGetPrivacyProofSuspenseQueryKey(id, params)
         

         const query = useSuspenseQuery({
          ...x402ControllerGetPrivacyProofSuspenseQueryOptions(id, params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<X402ControllerGetPrivacyProof402 | X402ControllerGetPrivacyProof404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}