/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { BlogControllerFindBySlugQueryResponse, BlogControllerFindBySlugPathParams } from "@/lib/api-client/types/blog-controller-find-by-slug";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { blogControllerFindBySlug } from "@/lib/api-client/client/blog-controller-find-by-slug";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const blogControllerFindBySlugSuspenseQueryKey = (slug: BlogControllerFindBySlugPathParams["slug"]) => [{ url: '/api/blogs/:slug', params: {slug:slug} }] as const

export type BlogControllerFindBySlugSuspenseQueryKey = ReturnType<typeof blogControllerFindBySlugSuspenseQueryKey>

export function blogControllerFindBySlugSuspenseQueryOptions(slug: BlogControllerFindBySlugPathParams["slug"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = blogControllerFindBySlugSuspenseQueryKey(slug)
        return queryOptions<BlogControllerFindBySlugQueryResponse, ResponseErrorConfig<Error>, BlogControllerFindBySlugQueryResponse, typeof queryKey>({
         enabled: !!(slug),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return blogControllerFindBySlug(slug, config)
         },
        })

}

/**
 * @summary Get a blog post by slug
 * {@link /api/blogs/:slug}
 */
export function useBlogControllerFindBySlugSuspense<TData = BlogControllerFindBySlugQueryResponse, TQueryKey extends QueryKey = BlogControllerFindBySlugSuspenseQueryKey>(slug: BlogControllerFindBySlugPathParams["slug"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<BlogControllerFindBySlugQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? blogControllerFindBySlugSuspenseQueryKey(slug)
         

         const query = useSuspenseQuery({
          ...blogControllerFindBySlugSuspenseQueryOptions(slug, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}