/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UserControllerUpdateProfileMutationRequest, UserControllerUpdateProfileMutationResponse, UserControllerUpdateProfile401 } from "@/lib/api-client/types/user-controller-update-profile";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { userControllerUpdateProfile } from "@/lib/api-client/client/user-controller-update-profile";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const userControllerUpdateProfileMutationKey = () => [{ url: '/api/users/me' }] as const

export type UserControllerUpdateProfileMutationKey = ReturnType<typeof userControllerUpdateProfileMutationKey>

export function userControllerUpdateProfileMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UserControllerUpdateProfileMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = userControllerUpdateProfileMutationKey()
        return mutationOptions<UserControllerUpdateProfileMutationResponse, ResponseErrorConfig<UserControllerUpdateProfile401>, {data?: UserControllerUpdateProfileMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return userControllerUpdateProfile(data, config)
          },
        })

}

/**
 * @summary Update current user profile
 * {@link /api/users/me}
 */
export function useUserControllerUpdateProfile<TContext>(options: 
{
  mutation?: UseMutationOptions<UserControllerUpdateProfileMutationResponse, ResponseErrorConfig<UserControllerUpdateProfile401>, {data?: UserControllerUpdateProfileMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UserControllerUpdateProfileMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? userControllerUpdateProfileMutationKey()

          const baseOptions = userControllerUpdateProfileMutationOptions(config) as UseMutationOptions<UserControllerUpdateProfileMutationResponse, ResponseErrorConfig<UserControllerUpdateProfile401>, {data?: UserControllerUpdateProfileMutationRequest}, TContext>
          

          return useMutation<UserControllerUpdateProfileMutationResponse, ResponseErrorConfig<UserControllerUpdateProfile401>, {data?: UserControllerUpdateProfileMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UserControllerUpdateProfileMutationResponse, ResponseErrorConfig<UserControllerUpdateProfile401>, {data?: UserControllerUpdateProfileMutationRequest}, TContext>
      
}