/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerMarkNullifierUsedMutationRequest, ZkControllerMarkNullifierUsedMutationResponse } from "@/lib/api-client/types/zk-controller-mark-nullifier-used";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { zkControllerMarkNullifierUsed } from "@/lib/api-client/client/zk-controller-mark-nullifier-used";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const zkControllerMarkNullifierUsedMutationKey = () => [{ url: '/api/zk/nullifiers' }] as const

export type ZkControllerMarkNullifierUsedMutationKey = ReturnType<typeof zkControllerMarkNullifierUsedMutationKey>

export function zkControllerMarkNullifierUsedMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ZkControllerMarkNullifierUsedMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = zkControllerMarkNullifierUsedMutationKey()
        return mutationOptions<ZkControllerMarkNullifierUsedMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerMarkNullifierUsedMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return zkControllerMarkNullifierUsed(data, config)
          },
        })

}

/**
 * @summary Mark a nullifier as used
 * {@link /api/zk/nullifiers}
 */
export function useZkControllerMarkNullifierUsed<TContext>(options: 
{
  mutation?: UseMutationOptions<ZkControllerMarkNullifierUsedMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerMarkNullifierUsedMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ZkControllerMarkNullifierUsedMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? zkControllerMarkNullifierUsedMutationKey()

          const baseOptions = zkControllerMarkNullifierUsedMutationOptions(config) as UseMutationOptions<ZkControllerMarkNullifierUsedMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerMarkNullifierUsedMutationRequest}, TContext>
          

          return useMutation<ZkControllerMarkNullifierUsedMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerMarkNullifierUsedMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ZkControllerMarkNullifierUsedMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerMarkNullifierUsedMutationRequest}, TContext>
      
}