/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GraduationControllerGetTrendingQueryResponse, GraduationControllerGetTrendingQueryParams } from "@/lib/api-client/types/graduation-controller-get-trending";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { graduationControllerGetTrending } from "@/lib/api-client/client/graduation-controller-get-trending";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const graduationControllerGetTrendingQueryKey = (params: GraduationControllerGetTrendingQueryParams = {}) => [{ url: '/api/graduation/trending' }, ...(params ? [params] : [])] as const

export type GraduationControllerGetTrendingQueryKey = ReturnType<typeof graduationControllerGetTrendingQueryKey>

export function graduationControllerGetTrendingQueryOptions(params?: GraduationControllerGetTrendingQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = graduationControllerGetTrendingQueryKey(params)
        return queryOptions<GraduationControllerGetTrendingQueryResponse, ResponseErrorConfig<Error>, GraduationControllerGetTrendingQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return graduationControllerGetTrending(params, config)
         },
        })

}

/**
 * @summary Get trending pump.fun tokens on bonding curve
 * {@link /api/graduation/trending}
 */
export function useGraduationControllerGetTrending<TData = GraduationControllerGetTrendingQueryResponse, TQueryData = GraduationControllerGetTrendingQueryResponse, TQueryKey extends QueryKey = GraduationControllerGetTrendingQueryKey>(params?: GraduationControllerGetTrendingQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GraduationControllerGetTrendingQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? graduationControllerGetTrendingQueryKey(params)
         

         const query = useQuery({
          ...graduationControllerGetTrendingQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}