/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminControllerAddAdminMutationResponse, AdminControllerAddAdminPathParams, AdminControllerAddAdmin403 } from "@/lib/api-client/types/admin-controller-add-admin";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminControllerAddAdmin } from "@/lib/api-client/client/admin-controller-add-admin";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminControllerAddAdminMutationKey = () => [{ url: '/api/admin/add/:walletAddress' }] as const

export type AdminControllerAddAdminMutationKey = ReturnType<typeof adminControllerAddAdminMutationKey>

export function adminControllerAddAdminMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = adminControllerAddAdminMutationKey()
        return mutationOptions<AdminControllerAddAdminMutationResponse, ResponseErrorConfig<AdminControllerAddAdmin403>, {walletAddress: AdminControllerAddAdminPathParams["walletAddress"]}, TContext>({
          mutationKey,
          mutationFn: async({ walletAddress }) => {
            return adminControllerAddAdmin(walletAddress, config)
          },
        })

}

/**
 * @summary Add a new admin (requires admin)
 * {@link /api/admin/add/:walletAddress}
 */
export function useAdminControllerAddAdmin<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminControllerAddAdminMutationResponse, ResponseErrorConfig<AdminControllerAddAdmin403>, {walletAddress: AdminControllerAddAdminPathParams["walletAddress"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminControllerAddAdminMutationKey()

          const baseOptions = adminControllerAddAdminMutationOptions(config) as UseMutationOptions<AdminControllerAddAdminMutationResponse, ResponseErrorConfig<AdminControllerAddAdmin403>, {walletAddress: AdminControllerAddAdminPathParams["walletAddress"]}, TContext>
          

          return useMutation<AdminControllerAddAdminMutationResponse, ResponseErrorConfig<AdminControllerAddAdmin403>, {walletAddress: AdminControllerAddAdminPathParams["walletAddress"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminControllerAddAdminMutationResponse, ResponseErrorConfig<AdminControllerAddAdmin403>, {walletAddress: AdminControllerAddAdminPathParams["walletAddress"]}, TContext>
      
}