/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PortfolioControllerGetHistoryQueryResponse, PortfolioControllerGetHistoryPathParams, PortfolioControllerGetHistoryQueryParams } from "@/lib/api-client/types/portfolio-controller-get-history";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { portfolioControllerGetHistory } from "@/lib/api-client/client/portfolio-controller-get-history";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const portfolioControllerGetHistoryQueryKey = (wallet: PortfolioControllerGetHistoryPathParams["wallet"], params: PortfolioControllerGetHistoryQueryParams = {}) => [{ url: '/api/portfolio/:wallet/history', params: {wallet:wallet} }, ...(params ? [params] : [])] as const

export type PortfolioControllerGetHistoryQueryKey = ReturnType<typeof portfolioControllerGetHistoryQueryKey>

export function portfolioControllerGetHistoryQueryOptions(wallet: PortfolioControllerGetHistoryPathParams["wallet"], params?: PortfolioControllerGetHistoryQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = portfolioControllerGetHistoryQueryKey(wallet, params)
        return queryOptions<PortfolioControllerGetHistoryQueryResponse, ResponseErrorConfig<Error>, PortfolioControllerGetHistoryQueryResponse, typeof queryKey>({
         enabled: !!(wallet),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return portfolioControllerGetHistory(wallet, params, config)
         },
        })

}

/**
 * @summary Get transaction history for a wallet address
 * {@link /api/portfolio/:wallet/history}
 */
export function usePortfolioControllerGetHistory<TData = PortfolioControllerGetHistoryQueryResponse, TQueryData = PortfolioControllerGetHistoryQueryResponse, TQueryKey extends QueryKey = PortfolioControllerGetHistoryQueryKey>(wallet: PortfolioControllerGetHistoryPathParams["wallet"], params?: PortfolioControllerGetHistoryQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<PortfolioControllerGetHistoryQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? portfolioControllerGetHistoryQueryKey(wallet, params)
         

         const query = useQuery({
          ...portfolioControllerGetHistoryQueryOptions(wallet, params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}