/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { BlogControllerFindFeaturedQueryResponse } from "@/lib/api-client/types/blog-controller-find-featured";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { blogControllerFindFeatured } from "@/lib/api-client/client/blog-controller-find-featured";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const blogControllerFindFeaturedQueryKey = () => [{ url: '/api/blogs/featured' }] as const

export type BlogControllerFindFeaturedQueryKey = ReturnType<typeof blogControllerFindFeaturedQueryKey>

export function blogControllerFindFeaturedQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = blogControllerFindFeaturedQueryKey()
        return queryOptions<BlogControllerFindFeaturedQueryResponse, ResponseErrorConfig<Error>, BlogControllerFindFeaturedQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return blogControllerFindFeatured(config)
         },
        })

}

/**
 * @summary Get featured blog posts
 * {@link /api/blogs/featured}
 */
export function useBlogControllerFindFeatured<TData = BlogControllerFindFeaturedQueryResponse, TQueryData = BlogControllerFindFeaturedQueryResponse, TQueryKey extends QueryKey = BlogControllerFindFeaturedQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<BlogControllerFindFeaturedQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? blogControllerFindFeaturedQueryKey()
         

         const query = useQuery({
          ...blogControllerFindFeaturedQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}