/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ArticleControllerFindAllQueryResponse, ArticleControllerFindAllQueryParams } from "@/lib/api-client/types/article-controller-find-all";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { articleControllerFindAll } from "@/lib/api-client/client/article-controller-find-all";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const articleControllerFindAllSuspenseQueryKey = (params: ArticleControllerFindAllQueryParams = {}) => [{ url: '/api/articles' }, ...(params ? [params] : [])] as const

export type ArticleControllerFindAllSuspenseQueryKey = ReturnType<typeof articleControllerFindAllSuspenseQueryKey>

export function articleControllerFindAllSuspenseQueryOptions(params?: ArticleControllerFindAllQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = articleControllerFindAllSuspenseQueryKey(params)
        return queryOptions<ArticleControllerFindAllQueryResponse, ResponseErrorConfig<Error>, ArticleControllerFindAllQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return articleControllerFindAll(params, config)
         },
        })

}

/**
 * @summary List articles (paginated)
 * {@link /api/articles}
 */
export function useArticleControllerFindAllSuspense<TData = ArticleControllerFindAllQueryResponse, TQueryKey extends QueryKey = ArticleControllerFindAllSuspenseQueryKey>(params?: ArticleControllerFindAllQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ArticleControllerFindAllQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? articleControllerFindAllSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...articleControllerFindAllSuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}