/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { NotificationControllerMarkAsReadMutationResponse, NotificationControllerMarkAsReadPathParams } from "@/lib/api-client/types/notification-controller-mark-as-read";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { notificationControllerMarkAsRead } from "@/lib/api-client/client/notification-controller-mark-as-read";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const notificationControllerMarkAsReadMutationKey = () => [{ url: '/api/notifications/:id/read' }] as const

export type NotificationControllerMarkAsReadMutationKey = ReturnType<typeof notificationControllerMarkAsReadMutationKey>

export function notificationControllerMarkAsReadMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = notificationControllerMarkAsReadMutationKey()
        return mutationOptions<NotificationControllerMarkAsReadMutationResponse, ResponseErrorConfig<Error>, {id: NotificationControllerMarkAsReadPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return notificationControllerMarkAsRead(id, config)
          },
        })

}

/**
 * @summary Mark a single notification as read
 * {@link /api/notifications/:id/read}
 */
export function useNotificationControllerMarkAsRead<TContext>(options: 
{
  mutation?: UseMutationOptions<NotificationControllerMarkAsReadMutationResponse, ResponseErrorConfig<Error>, {id: NotificationControllerMarkAsReadPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? notificationControllerMarkAsReadMutationKey()

          const baseOptions = notificationControllerMarkAsReadMutationOptions(config) as UseMutationOptions<NotificationControllerMarkAsReadMutationResponse, ResponseErrorConfig<Error>, {id: NotificationControllerMarkAsReadPathParams["id"]}, TContext>
          

          return useMutation<NotificationControllerMarkAsReadMutationResponse, ResponseErrorConfig<Error>, {id: NotificationControllerMarkAsReadPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<NotificationControllerMarkAsReadMutationResponse, ResponseErrorConfig<Error>, {id: NotificationControllerMarkAsReadPathParams["id"]}, TContext>
      
}