/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { X402ControllerHealthQueryResponse } from "@/lib/api-client/types/x402-controller-health";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { x402ControllerHealth } from "@/lib/api-client/client/x402-controller-health";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const x402ControllerHealthQueryKey = () => [{ url: '/api/health' }] as const

export type X402ControllerHealthQueryKey = ReturnType<typeof x402ControllerHealthQueryKey>

export function x402ControllerHealthQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = x402ControllerHealthQueryKey()
        return queryOptions<X402ControllerHealthQueryResponse, ResponseErrorConfig<Error>, X402ControllerHealthQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return x402ControllerHealth(config)
         },
        })

}

/**
 * @description Returns server health status, uptime, network, and active market count. No payment required.
 * @summary Health check (free)
 * {@link /api/health}
 */
export function useX402ControllerHealth<TData = X402ControllerHealthQueryResponse, TQueryData = X402ControllerHealthQueryResponse, TQueryKey extends QueryKey = X402ControllerHealthQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<X402ControllerHealthQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? x402ControllerHealthQueryKey()
         

         const query = useQuery({
          ...x402ControllerHealthQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}