/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UploadControllerUploadImagesMutationResponse } from "@/lib/api-client/types/upload-controller-upload-images";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { uploadControllerUploadImages } from "@/lib/api-client/client/upload-controller-upload-images";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const uploadControllerUploadImagesMutationKey = () => [{ url: '/api/r2/upload' }] as const

export type UploadControllerUploadImagesMutationKey = ReturnType<typeof uploadControllerUploadImagesMutationKey>

export function uploadControllerUploadImagesMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = uploadControllerUploadImagesMutationKey()
        return mutationOptions<UploadControllerUploadImagesMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return uploadControllerUploadImages(config)
          },
        })

}

/**
 * @description Upload up to 5 images and receive their public URLs. Use these URLs when creating comments.
 * @summary Upload images to R2 and get URLs
 * {@link /api/r2/upload}
 */
export function useUploadControllerUploadImages<TContext>(options: 
{
  mutation?: UseMutationOptions<UploadControllerUploadImagesMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? uploadControllerUploadImagesMutationKey()

          const baseOptions = uploadControllerUploadImagesMutationOptions(config) as UseMutationOptions<UploadControllerUploadImagesMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<UploadControllerUploadImagesMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UploadControllerUploadImagesMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}