/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { X402ControllerGetMarketDetailQueryResponse, X402ControllerGetMarketDetailPathParams, X402ControllerGetMarketDetail404 } from "@/lib/api-client/types/x402-controller-get-market-detail";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { x402ControllerGetMarketDetail } from "@/lib/api-client/client/x402-controller-get-market-detail";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const x402ControllerGetMarketDetailQueryKey = (id: X402ControllerGetMarketDetailPathParams["id"]) => [{ url: '/api/v1/markets/:id', params: {id:id} }] as const

export type X402ControllerGetMarketDetailQueryKey = ReturnType<typeof x402ControllerGetMarketDetailQueryKey>

export function x402ControllerGetMarketDetailQueryOptions(id: X402ControllerGetMarketDetailPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = x402ControllerGetMarketDetailQueryKey(id)
        return queryOptions<X402ControllerGetMarketDetailQueryResponse, ResponseErrorConfig<X402ControllerGetMarketDetail404>, X402ControllerGetMarketDetailQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return x402ControllerGetMarketDetail(id, config)
         },
        })

}

/**
 * @description Returns full on-chain market data including reserves, oracle config, and prices.
 * @summary Get market detail (free)
 * {@link /api/v1/markets/:id}
 */
export function useX402ControllerGetMarketDetail<TData = X402ControllerGetMarketDetailQueryResponse, TQueryData = X402ControllerGetMarketDetailQueryResponse, TQueryKey extends QueryKey = X402ControllerGetMarketDetailQueryKey>(id: X402ControllerGetMarketDetailPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<X402ControllerGetMarketDetailQueryResponse, ResponseErrorConfig<X402ControllerGetMarketDetail404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? x402ControllerGetMarketDetailQueryKey(id)
         

         const query = useQuery({
          ...x402ControllerGetMarketDetailQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<X402ControllerGetMarketDetail404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}