/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { KalshiControllerGetEventsQueryResponse, KalshiControllerGetEventsQueryParams } from "@/lib/api-client/types/kalshi-controller-get-events";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { kalshiControllerGetEvents } from "@/lib/api-client/client/kalshi-controller-get-events";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const kalshiControllerGetEventsSuspenseQueryKey = (params: KalshiControllerGetEventsQueryParams = {}) => [{ url: '/api/kalshi/events' }, ...(params ? [params] : [])] as const

export type KalshiControllerGetEventsSuspenseQueryKey = ReturnType<typeof kalshiControllerGetEventsSuspenseQueryKey>

export function kalshiControllerGetEventsSuspenseQueryOptions(params?: KalshiControllerGetEventsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = kalshiControllerGetEventsSuspenseQueryKey(params)
        return queryOptions<KalshiControllerGetEventsQueryResponse, ResponseErrorConfig<Error>, KalshiControllerGetEventsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return kalshiControllerGetEvents(params, config)
         },
        })

}

/**
 * @summary Get trending Kalshi events
 * {@link /api/kalshi/events}
 */
export function useKalshiControllerGetEventsSuspense<TData = KalshiControllerGetEventsQueryResponse, TQueryKey extends QueryKey = KalshiControllerGetEventsSuspenseQueryKey>(params?: KalshiControllerGetEventsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<KalshiControllerGetEventsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? kalshiControllerGetEventsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...kalshiControllerGetEventsSuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}