/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ArticleControllerCreateMutationRequest, ArticleControllerCreateMutationResponse } from "@/lib/api-client/types/article-controller-create";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { articleControllerCreate } from "@/lib/api-client/client/article-controller-create";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const articleControllerCreateMutationKey = () => [{ url: '/api/articles' }] as const

export type ArticleControllerCreateMutationKey = ReturnType<typeof articleControllerCreateMutationKey>

export function articleControllerCreateMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ArticleControllerCreateMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = articleControllerCreateMutationKey()
        return mutationOptions<ArticleControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: ArticleControllerCreateMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return articleControllerCreate(data, config)
          },
        })

}

/**
 * @summary Create a new article (admin only)
 * {@link /api/articles}
 */
export function useArticleControllerCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<ArticleControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: ArticleControllerCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ArticleControllerCreateMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? articleControllerCreateMutationKey()

          const baseOptions = articleControllerCreateMutationOptions(config) as UseMutationOptions<ArticleControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: ArticleControllerCreateMutationRequest}, TContext>
          

          return useMutation<ArticleControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: ArticleControllerCreateMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ArticleControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: ArticleControllerCreateMutationRequest}, TContext>
      
}