/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerStoreNoteMutationRequest, ZkControllerStoreNoteMutationResponse } from "@/lib/api-client/types/zk-controller-store-note";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { zkControllerStoreNote } from "@/lib/api-client/client/zk-controller-store-note";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const zkControllerStoreNoteMutationKey = () => [{ url: '/api/zk/notes' }] as const

export type ZkControllerStoreNoteMutationKey = ReturnType<typeof zkControllerStoreNoteMutationKey>

export function zkControllerStoreNoteMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ZkControllerStoreNoteMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = zkControllerStoreNoteMutationKey()
        return mutationOptions<ZkControllerStoreNoteMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreNoteMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return zkControllerStoreNote(data, config)
          },
        })

}

/**
 * @summary Store an encrypted note
 * {@link /api/zk/notes}
 */
export function useZkControllerStoreNote<TContext>(options: 
{
  mutation?: UseMutationOptions<ZkControllerStoreNoteMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreNoteMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ZkControllerStoreNoteMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? zkControllerStoreNoteMutationKey()

          const baseOptions = zkControllerStoreNoteMutationOptions(config) as UseMutationOptions<ZkControllerStoreNoteMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreNoteMutationRequest}, TContext>
          

          return useMutation<ZkControllerStoreNoteMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreNoteMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ZkControllerStoreNoteMutationResponse, ResponseErrorConfig<Error>, {data: ZkControllerStoreNoteMutationRequest}, TContext>
      
}