/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { NotificationControllerGetNotificationsQueryResponse, NotificationControllerGetNotificationsQueryParams } from "@/lib/api-client/types/notification-controller-get-notifications";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { notificationControllerGetNotifications } from "@/lib/api-client/client/notification-controller-get-notifications";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const notificationControllerGetNotificationsSuspenseQueryKey = (params: NotificationControllerGetNotificationsQueryParams = {}) => [{ url: '/api/notifications' }, ...(params ? [params] : [])] as const

export type NotificationControllerGetNotificationsSuspenseQueryKey = ReturnType<typeof notificationControllerGetNotificationsSuspenseQueryKey>

export function notificationControllerGetNotificationsSuspenseQueryOptions(params?: NotificationControllerGetNotificationsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = notificationControllerGetNotificationsSuspenseQueryKey(params)
        return queryOptions<NotificationControllerGetNotificationsQueryResponse, ResponseErrorConfig<Error>, NotificationControllerGetNotificationsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return notificationControllerGetNotifications(params, config)
         },
        })

}

/**
 * @summary Get paginated in-app notifications
 * {@link /api/notifications}
 */
export function useNotificationControllerGetNotificationsSuspense<TData = NotificationControllerGetNotificationsQueryResponse, TQueryKey extends QueryKey = NotificationControllerGetNotificationsSuspenseQueryKey>(params?: NotificationControllerGetNotificationsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<NotificationControllerGetNotificationsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? notificationControllerGetNotificationsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...notificationControllerGetNotificationsSuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}