/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetBatchSnapshotsQueryResponse, ZkControllerGetBatchSnapshotsPathParams } from "@/lib/api-client/types/zk-controller-get-batch-snapshots";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { zkControllerGetBatchSnapshots } from "@/lib/api-client/client/zk-controller-get-batch-snapshots";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const zkControllerGetBatchSnapshotsQueryKey = (poolAddress: ZkControllerGetBatchSnapshotsPathParams["poolAddress"]) => [{ url: '/api/zk/batch-snapshots/:poolAddress', params: {poolAddress:poolAddress} }] as const

export type ZkControllerGetBatchSnapshotsQueryKey = ReturnType<typeof zkControllerGetBatchSnapshotsQueryKey>

export function zkControllerGetBatchSnapshotsQueryOptions(poolAddress: ZkControllerGetBatchSnapshotsPathParams["poolAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetBatchSnapshotsQueryKey(poolAddress)
        return queryOptions<ZkControllerGetBatchSnapshotsQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetBatchSnapshotsQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetBatchSnapshots(poolAddress, config)
         },
        })

}

/**
 * @summary Get all batch snapshots for a pool
 * {@link /api/zk/batch-snapshots/:poolAddress}
 */
export function useZkControllerGetBatchSnapshots<TData = ZkControllerGetBatchSnapshotsQueryResponse, TQueryData = ZkControllerGetBatchSnapshotsQueryResponse, TQueryKey extends QueryKey = ZkControllerGetBatchSnapshotsQueryKey>(poolAddress: ZkControllerGetBatchSnapshotsPathParams["poolAddress"], options: 
{
  query?: Partial<QueryObserverOptions<ZkControllerGetBatchSnapshotsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetBatchSnapshotsQueryKey(poolAddress)
         

         const query = useQuery({
          ...zkControllerGetBatchSnapshotsQueryOptions(poolAddress, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}