/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ArticleControllerFindAllQueryResponse, ArticleControllerFindAllQueryParams } from "@/lib/api-client/types/article-controller-find-all";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { articleControllerFindAll } from "@/lib/api-client/client/article-controller-find-all";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const articleControllerFindAllQueryKey = (params: ArticleControllerFindAllQueryParams = {}) => [{ url: '/api/articles' }, ...(params ? [params] : [])] as const

export type ArticleControllerFindAllQueryKey = ReturnType<typeof articleControllerFindAllQueryKey>

export function articleControllerFindAllQueryOptions(params?: ArticleControllerFindAllQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = articleControllerFindAllQueryKey(params)
        return queryOptions<ArticleControllerFindAllQueryResponse, ResponseErrorConfig<Error>, ArticleControllerFindAllQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return articleControllerFindAll(params, config)
         },
        })

}

/**
 * @summary List articles (paginated)
 * {@link /api/articles}
 */
export function useArticleControllerFindAll<TData = ArticleControllerFindAllQueryResponse, TQueryData = ArticleControllerFindAllQueryResponse, TQueryKey extends QueryKey = ArticleControllerFindAllQueryKey>(params?: ArticleControllerFindAllQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ArticleControllerFindAllQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? articleControllerFindAllQueryKey(params)
         

         const query = useQuery({
          ...articleControllerFindAllQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}