/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ArticleControllerFindBySlugQueryResponse, ArticleControllerFindBySlugPathParams } from "@/lib/api-client/types/article-controller-find-by-slug";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { articleControllerFindBySlug } from "@/lib/api-client/client/article-controller-find-by-slug";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const articleControllerFindBySlugQueryKey = (slug: ArticleControllerFindBySlugPathParams["slug"]) => [{ url: '/api/articles/:slug', params: {slug:slug} }] as const

export type ArticleControllerFindBySlugQueryKey = ReturnType<typeof articleControllerFindBySlugQueryKey>

export function articleControllerFindBySlugQueryOptions(slug: ArticleControllerFindBySlugPathParams["slug"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = articleControllerFindBySlugQueryKey(slug)
        return queryOptions<ArticleControllerFindBySlugQueryResponse, ResponseErrorConfig<Error>, ArticleControllerFindBySlugQueryResponse, typeof queryKey>({
         enabled: !!(slug),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return articleControllerFindBySlug(slug, config)
         },
        })

}

/**
 * @summary Get an article by slug
 * {@link /api/articles/:slug}
 */
export function useArticleControllerFindBySlug<TData = ArticleControllerFindBySlugQueryResponse, TQueryData = ArticleControllerFindBySlugQueryResponse, TQueryKey extends QueryKey = ArticleControllerFindBySlugQueryKey>(slug: ArticleControllerFindBySlugPathParams["slug"], options: 
{
  query?: Partial<QueryObserverOptions<ArticleControllerFindBySlugQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? articleControllerFindBySlugQueryKey(slug)
         

         const query = useQuery({
          ...articleControllerFindBySlugQueryOptions(slug, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}