/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { BlogControllerFindAllQueryResponse, BlogControllerFindAllQueryParams } from "@/lib/api-client/types/blog-controller-find-all";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { blogControllerFindAll } from "@/lib/api-client/client/blog-controller-find-all";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const blogControllerFindAllSuspenseQueryKey = (params: BlogControllerFindAllQueryParams = {}) => [{ url: '/api/blogs' }, ...(params ? [params] : [])] as const

export type BlogControllerFindAllSuspenseQueryKey = ReturnType<typeof blogControllerFindAllSuspenseQueryKey>

export function blogControllerFindAllSuspenseQueryOptions(params?: BlogControllerFindAllQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = blogControllerFindAllSuspenseQueryKey(params)
        return queryOptions<BlogControllerFindAllQueryResponse, ResponseErrorConfig<Error>, BlogControllerFindAllQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return blogControllerFindAll(params, config)
         },
        })

}

/**
 * @summary List blog posts (paginated)
 * {@link /api/blogs}
 */
export function useBlogControllerFindAllSuspense<TData = BlogControllerFindAllQueryResponse, TQueryKey extends QueryKey = BlogControllerFindAllSuspenseQueryKey>(params?: BlogControllerFindAllQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<BlogControllerFindAllQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? blogControllerFindAllSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...blogControllerFindAllSuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}