/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PolymarketControllerTriggerResolutionCheckMutationResponse } from "@/lib/api-client/types/polymarket-controller-trigger-resolution-check";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { polymarketControllerTriggerResolutionCheck } from "@/lib/api-client/client/polymarket-controller-trigger-resolution-check";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const polymarketControllerTriggerResolutionCheckMutationKey = () => [{ url: '/api/polymarket/resolution-check' }] as const

export type PolymarketControllerTriggerResolutionCheckMutationKey = ReturnType<typeof polymarketControllerTriggerResolutionCheckMutationKey>

export function polymarketControllerTriggerResolutionCheckMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = polymarketControllerTriggerResolutionCheckMutationKey()
        return mutationOptions<PolymarketControllerTriggerResolutionCheckMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return polymarketControllerTriggerResolutionCheck(config)
          },
        })

}

/**
 * @summary Trigger manual Polymarket resolution check
 * {@link /api/polymarket/resolution-check}
 */
export function usePolymarketControllerTriggerResolutionCheck<TContext>(options: 
{
  mutation?: UseMutationOptions<PolymarketControllerTriggerResolutionCheckMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? polymarketControllerTriggerResolutionCheckMutationKey()

          const baseOptions = polymarketControllerTriggerResolutionCheckMutationOptions(config) as UseMutationOptions<PolymarketControllerTriggerResolutionCheckMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<PolymarketControllerTriggerResolutionCheckMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PolymarketControllerTriggerResolutionCheckMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}