/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { BlogControllerFindAllQueryResponse, BlogControllerFindAllQueryParams } from "@/lib/api-client/types/blog-controller-find-all";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { blogControllerFindAll } from "@/lib/api-client/client/blog-controller-find-all";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const blogControllerFindAllQueryKey = (params: BlogControllerFindAllQueryParams = {}) => [{ url: '/api/blogs' }, ...(params ? [params] : [])] as const

export type BlogControllerFindAllQueryKey = ReturnType<typeof blogControllerFindAllQueryKey>

export function blogControllerFindAllQueryOptions(params?: BlogControllerFindAllQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = blogControllerFindAllQueryKey(params)
        return queryOptions<BlogControllerFindAllQueryResponse, ResponseErrorConfig<Error>, BlogControllerFindAllQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return blogControllerFindAll(params, config)
         },
        })

}

/**
 * @summary List blog posts (paginated)
 * {@link /api/blogs}
 */
export function useBlogControllerFindAll<TData = BlogControllerFindAllQueryResponse, TQueryData = BlogControllerFindAllQueryResponse, TQueryKey extends QueryKey = BlogControllerFindAllQueryKey>(params?: BlogControllerFindAllQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<BlogControllerFindAllQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? blogControllerFindAllQueryKey(params)
         

         const query = useQuery({
          ...blogControllerFindAllQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}