/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminControllerListAdminsQueryResponse, AdminControllerListAdmins403 } from "@/lib/api-client/types/admin-controller-list-admins";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { adminControllerListAdmins } from "@/lib/api-client/client/admin-controller-list-admins";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const adminControllerListAdminsSuspenseQueryKey = () => [{ url: '/api/admin/list' }] as const

export type AdminControllerListAdminsSuspenseQueryKey = ReturnType<typeof adminControllerListAdminsSuspenseQueryKey>

export function adminControllerListAdminsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerListAdminsSuspenseQueryKey()
        return queryOptions<AdminControllerListAdminsQueryResponse, ResponseErrorConfig<AdminControllerListAdmins403>, AdminControllerListAdminsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return adminControllerListAdmins(config)
         },
        })

}

/**
 * @summary Get all admins (requires admin)
 * {@link /api/admin/list}
 */
export function useAdminControllerListAdminsSuspense<TData = AdminControllerListAdminsQueryResponse, TQueryKey extends QueryKey = AdminControllerListAdminsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AdminControllerListAdminsQueryResponse, ResponseErrorConfig<AdminControllerListAdmins403>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? adminControllerListAdminsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...adminControllerListAdminsSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<AdminControllerListAdmins403>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}