/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { BlogControllerCreateMutationRequest, BlogControllerCreateMutationResponse } from "@/lib/api-client/types/blog-controller-create";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { blogControllerCreate } from "@/lib/api-client/client/blog-controller-create";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const blogControllerCreateMutationKey = () => [{ url: '/api/blogs' }] as const

export type BlogControllerCreateMutationKey = ReturnType<typeof blogControllerCreateMutationKey>

export function blogControllerCreateMutationOptions<TContext = unknown>(config: Partial<RequestConfig<BlogControllerCreateMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = blogControllerCreateMutationKey()
        return mutationOptions<BlogControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: BlogControllerCreateMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return blogControllerCreate(data, config)
          },
        })

}

/**
 * @summary Create a new blog post (admin only)
 * {@link /api/blogs}
 */
export function useBlogControllerCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<BlogControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: BlogControllerCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<BlogControllerCreateMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? blogControllerCreateMutationKey()

          const baseOptions = blogControllerCreateMutationOptions(config) as UseMutationOptions<BlogControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: BlogControllerCreateMutationRequest}, TContext>
          

          return useMutation<BlogControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: BlogControllerCreateMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<BlogControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: BlogControllerCreateMutationRequest}, TContext>
      
}