/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UserControllerGetCurrentUserQueryResponse, UserControllerGetCurrentUser401 } from "@/lib/api-client/types/user-controller-get-current-user";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { userControllerGetCurrentUser } from "@/lib/api-client/client/user-controller-get-current-user";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const userControllerGetCurrentUserQueryKey = () => [{ url: '/api/users/me' }] as const

export type UserControllerGetCurrentUserQueryKey = ReturnType<typeof userControllerGetCurrentUserQueryKey>

export function userControllerGetCurrentUserQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = userControllerGetCurrentUserQueryKey()
        return queryOptions<UserControllerGetCurrentUserQueryResponse, ResponseErrorConfig<UserControllerGetCurrentUser401>, UserControllerGetCurrentUserQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return userControllerGetCurrentUser(config)
         },
        })

}

/**
 * @summary Get current user profile
 * {@link /api/users/me}
 */
export function useUserControllerGetCurrentUser<TData = UserControllerGetCurrentUserQueryResponse, TQueryData = UserControllerGetCurrentUserQueryResponse, TQueryKey extends QueryKey = UserControllerGetCurrentUserQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<UserControllerGetCurrentUserQueryResponse, ResponseErrorConfig<UserControllerGetCurrentUser401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? userControllerGetCurrentUserQueryKey()
         

         const query = useQuery({
          ...userControllerGetCurrentUserQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<UserControllerGetCurrentUser401>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}