/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { NotificationControllerVerifyEmailQueryResponse, NotificationControllerVerifyEmailQueryParams } from "@/lib/api-client/types/notification-controller-verify-email";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { notificationControllerVerifyEmail } from "@/lib/api-client/client/notification-controller-verify-email";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const notificationControllerVerifyEmailSuspenseQueryKey = (params: NotificationControllerVerifyEmailQueryParams) => [{ url: '/api/notifications/email/verify' }, ...(params ? [params] : [])] as const

export type NotificationControllerVerifyEmailSuspenseQueryKey = ReturnType<typeof notificationControllerVerifyEmailSuspenseQueryKey>

export function notificationControllerVerifyEmailSuspenseQueryOptions(params: NotificationControllerVerifyEmailQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = notificationControllerVerifyEmailSuspenseQueryKey(params)
        return queryOptions<NotificationControllerVerifyEmailQueryResponse, ResponseErrorConfig<Error>, NotificationControllerVerifyEmailQueryResponse, typeof queryKey>({
         enabled: !!(params),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return notificationControllerVerifyEmail(params, config)
         },
        })

}

/**
 * @summary Verify email via signed token
 * {@link /api/notifications/email/verify}
 */
export function useNotificationControllerVerifyEmailSuspense<TData = NotificationControllerVerifyEmailQueryResponse, TQueryKey extends QueryKey = NotificationControllerVerifyEmailSuspenseQueryKey>(params: NotificationControllerVerifyEmailQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<NotificationControllerVerifyEmailQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? notificationControllerVerifyEmailSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...notificationControllerVerifyEmailSuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}