/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { MarketControllerFindAllQueryResponse, MarketControllerFindAllQueryParams } from "@/lib/api-client/types/market-controller-find-all";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { marketControllerFindAll } from "@/lib/api-client/client/market-controller-find-all";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const marketControllerFindAllQueryKey = (params: MarketControllerFindAllQueryParams = {}) => [{ url: '/api/markets' }, ...(params ? [params] : [])] as const

export type MarketControllerFindAllQueryKey = ReturnType<typeof marketControllerFindAllQueryKey>

export function marketControllerFindAllQueryOptions(params?: MarketControllerFindAllQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketControllerFindAllQueryKey(params)
        return queryOptions<MarketControllerFindAllQueryResponse, ResponseErrorConfig<Error>, MarketControllerFindAllQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return marketControllerFindAll(params, config)
         },
        })

}

/**
 * @summary Get markets with pagination, search, and sort
 * {@link /api/markets}
 */
export function useMarketControllerFindAll<TData = MarketControllerFindAllQueryResponse, TQueryData = MarketControllerFindAllQueryResponse, TQueryKey extends QueryKey = MarketControllerFindAllQueryKey>(params?: MarketControllerFindAllQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<MarketControllerFindAllQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? marketControllerFindAllQueryKey(params)
         

         const query = useQuery({
          ...marketControllerFindAllQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}