/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PolymarketControllerGetEventsQueryResponse, PolymarketControllerGetEventsQueryParams } from "@/lib/api-client/types/polymarket-controller-get-events";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { polymarketControllerGetEvents } from "@/lib/api-client/client/polymarket-controller-get-events";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const polymarketControllerGetEventsQueryKey = (params: PolymarketControllerGetEventsQueryParams = {}) => [{ url: '/api/polymarket/events' }, ...(params ? [params] : [])] as const

export type PolymarketControllerGetEventsQueryKey = ReturnType<typeof polymarketControllerGetEventsQueryKey>

export function polymarketControllerGetEventsQueryOptions(params?: PolymarketControllerGetEventsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = polymarketControllerGetEventsQueryKey(params)
        return queryOptions<PolymarketControllerGetEventsQueryResponse, ResponseErrorConfig<Error>, PolymarketControllerGetEventsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return polymarketControllerGetEvents(params, config)
         },
        })

}

/**
 * @summary Get trending Polymarket events
 * {@link /api/polymarket/events}
 */
export function usePolymarketControllerGetEvents<TData = PolymarketControllerGetEventsQueryResponse, TQueryData = PolymarketControllerGetEventsQueryResponse, TQueryKey extends QueryKey = PolymarketControllerGetEventsQueryKey>(params?: PolymarketControllerGetEventsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<PolymarketControllerGetEventsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? polymarketControllerGetEventsQueryKey(params)
         

         const query = useQuery({
          ...polymarketControllerGetEventsQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}