/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GraduationControllerGetMarketsQueryResponse, GraduationControllerGetMarketsQueryParams } from "@/lib/api-client/types/graduation-controller-get-markets";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { graduationControllerGetMarkets } from "@/lib/api-client/client/graduation-controller-get-markets";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const graduationControllerGetMarketsSuspenseQueryKey = (params: GraduationControllerGetMarketsQueryParams = {}) => [{ url: '/api/graduation/markets' }, ...(params ? [params] : [])] as const

export type GraduationControllerGetMarketsSuspenseQueryKey = ReturnType<typeof graduationControllerGetMarketsSuspenseQueryKey>

export function graduationControllerGetMarketsSuspenseQueryOptions(params?: GraduationControllerGetMarketsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = graduationControllerGetMarketsSuspenseQueryKey(params)
        return queryOptions<GraduationControllerGetMarketsQueryResponse, ResponseErrorConfig<Error>, GraduationControllerGetMarketsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return graduationControllerGetMarkets(params, config)
         },
        })

}

/**
 * @summary Get graduation prediction markets
 * {@link /api/graduation/markets}
 */
export function useGraduationControllerGetMarketsSuspense<TData = GraduationControllerGetMarketsQueryResponse, TQueryKey extends QueryKey = GraduationControllerGetMarketsSuspenseQueryKey>(params?: GraduationControllerGetMarketsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GraduationControllerGetMarketsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? graduationControllerGetMarketsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...graduationControllerGetMarketsSuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}