/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TokenDataControllerGetOverviewQueryResponse, TokenDataControllerGetOverviewPathParams } from "@/lib/api-client/types/token-data-controller-get-overview";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { tokenDataControllerGetOverview } from "@/lib/api-client/client/token-data-controller-get-overview";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const tokenDataControllerGetOverviewQueryKey = (mint: TokenDataControllerGetOverviewPathParams["mint"]) => [{ url: '/api/token-data/:mint/overview', params: {mint:mint} }] as const

export type TokenDataControllerGetOverviewQueryKey = ReturnType<typeof tokenDataControllerGetOverviewQueryKey>

export function tokenDataControllerGetOverviewQueryOptions(mint: TokenDataControllerGetOverviewPathParams["mint"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = tokenDataControllerGetOverviewQueryKey(mint)
        return queryOptions<TokenDataControllerGetOverviewQueryResponse, ResponseErrorConfig<Error>, TokenDataControllerGetOverviewQueryResponse, typeof queryKey>({
         enabled: !!(mint),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return tokenDataControllerGetOverview(mint, config)
         },
        })

}

/**
 * @summary Get token overview data
 * {@link /api/token-data/:mint/overview}
 */
export function useTokenDataControllerGetOverview<TData = TokenDataControllerGetOverviewQueryResponse, TQueryData = TokenDataControllerGetOverviewQueryResponse, TQueryKey extends QueryKey = TokenDataControllerGetOverviewQueryKey>(mint: TokenDataControllerGetOverviewPathParams["mint"], options: 
{
  query?: Partial<QueryObserverOptions<TokenDataControllerGetOverviewQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? tokenDataControllerGetOverviewQueryKey(mint)
         

         const query = useQuery({
          ...tokenDataControllerGetOverviewQueryOptions(mint, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}