/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GraduationControllerGetTokenDetailQueryResponse, GraduationControllerGetTokenDetailPathParams, GraduationControllerGetTokenDetail404 } from "@/lib/api-client/types/graduation-controller-get-token-detail";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { graduationControllerGetTokenDetail } from "@/lib/api-client/client/graduation-controller-get-token-detail";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const graduationControllerGetTokenDetailQueryKey = (mint: GraduationControllerGetTokenDetailPathParams["mint"]) => [{ url: '/api/graduation/token/:mint', params: {mint:mint} }] as const

export type GraduationControllerGetTokenDetailQueryKey = ReturnType<typeof graduationControllerGetTokenDetailQueryKey>

export function graduationControllerGetTokenDetailQueryOptions(mint: GraduationControllerGetTokenDetailPathParams["mint"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = graduationControllerGetTokenDetailQueryKey(mint)
        return queryOptions<GraduationControllerGetTokenDetailQueryResponse, ResponseErrorConfig<GraduationControllerGetTokenDetail404>, GraduationControllerGetTokenDetailQueryResponse, typeof queryKey>({
         enabled: !!(mint),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return graduationControllerGetTokenDetail(mint, config)
         },
        })

}

/**
 * @summary Get detailed data for a pump.fun token
 * {@link /api/graduation/token/:mint}
 */
export function useGraduationControllerGetTokenDetail<TData = GraduationControllerGetTokenDetailQueryResponse, TQueryData = GraduationControllerGetTokenDetailQueryResponse, TQueryKey extends QueryKey = GraduationControllerGetTokenDetailQueryKey>(mint: GraduationControllerGetTokenDetailPathParams["mint"], options: 
{
  query?: Partial<QueryObserverOptions<GraduationControllerGetTokenDetailQueryResponse, ResponseErrorConfig<GraduationControllerGetTokenDetail404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? graduationControllerGetTokenDetailQueryKey(mint)
         

         const query = useQuery({
          ...graduationControllerGetTokenDetailQueryOptions(mint, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GraduationControllerGetTokenDetail404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}