/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PolymarketControllerForceResolveMutationResponse, PolymarketControllerForceResolvePathParams } from "@/lib/api-client/types/polymarket-controller-force-resolve";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { polymarketControllerForceResolve } from "@/lib/api-client/client/polymarket-controller-force-resolve";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const polymarketControllerForceResolveMutationKey = () => [{ url: '/api/polymarket/force-resolve/:marketId' }] as const

export type PolymarketControllerForceResolveMutationKey = ReturnType<typeof polymarketControllerForceResolveMutationKey>

export function polymarketControllerForceResolveMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = polymarketControllerForceResolveMutationKey()
        return mutationOptions<PolymarketControllerForceResolveMutationResponse, ResponseErrorConfig<Error>, {marketId: PolymarketControllerForceResolvePathParams["marketId"]}, TContext>({
          mutationKey,
          mutationFn: async({ marketId }) => {
            return polymarketControllerForceResolve(marketId, config)
          },
        })

}

/**
 * @summary Force-resolve a specific market
 * {@link /api/polymarket/force-resolve/:marketId}
 */
export function usePolymarketControllerForceResolve<TContext>(options: 
{
  mutation?: UseMutationOptions<PolymarketControllerForceResolveMutationResponse, ResponseErrorConfig<Error>, {marketId: PolymarketControllerForceResolvePathParams["marketId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? polymarketControllerForceResolveMutationKey()

          const baseOptions = polymarketControllerForceResolveMutationOptions(config) as UseMutationOptions<PolymarketControllerForceResolveMutationResponse, ResponseErrorConfig<Error>, {marketId: PolymarketControllerForceResolvePathParams["marketId"]}, TContext>
          

          return useMutation<PolymarketControllerForceResolveMutationResponse, ResponseErrorConfig<Error>, {marketId: PolymarketControllerForceResolvePathParams["marketId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PolymarketControllerForceResolveMutationResponse, ResponseErrorConfig<Error>, {marketId: PolymarketControllerForceResolvePathParams["marketId"]}, TContext>
      
}