/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { X402ControllerGetX402InfoQueryResponse } from "@/lib/api-client/types/x402-controller-get-x402-info";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { x402ControllerGetX402Info } from "@/lib/api-client/client/x402-controller-get-x402-info";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const x402ControllerGetX402InfoSuspenseQueryKey = () => [{ url: '/api/x402-info' }] as const

export type X402ControllerGetX402InfoSuspenseQueryKey = ReturnType<typeof x402ControllerGetX402InfoSuspenseQueryKey>

export function x402ControllerGetX402InfoSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = x402ControllerGetX402InfoSuspenseQueryKey()
        return queryOptions<X402ControllerGetX402InfoQueryResponse, ResponseErrorConfig<Error>, X402ControllerGetX402InfoQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return x402ControllerGetX402Info(config)
         },
        })

}

/**
 * @description Lists all available paid endpoints with their prices. No payment required. Use this to discover the API.
 * @summary x402 endpoint information (free)
 * {@link /api/x402-info}
 */
export function useX402ControllerGetX402InfoSuspense<TData = X402ControllerGetX402InfoQueryResponse, TQueryKey extends QueryKey = X402ControllerGetX402InfoSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<X402ControllerGetX402InfoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? x402ControllerGetX402InfoSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...x402ControllerGetX402InfoSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}