/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CloudinaryUploadControllerUploadMutationResponse } from "@/lib/api-client/types/cloudinary-upload-controller-upload";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { cloudinaryUploadControllerUpload } from "@/lib/api-client/client/cloudinary-upload-controller-upload";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const cloudinaryUploadControllerUploadMutationKey = () => [{ url: '/api/cloudinary/upload' }] as const

export type CloudinaryUploadControllerUploadMutationKey = ReturnType<typeof cloudinaryUploadControllerUploadMutationKey>

export function cloudinaryUploadControllerUploadMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = cloudinaryUploadControllerUploadMutationKey()
        return mutationOptions<CloudinaryUploadControllerUploadMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return cloudinaryUploadControllerUpload(config)
          },
        })

}

/**
 * @summary Upload an image to Cloudinary (admin, signed)
 * {@link /api/cloudinary/upload}
 */
export function useCloudinaryUploadControllerUpload<TContext>(options: 
{
  mutation?: UseMutationOptions<CloudinaryUploadControllerUploadMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? cloudinaryUploadControllerUploadMutationKey()

          const baseOptions = cloudinaryUploadControllerUploadMutationOptions(config) as UseMutationOptions<CloudinaryUploadControllerUploadMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<CloudinaryUploadControllerUploadMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CloudinaryUploadControllerUploadMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}