/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetCommitmentsByBatchQueryResponse, ZkControllerGetCommitmentsByBatchPathParams } from "@/lib/api-client/types/zk-controller-get-commitments-by-batch";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { zkControllerGetCommitmentsByBatch } from "@/lib/api-client/client/zk-controller-get-commitments-by-batch";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const zkControllerGetCommitmentsByBatchSuspenseQueryKey = (poolAddress: ZkControllerGetCommitmentsByBatchPathParams["poolAddress"], batchNumber: ZkControllerGetCommitmentsByBatchPathParams["batchNumber"]) => [{ url: '/api/zk/commitments/:poolAddress/batch/:batchNumber', params: {poolAddress:poolAddress,batchNumber:batchNumber} }] as const

export type ZkControllerGetCommitmentsByBatchSuspenseQueryKey = ReturnType<typeof zkControllerGetCommitmentsByBatchSuspenseQueryKey>

export function zkControllerGetCommitmentsByBatchSuspenseQueryOptions(poolAddress: ZkControllerGetCommitmentsByBatchPathParams["poolAddress"], batchNumber: ZkControllerGetCommitmentsByBatchPathParams["batchNumber"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetCommitmentsByBatchSuspenseQueryKey(poolAddress, batchNumber)
        return queryOptions<ZkControllerGetCommitmentsByBatchQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetCommitmentsByBatchQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress&& batchNumber),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetCommitmentsByBatch(poolAddress, batchNumber, config)
         },
        })

}

/**
 * @summary Get commitments for a specific batch
 * {@link /api/zk/commitments/:poolAddress/batch/:batchNumber}
 */
export function useZkControllerGetCommitmentsByBatchSuspense<TData = ZkControllerGetCommitmentsByBatchQueryResponse, TQueryKey extends QueryKey = ZkControllerGetCommitmentsByBatchSuspenseQueryKey>(poolAddress: ZkControllerGetCommitmentsByBatchPathParams["poolAddress"], batchNumber: ZkControllerGetCommitmentsByBatchPathParams["batchNumber"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ZkControllerGetCommitmentsByBatchQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetCommitmentsByBatchSuspenseQueryKey(poolAddress, batchNumber)
         

         const query = useSuspenseQuery({
          ...zkControllerGetCommitmentsByBatchSuspenseQueryOptions(poolAddress, batchNumber, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}