/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PortfolioControllerGetCostBasisQueryResponse, PortfolioControllerGetCostBasisPathParams } from "@/lib/api-client/types/portfolio-controller-get-cost-basis";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { portfolioControllerGetCostBasis } from "@/lib/api-client/client/portfolio-controller-get-cost-basis";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const portfolioControllerGetCostBasisQueryKey = (wallet: PortfolioControllerGetCostBasisPathParams["wallet"]) => [{ url: '/api/portfolio/:wallet/cost-basis', params: {wallet:wallet} }] as const

export type PortfolioControllerGetCostBasisQueryKey = ReturnType<typeof portfolioControllerGetCostBasisQueryKey>

export function portfolioControllerGetCostBasisQueryOptions(wallet: PortfolioControllerGetCostBasisPathParams["wallet"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = portfolioControllerGetCostBasisQueryKey(wallet)
        return queryOptions<PortfolioControllerGetCostBasisQueryResponse, ResponseErrorConfig<Error>, PortfolioControllerGetCostBasisQueryResponse, typeof queryKey>({
         enabled: !!(wallet),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return portfolioControllerGetCostBasis(wallet, config)
         },
        })

}

/**
 * @summary Get cost basis (total SOL spent on BUY trades) per market for a wallet
 * {@link /api/portfolio/:wallet/cost-basis}
 */
export function usePortfolioControllerGetCostBasis<TData = PortfolioControllerGetCostBasisQueryResponse, TQueryData = PortfolioControllerGetCostBasisQueryResponse, TQueryKey extends QueryKey = PortfolioControllerGetCostBasisQueryKey>(wallet: PortfolioControllerGetCostBasisPathParams["wallet"], options: 
{
  query?: Partial<QueryObserverOptions<PortfolioControllerGetCostBasisQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? portfolioControllerGetCostBasisQueryKey(wallet)
         

         const query = useQuery({
          ...portfolioControllerGetCostBasisQueryOptions(wallet, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}