/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminControllerCheckAdminQueryResponse, AdminControllerCheckAdminPathParams } from "@/lib/api-client/types/admin-controller-check-admin";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { adminControllerCheckAdmin } from "@/lib/api-client/client/admin-controller-check-admin";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const adminControllerCheckAdminQueryKey = (walletAddress: AdminControllerCheckAdminPathParams["walletAddress"]) => [{ url: '/api/admin/check/:walletAddress', params: {walletAddress:walletAddress} }] as const

export type AdminControllerCheckAdminQueryKey = ReturnType<typeof adminControllerCheckAdminQueryKey>

export function adminControllerCheckAdminQueryOptions(walletAddress: AdminControllerCheckAdminPathParams["walletAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = adminControllerCheckAdminQueryKey(walletAddress)
        return queryOptions<AdminControllerCheckAdminQueryResponse, ResponseErrorConfig<Error>, AdminControllerCheckAdminQueryResponse, typeof queryKey>({
         enabled: !!(walletAddress),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return adminControllerCheckAdmin(walletAddress, config)
         },
        })

}

/**
 * @summary Check if a wallet address is an admin
 * {@link /api/admin/check/:walletAddress}
 */
export function useAdminControllerCheckAdmin<TData = AdminControllerCheckAdminQueryResponse, TQueryData = AdminControllerCheckAdminQueryResponse, TQueryKey extends QueryKey = AdminControllerCheckAdminQueryKey>(walletAddress: AdminControllerCheckAdminPathParams["walletAddress"], options: 
{
  query?: Partial<QueryObserverOptions<AdminControllerCheckAdminQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? adminControllerCheckAdminQueryKey(walletAddress)
         

         const query = useQuery({
          ...adminControllerCheckAdminQueryOptions(walletAddress, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}