/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TokenDataControllerGetOhlcvQueryResponse, TokenDataControllerGetOhlcvPathParams, TokenDataControllerGetOhlcvQueryParams } from "@/lib/api-client/types/token-data-controller-get-ohlcv";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { tokenDataControllerGetOhlcv } from "@/lib/api-client/client/token-data-controller-get-ohlcv";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const tokenDataControllerGetOhlcvQueryKey = (mint: TokenDataControllerGetOhlcvPathParams["mint"], params: TokenDataControllerGetOhlcvQueryParams = {}) => [{ url: '/api/token-data/:mint/ohlcv', params: {mint:mint} }, ...(params ? [params] : [])] as const

export type TokenDataControllerGetOhlcvQueryKey = ReturnType<typeof tokenDataControllerGetOhlcvQueryKey>

export function tokenDataControllerGetOhlcvQueryOptions(mint: TokenDataControllerGetOhlcvPathParams["mint"], params?: TokenDataControllerGetOhlcvQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = tokenDataControllerGetOhlcvQueryKey(mint, params)
        return queryOptions<TokenDataControllerGetOhlcvQueryResponse, ResponseErrorConfig<Error>, TokenDataControllerGetOhlcvQueryResponse, typeof queryKey>({
         enabled: !!(mint),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return tokenDataControllerGetOhlcv(mint, params, config)
         },
        })

}

/**
 * @summary Get OHLCV candlestick data
 * {@link /api/token-data/:mint/ohlcv}
 */
export function useTokenDataControllerGetOhlcv<TData = TokenDataControllerGetOhlcvQueryResponse, TQueryData = TokenDataControllerGetOhlcvQueryResponse, TQueryKey extends QueryKey = TokenDataControllerGetOhlcvQueryKey>(mint: TokenDataControllerGetOhlcvPathParams["mint"], params?: TokenDataControllerGetOhlcvQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<TokenDataControllerGetOhlcvQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? tokenDataControllerGetOhlcvQueryKey(mint, params)
         

         const query = useQuery({
          ...tokenDataControllerGetOhlcvQueryOptions(mint, params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}