/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ArticleControllerUpdateMutationRequest, ArticleControllerUpdateMutationResponse, ArticleControllerUpdatePathParams } from "@/lib/api-client/types/article-controller-update";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { articleControllerUpdate } from "@/lib/api-client/client/article-controller-update";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const articleControllerUpdateMutationKey = () => [{ url: '/api/articles/:id' }] as const

export type ArticleControllerUpdateMutationKey = ReturnType<typeof articleControllerUpdateMutationKey>

export function articleControllerUpdateMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ArticleControllerUpdateMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = articleControllerUpdateMutationKey()
        return mutationOptions<ArticleControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ArticleControllerUpdatePathParams["id"], data?: ArticleControllerUpdateMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return articleControllerUpdate(id, data, config)
          },
        })

}

/**
 * @summary Update an article (admin only)
 * {@link /api/articles/:id}
 */
export function useArticleControllerUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<ArticleControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ArticleControllerUpdatePathParams["id"], data?: ArticleControllerUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ArticleControllerUpdateMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? articleControllerUpdateMutationKey()

          const baseOptions = articleControllerUpdateMutationOptions(config) as UseMutationOptions<ArticleControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ArticleControllerUpdatePathParams["id"], data?: ArticleControllerUpdateMutationRequest}, TContext>
          

          return useMutation<ArticleControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ArticleControllerUpdatePathParams["id"], data?: ArticleControllerUpdateMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ArticleControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ArticleControllerUpdatePathParams["id"], data?: ArticleControllerUpdateMutationRequest}, TContext>
      
}