/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ChatControllerGetConversationsQueryResponse, ChatControllerGetConversationsQueryParams } from "@/lib/api-client/types/chat-controller-get-conversations";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { chatControllerGetConversations } from "@/lib/api-client/client/chat-controller-get-conversations";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const chatControllerGetConversationsSuspenseQueryKey = (params: ChatControllerGetConversationsQueryParams) => [{ url: '/api/chat/conversations' }, ...(params ? [params] : [])] as const

export type ChatControllerGetConversationsSuspenseQueryKey = ReturnType<typeof chatControllerGetConversationsSuspenseQueryKey>

export function chatControllerGetConversationsSuspenseQueryOptions(params: ChatControllerGetConversationsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = chatControllerGetConversationsSuspenseQueryKey(params)
        return queryOptions<ChatControllerGetConversationsQueryResponse, ResponseErrorConfig<Error>, ChatControllerGetConversationsQueryResponse, typeof queryKey>({
         enabled: !!(params),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return chatControllerGetConversations(params, config)
         },
        })

}

/**
 * {@link /api/chat/conversations}
 */
export function useChatControllerGetConversationsSuspense<TData = ChatControllerGetConversationsQueryResponse, TQueryKey extends QueryKey = ChatControllerGetConversationsSuspenseQueryKey>(params: ChatControllerGetConversationsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ChatControllerGetConversationsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? chatControllerGetConversationsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...chatControllerGetConversationsSuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}