/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { NewsControllerGetNewsQueryResponse, NewsControllerGetNewsPathParams, NewsControllerGetNewsQueryParams } from "@/lib/api-client/types/news-controller-get-news";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { newsControllerGetNews } from "@/lib/api-client/client/news-controller-get-news";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const newsControllerGetNewsSuspenseQueryKey = (symbol: NewsControllerGetNewsPathParams["symbol"], params: NewsControllerGetNewsQueryParams = {}) => [{ url: '/api/news/:symbol', params: {symbol:symbol} }, ...(params ? [params] : [])] as const

export type NewsControllerGetNewsSuspenseQueryKey = ReturnType<typeof newsControllerGetNewsSuspenseQueryKey>

export function newsControllerGetNewsSuspenseQueryOptions(symbol: NewsControllerGetNewsPathParams["symbol"], params?: NewsControllerGetNewsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = newsControllerGetNewsSuspenseQueryKey(symbol, params)
        return queryOptions<NewsControllerGetNewsQueryResponse, ResponseErrorConfig<Error>, NewsControllerGetNewsQueryResponse, typeof queryKey>({
         enabled: !!(symbol),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return newsControllerGetNews(symbol, params, config)
         },
        })

}

/**
 * @summary Get crypto news for a token symbol
 * {@link /api/news/:symbol}
 */
export function useNewsControllerGetNewsSuspense<TData = NewsControllerGetNewsQueryResponse, TQueryKey extends QueryKey = NewsControllerGetNewsSuspenseQueryKey>(symbol: NewsControllerGetNewsPathParams["symbol"], params?: NewsControllerGetNewsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<NewsControllerGetNewsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? newsControllerGetNewsSuspenseQueryKey(symbol, params)
         

         const query = useSuspenseQuery({
          ...newsControllerGetNewsSuspenseQueryOptions(symbol, params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}