/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { MarketControllerGetRecentTradesQueryResponse, MarketControllerGetRecentTradesQueryParams } from "@/lib/api-client/types/market-controller-get-recent-trades";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { marketControllerGetRecentTrades } from "@/lib/api-client/client/market-controller-get-recent-trades";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const marketControllerGetRecentTradesSuspenseQueryKey = (params: MarketControllerGetRecentTradesQueryParams = {}) => [{ url: '/api/markets/recent-trades' }, ...(params ? [params] : [])] as const

export type MarketControllerGetRecentTradesSuspenseQueryKey = ReturnType<typeof marketControllerGetRecentTradesSuspenseQueryKey>

export function marketControllerGetRecentTradesSuspenseQueryOptions(params?: MarketControllerGetRecentTradesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketControllerGetRecentTradesSuspenseQueryKey(params)
        return queryOptions<MarketControllerGetRecentTradesQueryResponse, ResponseErrorConfig<Error>, MarketControllerGetRecentTradesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return marketControllerGetRecentTrades(params, config)
         },
        })

}

/**
 * @summary Get recent trades across all markets
 * {@link /api/markets/recent-trades}
 */
export function useMarketControllerGetRecentTradesSuspense<TData = MarketControllerGetRecentTradesQueryResponse, TQueryKey extends QueryKey = MarketControllerGetRecentTradesSuspenseQueryKey>(params?: MarketControllerGetRecentTradesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<MarketControllerGetRecentTradesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? marketControllerGetRecentTradesSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...marketControllerGetRecentTradesSuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}