/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SnapshotControllerFindByMarketQueryResponse, SnapshotControllerFindByMarketPathParams, SnapshotControllerFindByMarketQueryParams } from "@/lib/api-client/types/snapshot-controller-find-by-market";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { snapshotControllerFindByMarket } from "@/lib/api-client/client/snapshot-controller-find-by-market";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const snapshotControllerFindByMarketSuspenseQueryKey = (marketId: SnapshotControllerFindByMarketPathParams["marketId"], params: SnapshotControllerFindByMarketQueryParams = {}) => [{ url: '/api/snapshots/:marketId', params: {marketId:marketId} }, ...(params ? [params] : [])] as const

export type SnapshotControllerFindByMarketSuspenseQueryKey = ReturnType<typeof snapshotControllerFindByMarketSuspenseQueryKey>

export function snapshotControllerFindByMarketSuspenseQueryOptions(marketId: SnapshotControllerFindByMarketPathParams["marketId"], params?: SnapshotControllerFindByMarketQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = snapshotControllerFindByMarketSuspenseQueryKey(marketId, params)
        return queryOptions<SnapshotControllerFindByMarketQueryResponse, ResponseErrorConfig<Error>, SnapshotControllerFindByMarketQueryResponse, typeof queryKey>({
         enabled: !!(marketId),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return snapshotControllerFindByMarket(marketId, params, config)
         },
        })

}

/**
 * @summary Get probability history for a market
 * {@link /api/snapshots/:marketId}
 */
export function useSnapshotControllerFindByMarketSuspense<TData = SnapshotControllerFindByMarketQueryResponse, TQueryKey extends QueryKey = SnapshotControllerFindByMarketSuspenseQueryKey>(marketId: SnapshotControllerFindByMarketPathParams["marketId"], params?: SnapshotControllerFindByMarketQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<SnapshotControllerFindByMarketQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? snapshotControllerFindByMarketSuspenseQueryKey(marketId, params)
         

         const query = useSuspenseQuery({
          ...snapshotControllerFindByMarketSuspenseQueryOptions(marketId, params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}