/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { BlogControllerRemoveMutationResponse, BlogControllerRemovePathParams } from "@/lib/api-client/types/blog-controller-remove";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { blogControllerRemove } from "@/lib/api-client/client/blog-controller-remove";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const blogControllerRemoveMutationKey = () => [{ url: '/api/blogs/:id' }] as const

export type BlogControllerRemoveMutationKey = ReturnType<typeof blogControllerRemoveMutationKey>

export function blogControllerRemoveMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = blogControllerRemoveMutationKey()
        return mutationOptions<BlogControllerRemoveMutationResponse, ResponseErrorConfig<Error>, {id: BlogControllerRemovePathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return blogControllerRemove(id, config)
          },
        })

}

/**
 * @summary Delete a blog post (admin only)
 * {@link /api/blogs/:id}
 */
export function useBlogControllerRemove<TContext>(options: 
{
  mutation?: UseMutationOptions<BlogControllerRemoveMutationResponse, ResponseErrorConfig<Error>, {id: BlogControllerRemovePathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? blogControllerRemoveMutationKey()

          const baseOptions = blogControllerRemoveMutationOptions(config) as UseMutationOptions<BlogControllerRemoveMutationResponse, ResponseErrorConfig<Error>, {id: BlogControllerRemovePathParams["id"]}, TContext>
          

          return useMutation<BlogControllerRemoveMutationResponse, ResponseErrorConfig<Error>, {id: BlogControllerRemovePathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<BlogControllerRemoveMutationResponse, ResponseErrorConfig<Error>, {id: BlogControllerRemovePathParams["id"]}, TContext>
      
}