/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { KalshiControllerGetEventsQueryResponse, KalshiControllerGetEventsQueryParams } from "@/lib/api-client/types/kalshi-controller-get-events";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { kalshiControllerGetEvents } from "@/lib/api-client/client/kalshi-controller-get-events";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const kalshiControllerGetEventsQueryKey = (params: KalshiControllerGetEventsQueryParams = {}) => [{ url: '/api/kalshi/events' }, ...(params ? [params] : [])] as const

export type KalshiControllerGetEventsQueryKey = ReturnType<typeof kalshiControllerGetEventsQueryKey>

export function kalshiControllerGetEventsQueryOptions(params?: KalshiControllerGetEventsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = kalshiControllerGetEventsQueryKey(params)
        return queryOptions<KalshiControllerGetEventsQueryResponse, ResponseErrorConfig<Error>, KalshiControllerGetEventsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return kalshiControllerGetEvents(params, config)
         },
        })

}

/**
 * @summary Get trending Kalshi events
 * {@link /api/kalshi/events}
 */
export function useKalshiControllerGetEvents<TData = KalshiControllerGetEventsQueryResponse, TQueryData = KalshiControllerGetEventsQueryResponse, TQueryKey extends QueryKey = KalshiControllerGetEventsQueryKey>(params?: KalshiControllerGetEventsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<KalshiControllerGetEventsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? kalshiControllerGetEventsQueryKey(params)
         

         const query = useQuery({
          ...kalshiControllerGetEventsQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}