/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CommentControllerRemoveMutationResponse, CommentControllerRemovePathParams } from "@/lib/api-client/types/comment-controller-remove";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { commentControllerRemove } from "@/lib/api-client/client/comment-controller-remove";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const commentControllerRemoveMutationKey = () => [{ url: '/api/comments/:id' }] as const

export type CommentControllerRemoveMutationKey = ReturnType<typeof commentControllerRemoveMutationKey>

export function commentControllerRemoveMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = commentControllerRemoveMutationKey()
        return mutationOptions<CommentControllerRemoveMutationResponse, ResponseErrorConfig<Error>, {id: CommentControllerRemovePathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return commentControllerRemove(id, config)
          },
        })

}

/**
 * @summary Delete a comment (also deletes images from R2)
 * {@link /api/comments/:id}
 */
export function useCommentControllerRemove<TContext>(options: 
{
  mutation?: UseMutationOptions<CommentControllerRemoveMutationResponse, ResponseErrorConfig<Error>, {id: CommentControllerRemovePathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? commentControllerRemoveMutationKey()

          const baseOptions = commentControllerRemoveMutationOptions(config) as UseMutationOptions<CommentControllerRemoveMutationResponse, ResponseErrorConfig<Error>, {id: CommentControllerRemovePathParams["id"]}, TContext>
          

          return useMutation<CommentControllerRemoveMutationResponse, ResponseErrorConfig<Error>, {id: CommentControllerRemovePathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CommentControllerRemoveMutationResponse, ResponseErrorConfig<Error>, {id: CommentControllerRemovePathParams["id"]}, TContext>
      
}