/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ChatControllerGetConversationsQueryResponse, ChatControllerGetConversationsQueryParams } from "@/lib/api-client/types/chat-controller-get-conversations";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { chatControllerGetConversations } from "@/lib/api-client/client/chat-controller-get-conversations";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const chatControllerGetConversationsQueryKey = (params: ChatControllerGetConversationsQueryParams) => [{ url: '/api/chat/conversations' }, ...(params ? [params] : [])] as const

export type ChatControllerGetConversationsQueryKey = ReturnType<typeof chatControllerGetConversationsQueryKey>

export function chatControllerGetConversationsQueryOptions(params: ChatControllerGetConversationsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = chatControllerGetConversationsQueryKey(params)
        return queryOptions<ChatControllerGetConversationsQueryResponse, ResponseErrorConfig<Error>, ChatControllerGetConversationsQueryResponse, typeof queryKey>({
         enabled: !!(params),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return chatControllerGetConversations(params, config)
         },
        })

}

/**
 * {@link /api/chat/conversations}
 */
export function useChatControllerGetConversations<TData = ChatControllerGetConversationsQueryResponse, TQueryData = ChatControllerGetConversationsQueryResponse, TQueryKey extends QueryKey = ChatControllerGetConversationsQueryKey>(params: ChatControllerGetConversationsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ChatControllerGetConversationsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? chatControllerGetConversationsQueryKey(params)
         

         const query = useQuery({
          ...chatControllerGetConversationsQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}