/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { NotificationControllerGetPreferencesQueryResponse } from "@/lib/api-client/types/notification-controller-get-preferences";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { notificationControllerGetPreferences } from "@/lib/api-client/client/notification-controller-get-preferences";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const notificationControllerGetPreferencesQueryKey = () => [{ url: '/api/notifications/preferences' }] as const

export type NotificationControllerGetPreferencesQueryKey = ReturnType<typeof notificationControllerGetPreferencesQueryKey>

export function notificationControllerGetPreferencesQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = notificationControllerGetPreferencesQueryKey()
        return queryOptions<NotificationControllerGetPreferencesQueryResponse, ResponseErrorConfig<Error>, NotificationControllerGetPreferencesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return notificationControllerGetPreferences(config)
         },
        })

}

/**
 * @summary Get notification preferences
 * {@link /api/notifications/preferences}
 */
export function useNotificationControllerGetPreferences<TData = NotificationControllerGetPreferencesQueryResponse, TQueryData = NotificationControllerGetPreferencesQueryResponse, TQueryKey extends QueryKey = NotificationControllerGetPreferencesQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<NotificationControllerGetPreferencesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? notificationControllerGetPreferencesQueryKey()
         

         const query = useQuery({
          ...notificationControllerGetPreferencesQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}