/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TokenDataControllerGetHoldersQueryResponse, TokenDataControllerGetHoldersPathParams, TokenDataControllerGetHoldersQueryParams } from "@/lib/api-client/types/token-data-controller-get-holders";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { tokenDataControllerGetHolders } from "@/lib/api-client/client/token-data-controller-get-holders";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const tokenDataControllerGetHoldersQueryKey = (mint: TokenDataControllerGetHoldersPathParams["mint"], params: TokenDataControllerGetHoldersQueryParams = {}) => [{ url: '/api/token-data/:mint/holders', params: {mint:mint} }, ...(params ? [params] : [])] as const

export type TokenDataControllerGetHoldersQueryKey = ReturnType<typeof tokenDataControllerGetHoldersQueryKey>

export function tokenDataControllerGetHoldersQueryOptions(mint: TokenDataControllerGetHoldersPathParams["mint"], params?: TokenDataControllerGetHoldersQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = tokenDataControllerGetHoldersQueryKey(mint, params)
        return queryOptions<TokenDataControllerGetHoldersQueryResponse, ResponseErrorConfig<Error>, TokenDataControllerGetHoldersQueryResponse, typeof queryKey>({
         enabled: !!(mint),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return tokenDataControllerGetHolders(mint, params, config)
         },
        })

}

/**
 * @summary Get top token holders
 * {@link /api/token-data/:mint/holders}
 */
export function useTokenDataControllerGetHolders<TData = TokenDataControllerGetHoldersQueryResponse, TQueryData = TokenDataControllerGetHoldersQueryResponse, TQueryKey extends QueryKey = TokenDataControllerGetHoldersQueryKey>(mint: TokenDataControllerGetHoldersPathParams["mint"], params?: TokenDataControllerGetHoldersQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<TokenDataControllerGetHoldersQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? tokenDataControllerGetHoldersQueryKey(mint, params)
         

         const query = useQuery({
          ...tokenDataControllerGetHoldersQueryOptions(mint, params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}