/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GraduationControllerGetTrendingQueryResponse, GraduationControllerGetTrendingQueryParams } from "@/lib/api-client/types/graduation-controller-get-trending";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { graduationControllerGetTrending } from "@/lib/api-client/client/graduation-controller-get-trending";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const graduationControllerGetTrendingSuspenseQueryKey = (params: GraduationControllerGetTrendingQueryParams = {}) => [{ url: '/api/graduation/trending' }, ...(params ? [params] : [])] as const

export type GraduationControllerGetTrendingSuspenseQueryKey = ReturnType<typeof graduationControllerGetTrendingSuspenseQueryKey>

export function graduationControllerGetTrendingSuspenseQueryOptions(params?: GraduationControllerGetTrendingQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = graduationControllerGetTrendingSuspenseQueryKey(params)
        return queryOptions<GraduationControllerGetTrendingQueryResponse, ResponseErrorConfig<Error>, GraduationControllerGetTrendingQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return graduationControllerGetTrending(params, config)
         },
        })

}

/**
 * @summary Get trending pump.fun tokens on bonding curve
 * {@link /api/graduation/trending}
 */
export function useGraduationControllerGetTrendingSuspense<TData = GraduationControllerGetTrendingQueryResponse, TQueryKey extends QueryKey = GraduationControllerGetTrendingSuspenseQueryKey>(params?: GraduationControllerGetTrendingQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GraduationControllerGetTrendingQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? graduationControllerGetTrendingSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...graduationControllerGetTrendingSuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}