/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CommentControllerCreateMutationRequest, CommentControllerCreateMutationResponse } from "@/lib/api-client/types/comment-controller-create";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { commentControllerCreate } from "@/lib/api-client/client/comment-controller-create";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const commentControllerCreateMutationKey = () => [{ url: '/api/comments' }] as const

export type CommentControllerCreateMutationKey = ReturnType<typeof commentControllerCreateMutationKey>

export function commentControllerCreateMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CommentControllerCreateMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = commentControllerCreateMutationKey()
        return mutationOptions<CommentControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: CommentControllerCreateMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return commentControllerCreate(data, config)
          },
        })

}

/**
 * @summary Create a new comment with image URLs
 * {@link /api/comments}
 */
export function useCommentControllerCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<CommentControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: CommentControllerCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommentControllerCreateMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? commentControllerCreateMutationKey()

          const baseOptions = commentControllerCreateMutationOptions(config) as UseMutationOptions<CommentControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: CommentControllerCreateMutationRequest}, TContext>
          

          return useMutation<CommentControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: CommentControllerCreateMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CommentControllerCreateMutationResponse, ResponseErrorConfig<Error>, {data: CommentControllerCreateMutationRequest}, TContext>
      
}