/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthControllerGetNonceMutationRequest, AuthControllerGetNonceMutationResponse } from "@/lib/api-client/types/auth-controller-get-nonce";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { authControllerGetNonce } from "@/lib/api-client/client/auth-controller-get-nonce";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authControllerGetNonceMutationKey = () => [{ url: '/api/auth/nonce' }] as const

export type AuthControllerGetNonceMutationKey = ReturnType<typeof authControllerGetNonceMutationKey>

export function authControllerGetNonceMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AuthControllerGetNonceMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = authControllerGetNonceMutationKey()
        return mutationOptions<AuthControllerGetNonceMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerGetNonceMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return authControllerGetNonce(data, config)
          },
        })

}

/**
 * @description Returns a nonce that must be signed by the wallet
 * @summary Get nonce for wallet authentication
 * {@link /api/auth/nonce}
 */
export function useAuthControllerGetNonce<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthControllerGetNonceMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerGetNonceMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthControllerGetNonceMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? authControllerGetNonceMutationKey()

          const baseOptions = authControllerGetNonceMutationOptions(config) as UseMutationOptions<AuthControllerGetNonceMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerGetNonceMutationRequest}, TContext>
          

          return useMutation<AuthControllerGetNonceMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerGetNonceMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AuthControllerGetNonceMutationResponse, ResponseErrorConfig<Error>, {data: AuthControllerGetNonceMutationRequest}, TContext>
      
}