/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { MarketControllerFindOneQueryResponse, MarketControllerFindOnePathParams } from "@/lib/api-client/types/market-controller-find-one";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { marketControllerFindOne } from "@/lib/api-client/client/market-controller-find-one";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const marketControllerFindOneQueryKey = (id: MarketControllerFindOnePathParams["id"]) => [{ url: '/api/markets/:id', params: {id:id} }] as const

export type MarketControllerFindOneQueryKey = ReturnType<typeof marketControllerFindOneQueryKey>

export function marketControllerFindOneQueryOptions(id: MarketControllerFindOnePathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketControllerFindOneQueryKey(id)
        return queryOptions<MarketControllerFindOneQueryResponse, ResponseErrorConfig<Error>, MarketControllerFindOneQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return marketControllerFindOne(id, config)
         },
        })

}

/**
 * @summary Get a market by ID
 * {@link /api/markets/:id}
 */
export function useMarketControllerFindOne<TData = MarketControllerFindOneQueryResponse, TQueryData = MarketControllerFindOneQueryResponse, TQueryKey extends QueryKey = MarketControllerFindOneQueryKey>(id: MarketControllerFindOnePathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<MarketControllerFindOneQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? marketControllerFindOneQueryKey(id)
         

         const query = useQuery({
          ...marketControllerFindOneQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}