/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerStoreCommitmentsMutationRequest, ZkControllerStoreCommitmentsMutationResponse } from "@/lib/api-client/types/zk-controller-store-commitments";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { zkControllerStoreCommitments } from "@/lib/api-client/client/zk-controller-store-commitments";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const zkControllerStoreCommitmentsMutationKey = () => [{ url: '/api/zk/commitments/batch' }] as const

export type ZkControllerStoreCommitmentsMutationKey = ReturnType<typeof zkControllerStoreCommitmentsMutationKey>

export function zkControllerStoreCommitmentsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<ZkControllerStoreCommitmentsMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = zkControllerStoreCommitmentsMutationKey()
        return mutationOptions<ZkControllerStoreCommitmentsMutationResponse, ResponseErrorConfig<Error>, {data?: ZkControllerStoreCommitmentsMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return zkControllerStoreCommitments(data, config)
          },
        })

}

/**
 * @summary Index multiple commitments at once
 * {@link /api/zk/commitments/batch}
 */
export function useZkControllerStoreCommitments<TContext>(options: 
{
  mutation?: UseMutationOptions<ZkControllerStoreCommitmentsMutationResponse, ResponseErrorConfig<Error>, {data?: ZkControllerStoreCommitmentsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ZkControllerStoreCommitmentsMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? zkControllerStoreCommitmentsMutationKey()

          const baseOptions = zkControllerStoreCommitmentsMutationOptions(config) as UseMutationOptions<ZkControllerStoreCommitmentsMutationResponse, ResponseErrorConfig<Error>, {data?: ZkControllerStoreCommitmentsMutationRequest}, TContext>
          

          return useMutation<ZkControllerStoreCommitmentsMutationResponse, ResponseErrorConfig<Error>, {data?: ZkControllerStoreCommitmentsMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ZkControllerStoreCommitmentsMutationResponse, ResponseErrorConfig<Error>, {data?: ZkControllerStoreCommitmentsMutationRequest}, TContext>
      
}