/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { NotificationControllerGetHistoryQueryResponse, NotificationControllerGetHistoryQueryParams } from "@/lib/api-client/types/notification-controller-get-history";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { notificationControllerGetHistory } from "@/lib/api-client/client/notification-controller-get-history";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const notificationControllerGetHistoryQueryKey = (params: NotificationControllerGetHistoryQueryParams = {}) => [{ url: '/api/notifications/history' }, ...(params ? [params] : [])] as const

export type NotificationControllerGetHistoryQueryKey = ReturnType<typeof notificationControllerGetHistoryQueryKey>

export function notificationControllerGetHistoryQueryOptions(params?: NotificationControllerGetHistoryQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = notificationControllerGetHistoryQueryKey(params)
        return queryOptions<NotificationControllerGetHistoryQueryResponse, ResponseErrorConfig<Error>, NotificationControllerGetHistoryQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return notificationControllerGetHistory(params, config)
         },
        })

}

/**
 * @summary Get paginated notification history
 * {@link /api/notifications/history}
 */
export function useNotificationControllerGetHistory<TData = NotificationControllerGetHistoryQueryResponse, TQueryData = NotificationControllerGetHistoryQueryResponse, TQueryKey extends QueryKey = NotificationControllerGetHistoryQueryKey>(params?: NotificationControllerGetHistoryQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<NotificationControllerGetHistoryQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? notificationControllerGetHistoryQueryKey(params)
         

         const query = useQuery({
          ...notificationControllerGetHistoryQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}