/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PolymarketControllerGetEventBySlugQueryResponse, PolymarketControllerGetEventBySlugPathParams } from "@/lib/api-client/types/polymarket-controller-get-event-by-slug";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { polymarketControllerGetEventBySlug } from "@/lib/api-client/client/polymarket-controller-get-event-by-slug";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const polymarketControllerGetEventBySlugSuspenseQueryKey = (slug: PolymarketControllerGetEventBySlugPathParams["slug"]) => [{ url: '/api/polymarket/events/:slug', params: {slug:slug} }] as const

export type PolymarketControllerGetEventBySlugSuspenseQueryKey = ReturnType<typeof polymarketControllerGetEventBySlugSuspenseQueryKey>

export function polymarketControllerGetEventBySlugSuspenseQueryOptions(slug: PolymarketControllerGetEventBySlugPathParams["slug"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = polymarketControllerGetEventBySlugSuspenseQueryKey(slug)
        return queryOptions<PolymarketControllerGetEventBySlugQueryResponse, ResponseErrorConfig<Error>, PolymarketControllerGetEventBySlugQueryResponse, typeof queryKey>({
         enabled: !!(slug),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return polymarketControllerGetEventBySlug(slug, config)
         },
        })

}

/**
 * @summary Get a single Polymarket event by slug
 * {@link /api/polymarket/events/:slug}
 */
export function usePolymarketControllerGetEventBySlugSuspense<TData = PolymarketControllerGetEventBySlugQueryResponse, TQueryKey extends QueryKey = PolymarketControllerGetEventBySlugSuspenseQueryKey>(slug: PolymarketControllerGetEventBySlugPathParams["slug"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<PolymarketControllerGetEventBySlugQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? polymarketControllerGetEventBySlugSuspenseQueryKey(slug)
         

         const query = useSuspenseQuery({
          ...polymarketControllerGetEventBySlugSuspenseQueryOptions(slug, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}