/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetBatchStatusQueryResponse, ZkControllerGetBatchStatusPathParams } from "@/lib/api-client/types/zk-controller-get-batch-status";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { zkControllerGetBatchStatus } from "@/lib/api-client/client/zk-controller-get-batch-status";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const zkControllerGetBatchStatusSuspenseQueryKey = (poolAddress: ZkControllerGetBatchStatusPathParams["poolAddress"]) => [{ url: '/api/zk/pools/:poolAddress/batch-status', params: {poolAddress:poolAddress} }] as const

export type ZkControllerGetBatchStatusSuspenseQueryKey = ReturnType<typeof zkControllerGetBatchStatusSuspenseQueryKey>

export function zkControllerGetBatchStatusSuspenseQueryOptions(poolAddress: ZkControllerGetBatchStatusPathParams["poolAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetBatchStatusSuspenseQueryKey(poolAddress)
        return queryOptions<ZkControllerGetBatchStatusQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetBatchStatusQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetBatchStatus(poolAddress, config)
         },
        })

}

/**
 * @description Returns the status of all batches including whether snapshots exist and if all commitments are indexed
 * @summary Get batch completeness status for a pool
 * {@link /api/zk/pools/:poolAddress/batch-status}
 */
export function useZkControllerGetBatchStatusSuspense<TData = ZkControllerGetBatchStatusQueryResponse, TQueryKey extends QueryKey = ZkControllerGetBatchStatusSuspenseQueryKey>(poolAddress: ZkControllerGetBatchStatusPathParams["poolAddress"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ZkControllerGetBatchStatusQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetBatchStatusSuspenseQueryKey(poolAddress)
         

         const query = useSuspenseQuery({
          ...zkControllerGetBatchStatusSuspenseQueryOptions(poolAddress, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}