/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthControllerRefreshMutationResponse } from "@/lib/api-client/types/auth-controller-refresh";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { authControllerRefresh } from "@/lib/api-client/client/auth-controller-refresh";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authControllerRefreshMutationKey = () => [{ url: '/api/auth/refresh' }] as const

export type AuthControllerRefreshMutationKey = ReturnType<typeof authControllerRefreshMutationKey>

export function authControllerRefreshMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = authControllerRefreshMutationKey()
        return mutationOptions<AuthControllerRefreshMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return authControllerRefresh(config)
          },
        })

}

/**
 * @description Use refresh token to get new access token
 * @summary Refresh access token
 * {@link /api/auth/refresh}
 */
export function useAuthControllerRefresh<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthControllerRefreshMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? authControllerRefreshMutationKey()

          const baseOptions = authControllerRefreshMutationOptions(config) as UseMutationOptions<AuthControllerRefreshMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<AuthControllerRefreshMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AuthControllerRefreshMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}