/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { X402ControllerGetMarketCommentsQueryResponse, X402ControllerGetMarketCommentsPathParams } from "@/lib/api-client/types/x402-controller-get-market-comments";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { x402ControllerGetMarketComments } from "@/lib/api-client/client/x402-controller-get-market-comments";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const x402ControllerGetMarketCommentsSuspenseQueryKey = (id: X402ControllerGetMarketCommentsPathParams["id"]) => [{ url: '/api/v1/markets/:id/comments', params: {id:id} }] as const

export type X402ControllerGetMarketCommentsSuspenseQueryKey = ReturnType<typeof x402ControllerGetMarketCommentsSuspenseQueryKey>

export function x402ControllerGetMarketCommentsSuspenseQueryOptions(id: X402ControllerGetMarketCommentsPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = x402ControllerGetMarketCommentsSuspenseQueryKey(id)
        return queryOptions<X402ControllerGetMarketCommentsQueryResponse, ResponseErrorConfig<Error>, X402ControllerGetMarketCommentsQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return x402ControllerGetMarketComments(id, config)
         },
        })

}

/**
 * @description Returns community comments and replies for a market.
 * @summary Get market comments (free)
 * {@link /api/v1/markets/:id/comments}
 */
export function useX402ControllerGetMarketCommentsSuspense<TData = X402ControllerGetMarketCommentsQueryResponse, TQueryKey extends QueryKey = X402ControllerGetMarketCommentsSuspenseQueryKey>(id: X402ControllerGetMarketCommentsPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<X402ControllerGetMarketCommentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? x402ControllerGetMarketCommentsSuspenseQueryKey(id)
         

         const query = useSuspenseQuery({
          ...x402ControllerGetMarketCommentsSuspenseQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}