/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetLatestBatchSnapshotQueryResponse, ZkControllerGetLatestBatchSnapshotPathParams } from "@/lib/api-client/types/zk-controller-get-latest-batch-snapshot";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { zkControllerGetLatestBatchSnapshot } from "@/lib/api-client/client/zk-controller-get-latest-batch-snapshot";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const zkControllerGetLatestBatchSnapshotSuspenseQueryKey = (poolAddress: ZkControllerGetLatestBatchSnapshotPathParams["poolAddress"]) => [{ url: '/api/zk/batch-snapshots/:poolAddress/latest', params: {poolAddress:poolAddress} }] as const

export type ZkControllerGetLatestBatchSnapshotSuspenseQueryKey = ReturnType<typeof zkControllerGetLatestBatchSnapshotSuspenseQueryKey>

export function zkControllerGetLatestBatchSnapshotSuspenseQueryOptions(poolAddress: ZkControllerGetLatestBatchSnapshotPathParams["poolAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetLatestBatchSnapshotSuspenseQueryKey(poolAddress)
        return queryOptions<ZkControllerGetLatestBatchSnapshotQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetLatestBatchSnapshotQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetLatestBatchSnapshot(poolAddress, config)
         },
        })

}

/**
 * @summary Get the latest batch snapshot for a pool
 * {@link /api/zk/batch-snapshots/:poolAddress/latest}
 */
export function useZkControllerGetLatestBatchSnapshotSuspense<TData = ZkControllerGetLatestBatchSnapshotQueryResponse, TQueryKey extends QueryKey = ZkControllerGetLatestBatchSnapshotSuspenseQueryKey>(poolAddress: ZkControllerGetLatestBatchSnapshotPathParams["poolAddress"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ZkControllerGetLatestBatchSnapshotQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetLatestBatchSnapshotSuspenseQueryKey(poolAddress)
         

         const query = useSuspenseQuery({
          ...zkControllerGetLatestBatchSnapshotSuspenseQueryOptions(poolAddress, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}