/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { X402ControllerResolveMarketQueryResponse, X402ControllerResolveMarketPathParams, X402ControllerResolveMarket400, X402ControllerResolveMarket402 } from "@/lib/api-client/types/x402-controller-resolve-market";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { x402ControllerResolveMarket } from "@/lib/api-client/client/x402-controller-resolve-market";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const x402ControllerResolveMarketQueryKey = (id: X402ControllerResolveMarketPathParams["id"]) => [{ url: '/api/v1/markets/:id/resolve', params: {id:id} }] as const

export type X402ControllerResolveMarketQueryKey = ReturnType<typeof x402ControllerResolveMarketQueryKey>

export function x402ControllerResolveMarketQueryOptions(id: X402ControllerResolveMarketPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = x402ControllerResolveMarketQueryKey(id)
        return queryOptions<X402ControllerResolveMarketQueryResponse, ResponseErrorConfig<X402ControllerResolveMarket400 | X402ControllerResolveMarket402>, X402ControllerResolveMarketQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return x402ControllerResolveMarket(id, config)
         },
        })

}

/**
 * @description Triggers oracle-based market resolution. Returns resolution result or reason if not yet resolvable.
 * @summary Resolve a market via oracle (x402 paid: $0.05)
 * {@link /api/v1/markets/:id/resolve}
 */
export function useX402ControllerResolveMarket<TData = X402ControllerResolveMarketQueryResponse, TQueryData = X402ControllerResolveMarketQueryResponse, TQueryKey extends QueryKey = X402ControllerResolveMarketQueryKey>(id: X402ControllerResolveMarketPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<X402ControllerResolveMarketQueryResponse, ResponseErrorConfig<X402ControllerResolveMarket400 | X402ControllerResolveMarket402>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? x402ControllerResolveMarketQueryKey(id)
         

         const query = useQuery({
          ...x402ControllerResolveMarketQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<X402ControllerResolveMarket400 | X402ControllerResolveMarket402>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}