/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { KalshiControllerGetEventByTickerQueryResponse, KalshiControllerGetEventByTickerPathParams } from "@/lib/api-client/types/kalshi-controller-get-event-by-ticker";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { kalshiControllerGetEventByTicker } from "@/lib/api-client/client/kalshi-controller-get-event-by-ticker";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const kalshiControllerGetEventByTickerQueryKey = (ticker: KalshiControllerGetEventByTickerPathParams["ticker"]) => [{ url: '/api/kalshi/events/:ticker', params: {ticker:ticker} }] as const

export type KalshiControllerGetEventByTickerQueryKey = ReturnType<typeof kalshiControllerGetEventByTickerQueryKey>

export function kalshiControllerGetEventByTickerQueryOptions(ticker: KalshiControllerGetEventByTickerPathParams["ticker"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = kalshiControllerGetEventByTickerQueryKey(ticker)
        return queryOptions<KalshiControllerGetEventByTickerQueryResponse, ResponseErrorConfig<Error>, KalshiControllerGetEventByTickerQueryResponse, typeof queryKey>({
         enabled: !!(ticker),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return kalshiControllerGetEventByTicker(ticker, config)
         },
        })

}

/**
 * @summary Get a single Kalshi event by ticker
 * {@link /api/kalshi/events/:ticker}
 */
export function useKalshiControllerGetEventByTicker<TData = KalshiControllerGetEventByTickerQueryResponse, TQueryData = KalshiControllerGetEventByTickerQueryResponse, TQueryKey extends QueryKey = KalshiControllerGetEventByTickerQueryKey>(ticker: KalshiControllerGetEventByTickerPathParams["ticker"], options: 
{
  query?: Partial<QueryObserverOptions<KalshiControllerGetEventByTickerQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? kalshiControllerGetEventByTickerQueryKey(ticker)
         

         const query = useQuery({
          ...kalshiControllerGetEventByTickerQueryOptions(ticker, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}