/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetBatchSnapshotQueryResponse, ZkControllerGetBatchSnapshotPathParams } from "@/lib/api-client/types/zk-controller-get-batch-snapshot";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { zkControllerGetBatchSnapshot } from "@/lib/api-client/client/zk-controller-get-batch-snapshot";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const zkControllerGetBatchSnapshotSuspenseQueryKey = (poolAddress: ZkControllerGetBatchSnapshotPathParams["poolAddress"], batchNumber: ZkControllerGetBatchSnapshotPathParams["batchNumber"]) => [{ url: '/api/zk/batch-snapshots/:poolAddress/:batchNumber', params: {poolAddress:poolAddress,batchNumber:batchNumber} }] as const

export type ZkControllerGetBatchSnapshotSuspenseQueryKey = ReturnType<typeof zkControllerGetBatchSnapshotSuspenseQueryKey>

export function zkControllerGetBatchSnapshotSuspenseQueryOptions(poolAddress: ZkControllerGetBatchSnapshotPathParams["poolAddress"], batchNumber: ZkControllerGetBatchSnapshotPathParams["batchNumber"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetBatchSnapshotSuspenseQueryKey(poolAddress, batchNumber)
        return queryOptions<ZkControllerGetBatchSnapshotQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetBatchSnapshotQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress&& batchNumber),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetBatchSnapshot(poolAddress, batchNumber, config)
         },
        })

}

/**
 * @summary Get a specific batch snapshot
 * {@link /api/zk/batch-snapshots/:poolAddress/:batchNumber}
 */
export function useZkControllerGetBatchSnapshotSuspense<TData = ZkControllerGetBatchSnapshotQueryResponse, TQueryKey extends QueryKey = ZkControllerGetBatchSnapshotSuspenseQueryKey>(poolAddress: ZkControllerGetBatchSnapshotPathParams["poolAddress"], batchNumber: ZkControllerGetBatchSnapshotPathParams["batchNumber"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ZkControllerGetBatchSnapshotQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetBatchSnapshotSuspenseQueryKey(poolAddress, batchNumber)
         

         const query = useSuspenseQuery({
          ...zkControllerGetBatchSnapshotSuspenseQueryOptions(poolAddress, batchNumber, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}