/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetMerkleTreeQueryResponse, ZkControllerGetMerkleTreePathParams } from "@/lib/api-client/types/zk-controller-get-merkle-tree";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { zkControllerGetMerkleTree } from "@/lib/api-client/client/zk-controller-get-merkle-tree";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const zkControllerGetMerkleTreeSuspenseQueryKey = (poolAddress: ZkControllerGetMerkleTreePathParams["poolAddress"]) => [{ url: '/api/zk/merkle-tree/:poolAddress', params: {poolAddress:poolAddress} }] as const

export type ZkControllerGetMerkleTreeSuspenseQueryKey = ReturnType<typeof zkControllerGetMerkleTreeSuspenseQueryKey>

export function zkControllerGetMerkleTreeSuspenseQueryOptions(poolAddress: ZkControllerGetMerkleTreePathParams["poolAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetMerkleTreeSuspenseQueryKey(poolAddress)
        return queryOptions<ZkControllerGetMerkleTreeQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetMerkleTreeQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetMerkleTree(poolAddress, config)
         },
        })

}

/**
 * @summary Get reconstructed Merkle tree data for a pool
 * {@link /api/zk/merkle-tree/:poolAddress}
 */
export function useZkControllerGetMerkleTreeSuspense<TData = ZkControllerGetMerkleTreeQueryResponse, TQueryKey extends QueryKey = ZkControllerGetMerkleTreeSuspenseQueryKey>(poolAddress: ZkControllerGetMerkleTreePathParams["poolAddress"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ZkControllerGetMerkleTreeQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetMerkleTreeSuspenseQueryKey(poolAddress)
         

         const query = useSuspenseQuery({
          ...zkControllerGetMerkleTreeSuspenseQueryOptions(poolAddress, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}