/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PortfolioControllerGetStatsQueryResponse, PortfolioControllerGetStatsPathParams } from "@/lib/api-client/types/portfolio-controller-get-stats";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { portfolioControllerGetStats } from "@/lib/api-client/client/portfolio-controller-get-stats";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const portfolioControllerGetStatsQueryKey = (wallet: PortfolioControllerGetStatsPathParams["wallet"]) => [{ url: '/api/portfolio/:wallet/stats', params: {wallet:wallet} }] as const

export type PortfolioControllerGetStatsQueryKey = ReturnType<typeof portfolioControllerGetStatsQueryKey>

export function portfolioControllerGetStatsQueryOptions(wallet: PortfolioControllerGetStatsPathParams["wallet"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = portfolioControllerGetStatsQueryKey(wallet)
        return queryOptions<PortfolioControllerGetStatsQueryResponse, ResponseErrorConfig<Error>, PortfolioControllerGetStatsQueryResponse, typeof queryKey>({
         enabled: !!(wallet),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return portfolioControllerGetStats(wallet, config)
         },
        })

}

/**
 * @summary Get portfolio statistics for a wallet address
 * {@link /api/portfolio/:wallet/stats}
 */
export function usePortfolioControllerGetStats<TData = PortfolioControllerGetStatsQueryResponse, TQueryData = PortfolioControllerGetStatsQueryResponse, TQueryKey extends QueryKey = PortfolioControllerGetStatsQueryKey>(wallet: PortfolioControllerGetStatsPathParams["wallet"], options: 
{
  query?: Partial<QueryObserverOptions<PortfolioControllerGetStatsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? portfolioControllerGetStatsQueryKey(wallet)
         

         const query = useQuery({
          ...portfolioControllerGetStatsQueryOptions(wallet, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}