/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminControllerRemoveAdminMutationResponse, AdminControllerRemoveAdminPathParams, AdminControllerRemoveAdmin403 } from "@/lib/api-client/types/admin-controller-remove-admin";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminControllerRemoveAdmin } from "@/lib/api-client/client/admin-controller-remove-admin";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminControllerRemoveAdminMutationKey = () => [{ url: '/api/admin/remove/:walletAddress' }] as const

export type AdminControllerRemoveAdminMutationKey = ReturnType<typeof adminControllerRemoveAdminMutationKey>

export function adminControllerRemoveAdminMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = adminControllerRemoveAdminMutationKey()
        return mutationOptions<AdminControllerRemoveAdminMutationResponse, ResponseErrorConfig<AdminControllerRemoveAdmin403>, {walletAddress: AdminControllerRemoveAdminPathParams["walletAddress"]}, TContext>({
          mutationKey,
          mutationFn: async({ walletAddress }) => {
            return adminControllerRemoveAdmin(walletAddress, config)
          },
        })

}

/**
 * @summary Remove an admin (requires admin)
 * {@link /api/admin/remove/:walletAddress}
 */
export function useAdminControllerRemoveAdmin<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminControllerRemoveAdminMutationResponse, ResponseErrorConfig<AdminControllerRemoveAdmin403>, {walletAddress: AdminControllerRemoveAdminPathParams["walletAddress"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? adminControllerRemoveAdminMutationKey()

          const baseOptions = adminControllerRemoveAdminMutationOptions(config) as UseMutationOptions<AdminControllerRemoveAdminMutationResponse, ResponseErrorConfig<AdminControllerRemoveAdmin403>, {walletAddress: AdminControllerRemoveAdminPathParams["walletAddress"]}, TContext>
          

          return useMutation<AdminControllerRemoveAdminMutationResponse, ResponseErrorConfig<AdminControllerRemoveAdmin403>, {walletAddress: AdminControllerRemoveAdminPathParams["walletAddress"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<AdminControllerRemoveAdminMutationResponse, ResponseErrorConfig<AdminControllerRemoveAdmin403>, {walletAddress: AdminControllerRemoveAdminPathParams["walletAddress"]}, TContext>
      
}