/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TokenDataControllerGetBinanceTokensQueryResponse } from "@/lib/api-client/types/token-data-controller-get-binance-tokens";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { tokenDataControllerGetBinanceTokens } from "@/lib/api-client/client/token-data-controller-get-binance-tokens";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const tokenDataControllerGetBinanceTokensQueryKey = () => [{ url: '/api/token-data/binance/tokens' }] as const

export type TokenDataControllerGetBinanceTokensQueryKey = ReturnType<typeof tokenDataControllerGetBinanceTokensQueryKey>

export function tokenDataControllerGetBinanceTokensQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = tokenDataControllerGetBinanceTokensQueryKey()
        return queryOptions<TokenDataControllerGetBinanceTokensQueryResponse, ResponseErrorConfig<Error>, TokenDataControllerGetBinanceTokensQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return tokenDataControllerGetBinanceTokens(config)
         },
        })

}

/**
 * @summary Get all Binance USDT trading pairs with token names
 * {@link /api/token-data/binance/tokens}
 */
export function useTokenDataControllerGetBinanceTokens<TData = TokenDataControllerGetBinanceTokensQueryResponse, TQueryData = TokenDataControllerGetBinanceTokensQueryResponse, TQueryKey extends QueryKey = TokenDataControllerGetBinanceTokensQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<TokenDataControllerGetBinanceTokensQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? tokenDataControllerGetBinanceTokensQueryKey()
         

         const query = useQuery({
          ...tokenDataControllerGetBinanceTokensQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}