/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerIsNullifierUsedQueryResponse, ZkControllerIsNullifierUsedPathParams } from "@/lib/api-client/types/zk-controller-is-nullifier-used";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { zkControllerIsNullifierUsed } from "@/lib/api-client/client/zk-controller-is-nullifier-used";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const zkControllerIsNullifierUsedQueryKey = (poolAddress: ZkControllerIsNullifierUsedPathParams["poolAddress"], nullifierHash: ZkControllerIsNullifierUsedPathParams["nullifierHash"]) => [{ url: '/api/zk/nullifiers/:poolAddress/:nullifierHash', params: {poolAddress:poolAddress,nullifierHash:nullifierHash} }] as const

export type ZkControllerIsNullifierUsedQueryKey = ReturnType<typeof zkControllerIsNullifierUsedQueryKey>

export function zkControllerIsNullifierUsedQueryOptions(poolAddress: ZkControllerIsNullifierUsedPathParams["poolAddress"], nullifierHash: ZkControllerIsNullifierUsedPathParams["nullifierHash"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerIsNullifierUsedQueryKey(poolAddress, nullifierHash)
        return queryOptions<ZkControllerIsNullifierUsedQueryResponse, ResponseErrorConfig<Error>, ZkControllerIsNullifierUsedQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress&& nullifierHash),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerIsNullifierUsed(poolAddress, nullifierHash, config)
         },
        })

}

/**
 * @summary Check if a nullifier has been used
 * {@link /api/zk/nullifiers/:poolAddress/:nullifierHash}
 */
export function useZkControllerIsNullifierUsed<TData = ZkControllerIsNullifierUsedQueryResponse, TQueryData = ZkControllerIsNullifierUsedQueryResponse, TQueryKey extends QueryKey = ZkControllerIsNullifierUsedQueryKey>(poolAddress: ZkControllerIsNullifierUsedPathParams["poolAddress"], nullifierHash: ZkControllerIsNullifierUsedPathParams["nullifierHash"], options: 
{
  query?: Partial<QueryObserverOptions<ZkControllerIsNullifierUsedQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerIsNullifierUsedQueryKey(poolAddress, nullifierHash)
         

         const query = useQuery({
          ...zkControllerIsNullifierUsedQueryOptions(poolAddress, nullifierHash, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}