/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GraduationControllerGetMarketsQueryResponse, GraduationControllerGetMarketsQueryParams } from "@/lib/api-client/types/graduation-controller-get-markets";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { graduationControllerGetMarkets } from "@/lib/api-client/client/graduation-controller-get-markets";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const graduationControllerGetMarketsQueryKey = (params: GraduationControllerGetMarketsQueryParams = {}) => [{ url: '/api/graduation/markets' }, ...(params ? [params] : [])] as const

export type GraduationControllerGetMarketsQueryKey = ReturnType<typeof graduationControllerGetMarketsQueryKey>

export function graduationControllerGetMarketsQueryOptions(params?: GraduationControllerGetMarketsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = graduationControllerGetMarketsQueryKey(params)
        return queryOptions<GraduationControllerGetMarketsQueryResponse, ResponseErrorConfig<Error>, GraduationControllerGetMarketsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return graduationControllerGetMarkets(params, config)
         },
        })

}

/**
 * @summary Get graduation prediction markets
 * {@link /api/graduation/markets}
 */
export function useGraduationControllerGetMarkets<TData = GraduationControllerGetMarketsQueryResponse, TQueryData = GraduationControllerGetMarketsQueryResponse, TQueryKey extends QueryKey = GraduationControllerGetMarketsQueryKey>(params?: GraduationControllerGetMarketsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GraduationControllerGetMarketsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? graduationControllerGetMarketsQueryKey(params)
         

         const query = useQuery({
          ...graduationControllerGetMarketsQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}