/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PortfolioControllerGetCostBasisQueryResponse, PortfolioControllerGetCostBasisPathParams } from "@/lib/api-client/types/portfolio-controller-get-cost-basis";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { portfolioControllerGetCostBasis } from "@/lib/api-client/client/portfolio-controller-get-cost-basis";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const portfolioControllerGetCostBasisSuspenseQueryKey = (wallet: PortfolioControllerGetCostBasisPathParams["wallet"]) => [{ url: '/api/portfolio/:wallet/cost-basis', params: {wallet:wallet} }] as const

export type PortfolioControllerGetCostBasisSuspenseQueryKey = ReturnType<typeof portfolioControllerGetCostBasisSuspenseQueryKey>

export function portfolioControllerGetCostBasisSuspenseQueryOptions(wallet: PortfolioControllerGetCostBasisPathParams["wallet"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = portfolioControllerGetCostBasisSuspenseQueryKey(wallet)
        return queryOptions<PortfolioControllerGetCostBasisQueryResponse, ResponseErrorConfig<Error>, PortfolioControllerGetCostBasisQueryResponse, typeof queryKey>({
         enabled: !!(wallet),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return portfolioControllerGetCostBasis(wallet, config)
         },
        })

}

/**
 * @summary Get cost basis (total SOL spent on BUY trades) per market for a wallet
 * {@link /api/portfolio/:wallet/cost-basis}
 */
export function usePortfolioControllerGetCostBasisSuspense<TData = PortfolioControllerGetCostBasisQueryResponse, TQueryKey extends QueryKey = PortfolioControllerGetCostBasisSuspenseQueryKey>(wallet: PortfolioControllerGetCostBasisPathParams["wallet"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<PortfolioControllerGetCostBasisQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? portfolioControllerGetCostBasisSuspenseQueryKey(wallet)
         

         const query = useSuspenseQuery({
          ...portfolioControllerGetCostBasisSuspenseQueryOptions(wallet, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}