/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PortfolioControllerCheckWatchlistQueryResponse, PortfolioControllerCheckWatchlistPathParams } from "@/lib/api-client/types/portfolio-controller-check-watchlist";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { portfolioControllerCheckWatchlist } from "@/lib/api-client/client/portfolio-controller-check-watchlist";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const portfolioControllerCheckWatchlistQueryKey = (marketId: PortfolioControllerCheckWatchlistPathParams["marketId"]) => [{ url: '/api/portfolio/watchlist/:marketId/check', params: {marketId:marketId} }] as const

export type PortfolioControllerCheckWatchlistQueryKey = ReturnType<typeof portfolioControllerCheckWatchlistQueryKey>

export function portfolioControllerCheckWatchlistQueryOptions(marketId: PortfolioControllerCheckWatchlistPathParams["marketId"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = portfolioControllerCheckWatchlistQueryKey(marketId)
        return queryOptions<PortfolioControllerCheckWatchlistQueryResponse, ResponseErrorConfig<Error>, PortfolioControllerCheckWatchlistQueryResponse, typeof queryKey>({
         enabled: !!(marketId),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return portfolioControllerCheckWatchlist(marketId, config)
         },
        })

}

/**
 * @summary Check if market is in watchlist
 * {@link /api/portfolio/watchlist/:marketId/check}
 */
export function usePortfolioControllerCheckWatchlist<TData = PortfolioControllerCheckWatchlistQueryResponse, TQueryData = PortfolioControllerCheckWatchlistQueryResponse, TQueryKey extends QueryKey = PortfolioControllerCheckWatchlistQueryKey>(marketId: PortfolioControllerCheckWatchlistPathParams["marketId"], options: 
{
  query?: Partial<QueryObserverOptions<PortfolioControllerCheckWatchlistQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? portfolioControllerCheckWatchlistQueryKey(marketId)
         

         const query = useQuery({
          ...portfolioControllerCheckWatchlistQueryOptions(marketId, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}