/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetNoteByCommitmentQueryResponse, ZkControllerGetNoteByCommitmentPathParams } from "@/lib/api-client/types/zk-controller-get-note-by-commitment";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { zkControllerGetNoteByCommitment } from "@/lib/api-client/client/zk-controller-get-note-by-commitment";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const zkControllerGetNoteByCommitmentSuspenseQueryKey = (commitment: ZkControllerGetNoteByCommitmentPathParams["commitment"]) => [{ url: '/api/zk/notes/:commitment', params: {commitment:commitment} }] as const

export type ZkControllerGetNoteByCommitmentSuspenseQueryKey = ReturnType<typeof zkControllerGetNoteByCommitmentSuspenseQueryKey>

export function zkControllerGetNoteByCommitmentSuspenseQueryOptions(commitment: ZkControllerGetNoteByCommitmentPathParams["commitment"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetNoteByCommitmentSuspenseQueryKey(commitment)
        return queryOptions<ZkControllerGetNoteByCommitmentQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetNoteByCommitmentQueryResponse, typeof queryKey>({
         enabled: !!(commitment),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetNoteByCommitment(commitment, config)
         },
        })

}

/**
 * @summary Get a specific note by commitment
 * {@link /api/zk/notes/:commitment}
 */
export function useZkControllerGetNoteByCommitmentSuspense<TData = ZkControllerGetNoteByCommitmentQueryResponse, TQueryKey extends QueryKey = ZkControllerGetNoteByCommitmentSuspenseQueryKey>(commitment: ZkControllerGetNoteByCommitmentPathParams["commitment"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ZkControllerGetNoteByCommitmentQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetNoteByCommitmentSuspenseQueryKey(commitment)
         

         const query = useSuspenseQuery({
          ...zkControllerGetNoteByCommitmentSuspenseQueryOptions(commitment, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}