/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PortfolioControllerCheckWatchlistQueryResponse, PortfolioControllerCheckWatchlistPathParams } from "@/lib/api-client/types/portfolio-controller-check-watchlist";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { portfolioControllerCheckWatchlist } from "@/lib/api-client/client/portfolio-controller-check-watchlist";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const portfolioControllerCheckWatchlistSuspenseQueryKey = (marketId: PortfolioControllerCheckWatchlistPathParams["marketId"]) => [{ url: '/api/portfolio/watchlist/:marketId/check', params: {marketId:marketId} }] as const

export type PortfolioControllerCheckWatchlistSuspenseQueryKey = ReturnType<typeof portfolioControllerCheckWatchlistSuspenseQueryKey>

export function portfolioControllerCheckWatchlistSuspenseQueryOptions(marketId: PortfolioControllerCheckWatchlistPathParams["marketId"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = portfolioControllerCheckWatchlistSuspenseQueryKey(marketId)
        return queryOptions<PortfolioControllerCheckWatchlistQueryResponse, ResponseErrorConfig<Error>, PortfolioControllerCheckWatchlistQueryResponse, typeof queryKey>({
         enabled: !!(marketId),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return portfolioControllerCheckWatchlist(marketId, config)
         },
        })

}

/**
 * @summary Check if market is in watchlist
 * {@link /api/portfolio/watchlist/:marketId/check}
 */
export function usePortfolioControllerCheckWatchlistSuspense<TData = PortfolioControllerCheckWatchlistQueryResponse, TQueryKey extends QueryKey = PortfolioControllerCheckWatchlistSuspenseQueryKey>(marketId: PortfolioControllerCheckWatchlistPathParams["marketId"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<PortfolioControllerCheckWatchlistQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? portfolioControllerCheckWatchlistSuspenseQueryKey(marketId)
         

         const query = useSuspenseQuery({
          ...portfolioControllerCheckWatchlistSuspenseQueryOptions(marketId, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}