/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PolymarketControllerGetEventsQueryResponse, PolymarketControllerGetEventsQueryParams } from "@/lib/api-client/types/polymarket-controller-get-events";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { polymarketControllerGetEvents } from "@/lib/api-client/client/polymarket-controller-get-events";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const polymarketControllerGetEventsSuspenseQueryKey = (params: PolymarketControllerGetEventsQueryParams = {}) => [{ url: '/api/polymarket/events' }, ...(params ? [params] : [])] as const

export type PolymarketControllerGetEventsSuspenseQueryKey = ReturnType<typeof polymarketControllerGetEventsSuspenseQueryKey>

export function polymarketControllerGetEventsSuspenseQueryOptions(params?: PolymarketControllerGetEventsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = polymarketControllerGetEventsSuspenseQueryKey(params)
        return queryOptions<PolymarketControllerGetEventsQueryResponse, ResponseErrorConfig<Error>, PolymarketControllerGetEventsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return polymarketControllerGetEvents(params, config)
         },
        })

}

/**
 * @summary Get trending Polymarket events
 * {@link /api/polymarket/events}
 */
export function usePolymarketControllerGetEventsSuspense<TData = PolymarketControllerGetEventsQueryResponse, TQueryKey extends QueryKey = PolymarketControllerGetEventsSuspenseQueryKey>(params?: PolymarketControllerGetEventsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<PolymarketControllerGetEventsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? polymarketControllerGetEventsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...polymarketControllerGetEventsSuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}