/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetMerkleTreeQueryResponse, ZkControllerGetMerkleTreePathParams } from "@/lib/api-client/types/zk-controller-get-merkle-tree";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { zkControllerGetMerkleTree } from "@/lib/api-client/client/zk-controller-get-merkle-tree";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const zkControllerGetMerkleTreeQueryKey = (poolAddress: ZkControllerGetMerkleTreePathParams["poolAddress"]) => [{ url: '/api/zk/merkle-tree/:poolAddress', params: {poolAddress:poolAddress} }] as const

export type ZkControllerGetMerkleTreeQueryKey = ReturnType<typeof zkControllerGetMerkleTreeQueryKey>

export function zkControllerGetMerkleTreeQueryOptions(poolAddress: ZkControllerGetMerkleTreePathParams["poolAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetMerkleTreeQueryKey(poolAddress)
        return queryOptions<ZkControllerGetMerkleTreeQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetMerkleTreeQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetMerkleTree(poolAddress, config)
         },
        })

}

/**
 * @summary Get reconstructed Merkle tree data for a pool
 * {@link /api/zk/merkle-tree/:poolAddress}
 */
export function useZkControllerGetMerkleTree<TData = ZkControllerGetMerkleTreeQueryResponse, TQueryData = ZkControllerGetMerkleTreeQueryResponse, TQueryKey extends QueryKey = ZkControllerGetMerkleTreeQueryKey>(poolAddress: ZkControllerGetMerkleTreePathParams["poolAddress"], options: 
{
  query?: Partial<QueryObserverOptions<ZkControllerGetMerkleTreeQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetMerkleTreeQueryKey(poolAddress)
         

         const query = useQuery({
          ...zkControllerGetMerkleTreeQueryOptions(poolAddress, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}