/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetMerkleProofQueryResponse, ZkControllerGetMerkleProofPathParams } from "@/lib/api-client/types/zk-controller-get-merkle-proof";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { zkControllerGetMerkleProof } from "@/lib/api-client/client/zk-controller-get-merkle-proof";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const zkControllerGetMerkleProofSuspenseQueryKey = (poolAddress: ZkControllerGetMerkleProofPathParams["poolAddress"], commitment: ZkControllerGetMerkleProofPathParams["commitment"]) => [{ url: '/api/zk/merkle-proof/:poolAddress/:commitment', params: {poolAddress:poolAddress,commitment:commitment} }] as const

export type ZkControllerGetMerkleProofSuspenseQueryKey = ReturnType<typeof zkControllerGetMerkleProofSuspenseQueryKey>

export function zkControllerGetMerkleProofSuspenseQueryOptions(poolAddress: ZkControllerGetMerkleProofPathParams["poolAddress"], commitment: ZkControllerGetMerkleProofPathParams["commitment"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetMerkleProofSuspenseQueryKey(poolAddress, commitment)
        return queryOptions<ZkControllerGetMerkleProofQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetMerkleProofQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress&& commitment),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetMerkleProof(poolAddress, commitment, config)
         },
        })

}

/**
 * @summary Get Merkle proof data for a specific commitment
 * {@link /api/zk/merkle-proof/:poolAddress/:commitment}
 */
export function useZkControllerGetMerkleProofSuspense<TData = ZkControllerGetMerkleProofQueryResponse, TQueryKey extends QueryKey = ZkControllerGetMerkleProofSuspenseQueryKey>(poolAddress: ZkControllerGetMerkleProofPathParams["poolAddress"], commitment: ZkControllerGetMerkleProofPathParams["commitment"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ZkControllerGetMerkleProofQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetMerkleProofSuspenseQueryKey(poolAddress, commitment)
         

         const query = useSuspenseQuery({
          ...zkControllerGetMerkleProofSuspenseQueryOptions(poolAddress, commitment, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}