/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { MetricsControllerTrackEventMutationRequest, MetricsControllerTrackEventMutationResponse } from "@/lib/api-client/types/metrics-controller-track-event";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { metricsControllerTrackEvent } from "@/lib/api-client/client/metrics-controller-track-event";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const metricsControllerTrackEventMutationKey = () => [{ url: '/api/metrics/track' }] as const

export type MetricsControllerTrackEventMutationKey = ReturnType<typeof metricsControllerTrackEventMutationKey>

export function metricsControllerTrackEventMutationOptions<TContext = unknown>(config: Partial<RequestConfig<MetricsControllerTrackEventMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = metricsControllerTrackEventMutationKey()
        return mutationOptions<MetricsControllerTrackEventMutationResponse, ResponseErrorConfig<Error>, {data: MetricsControllerTrackEventMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return metricsControllerTrackEvent(data, config)
          },
        })

}

/**
 * @summary Track an analytics event (fire-and-forget, public)
 * {@link /api/metrics/track}
 */
export function useMetricsControllerTrackEvent<TContext>(options: 
{
  mutation?: UseMutationOptions<MetricsControllerTrackEventMutationResponse, ResponseErrorConfig<Error>, {data: MetricsControllerTrackEventMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<MetricsControllerTrackEventMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? metricsControllerTrackEventMutationKey()

          const baseOptions = metricsControllerTrackEventMutationOptions(config) as UseMutationOptions<MetricsControllerTrackEventMutationResponse, ResponseErrorConfig<Error>, {data: MetricsControllerTrackEventMutationRequest}, TContext>
          

          return useMutation<MetricsControllerTrackEventMutationResponse, ResponseErrorConfig<Error>, {data: MetricsControllerTrackEventMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<MetricsControllerTrackEventMutationResponse, ResponseErrorConfig<Error>, {data: MetricsControllerTrackEventMutationRequest}, TContext>
      
}