/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CommentControllerUpdateMutationRequest, CommentControllerUpdateMutationResponse, CommentControllerUpdatePathParams } from "@/lib/api-client/types/comment-controller-update";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { commentControllerUpdate } from "@/lib/api-client/client/comment-controller-update";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const commentControllerUpdateMutationKey = () => [{ url: '/api/comments/:id' }] as const

export type CommentControllerUpdateMutationKey = ReturnType<typeof commentControllerUpdateMutationKey>

export function commentControllerUpdateMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CommentControllerUpdateMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = commentControllerUpdateMutationKey()
        return mutationOptions<CommentControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: CommentControllerUpdatePathParams["id"], data?: CommentControllerUpdateMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return commentControllerUpdate(id, data, config)
          },
        })

}

/**
 * @summary Update a comment
 * {@link /api/comments/:id}
 */
export function useCommentControllerUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<CommentControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: CommentControllerUpdatePathParams["id"], data?: CommentControllerUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CommentControllerUpdateMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? commentControllerUpdateMutationKey()

          const baseOptions = commentControllerUpdateMutationOptions(config) as UseMutationOptions<CommentControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: CommentControllerUpdatePathParams["id"], data?: CommentControllerUpdateMutationRequest}, TContext>
          

          return useMutation<CommentControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: CommentControllerUpdatePathParams["id"], data?: CommentControllerUpdateMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CommentControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: CommentControllerUpdatePathParams["id"], data?: CommentControllerUpdateMutationRequest}, TContext>
      
}