/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { MarketControllerFindBySlugQueryResponse, MarketControllerFindBySlugPathParams } from "@/lib/api-client/types/market-controller-find-by-slug";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { marketControllerFindBySlug } from "@/lib/api-client/client/market-controller-find-by-slug";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const marketControllerFindBySlugSuspenseQueryKey = (slug: MarketControllerFindBySlugPathParams["slug"]) => [{ url: '/api/markets/by-slug/:slug', params: {slug:slug} }] as const

export type MarketControllerFindBySlugSuspenseQueryKey = ReturnType<typeof marketControllerFindBySlugSuspenseQueryKey>

export function marketControllerFindBySlugSuspenseQueryOptions(slug: MarketControllerFindBySlugPathParams["slug"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketControllerFindBySlugSuspenseQueryKey(slug)
        return queryOptions<MarketControllerFindBySlugQueryResponse, ResponseErrorConfig<Error>, MarketControllerFindBySlugQueryResponse, typeof queryKey>({
         enabled: !!(slug),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return marketControllerFindBySlug(slug, config)
         },
        })

}

/**
 * @summary Get a market by slug
 * {@link /api/markets/by-slug/:slug}
 */
export function useMarketControllerFindBySlugSuspense<TData = MarketControllerFindBySlugQueryResponse, TQueryKey extends QueryKey = MarketControllerFindBySlugSuspenseQueryKey>(slug: MarketControllerFindBySlugPathParams["slug"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<MarketControllerFindBySlugQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? marketControllerFindBySlugSuspenseQueryKey(slug)
         

         const query = useSuspenseQuery({
          ...marketControllerFindBySlugSuspenseQueryOptions(slug, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}