/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerGetCommitmentsQueryResponse, ZkControllerGetCommitmentsPathParams } from "@/lib/api-client/types/zk-controller-get-commitments";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { zkControllerGetCommitments } from "@/lib/api-client/client/zk-controller-get-commitments";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const zkControllerGetCommitmentsSuspenseQueryKey = (poolAddress: ZkControllerGetCommitmentsPathParams["poolAddress"]) => [{ url: '/api/zk/commitments/:poolAddress', params: {poolAddress:poolAddress} }] as const

export type ZkControllerGetCommitmentsSuspenseQueryKey = ReturnType<typeof zkControllerGetCommitmentsSuspenseQueryKey>

export function zkControllerGetCommitmentsSuspenseQueryOptions(poolAddress: ZkControllerGetCommitmentsPathParams["poolAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = zkControllerGetCommitmentsSuspenseQueryKey(poolAddress)
        return queryOptions<ZkControllerGetCommitmentsQueryResponse, ResponseErrorConfig<Error>, ZkControllerGetCommitmentsQueryResponse, typeof queryKey>({
         enabled: !!(poolAddress),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return zkControllerGetCommitments(poolAddress, config)
         },
        })

}

/**
 * @summary Get all commitments for a pool
 * {@link /api/zk/commitments/:poolAddress}
 */
export function useZkControllerGetCommitmentsSuspense<TData = ZkControllerGetCommitmentsQueryResponse, TQueryKey extends QueryKey = ZkControllerGetCommitmentsSuspenseQueryKey>(poolAddress: ZkControllerGetCommitmentsPathParams["poolAddress"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ZkControllerGetCommitmentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? zkControllerGetCommitmentsSuspenseQueryKey(poolAddress)
         

         const query = useSuspenseQuery({
          ...zkControllerGetCommitmentsSuspenseQueryOptions(poolAddress, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}