/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { NotificationControllerRemoveEmailMutationResponse } from "@/lib/api-client/types/notification-controller-remove-email";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { notificationControllerRemoveEmail } from "@/lib/api-client/client/notification-controller-remove-email";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const notificationControllerRemoveEmailMutationKey = () => [{ url: '/api/notifications/email' }] as const

export type NotificationControllerRemoveEmailMutationKey = ReturnType<typeof notificationControllerRemoveEmailMutationKey>

export function notificationControllerRemoveEmailMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = notificationControllerRemoveEmailMutationKey()
        return mutationOptions<NotificationControllerRemoveEmailMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return notificationControllerRemoveEmail(config)
          },
        })

}

/**
 * @summary Remove email and all notification preferences
 * {@link /api/notifications/email}
 */
export function useNotificationControllerRemoveEmail<TContext>(options: 
{
  mutation?: UseMutationOptions<NotificationControllerRemoveEmailMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? notificationControllerRemoveEmailMutationKey()

          const baseOptions = notificationControllerRemoveEmailMutationOptions(config) as UseMutationOptions<NotificationControllerRemoveEmailMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<NotificationControllerRemoveEmailMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<NotificationControllerRemoveEmailMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}