/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { X402ControllerGetPriceHistoryQueryResponse, X402ControllerGetPriceHistoryPathParams, X402ControllerGetPriceHistoryQueryParams } from "@/lib/api-client/types/x402-controller-get-price-history";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { x402ControllerGetPriceHistory } from "@/lib/api-client/client/x402-controller-get-price-history";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const x402ControllerGetPriceHistorySuspenseQueryKey = (id: X402ControllerGetPriceHistoryPathParams["id"], params: X402ControllerGetPriceHistoryQueryParams = {}) => [{ url: '/api/v1/markets/:id/history', params: {id:id} }, ...(params ? [params] : [])] as const

export type X402ControllerGetPriceHistorySuspenseQueryKey = ReturnType<typeof x402ControllerGetPriceHistorySuspenseQueryKey>

export function x402ControllerGetPriceHistorySuspenseQueryOptions(id: X402ControllerGetPriceHistoryPathParams["id"], params?: X402ControllerGetPriceHistoryQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = x402ControllerGetPriceHistorySuspenseQueryKey(id, params)
        return queryOptions<X402ControllerGetPriceHistoryQueryResponse, ResponseErrorConfig<Error>, X402ControllerGetPriceHistoryQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return x402ControllerGetPriceHistory(id, params, config)
         },
        })

}

/**
 * @description Returns historical price snapshots for chart rendering.
 * @summary Get market price history (free)
 * {@link /api/v1/markets/:id/history}
 */
export function useX402ControllerGetPriceHistorySuspense<TData = X402ControllerGetPriceHistoryQueryResponse, TQueryKey extends QueryKey = X402ControllerGetPriceHistorySuspenseQueryKey>(id: X402ControllerGetPriceHistoryPathParams["id"], params?: X402ControllerGetPriceHistoryQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<X402ControllerGetPriceHistoryQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? x402ControllerGetPriceHistorySuspenseQueryKey(id, params)
         

         const query = useSuspenseQuery({
          ...x402ControllerGetPriceHistorySuspenseQueryOptions(id, params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}