/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { BlogControllerUpdateMutationRequest, BlogControllerUpdateMutationResponse, BlogControllerUpdatePathParams } from "@/lib/api-client/types/blog-controller-update";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { blogControllerUpdate } from "@/lib/api-client/client/blog-controller-update";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const blogControllerUpdateMutationKey = () => [{ url: '/api/blogs/:id' }] as const

export type BlogControllerUpdateMutationKey = ReturnType<typeof blogControllerUpdateMutationKey>

export function blogControllerUpdateMutationOptions<TContext = unknown>(config: Partial<RequestConfig<BlogControllerUpdateMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = blogControllerUpdateMutationKey()
        return mutationOptions<BlogControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: BlogControllerUpdatePathParams["id"], data?: BlogControllerUpdateMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return blogControllerUpdate(id, data, config)
          },
        })

}

/**
 * @summary Update a blog post (admin only)
 * {@link /api/blogs/:id}
 */
export function useBlogControllerUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<BlogControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: BlogControllerUpdatePathParams["id"], data?: BlogControllerUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<BlogControllerUpdateMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? blogControllerUpdateMutationKey()

          const baseOptions = blogControllerUpdateMutationOptions(config) as UseMutationOptions<BlogControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: BlogControllerUpdatePathParams["id"], data?: BlogControllerUpdateMutationRequest}, TContext>
          

          return useMutation<BlogControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: BlogControllerUpdatePathParams["id"], data?: BlogControllerUpdateMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<BlogControllerUpdateMutationResponse, ResponseErrorConfig<Error>, {id: BlogControllerUpdatePathParams["id"], data?: BlogControllerUpdateMutationRequest}, TContext>
      
}