/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { MarketControllerFindByMarketIdQueryResponse, MarketControllerFindByMarketIdPathParams, MarketControllerFindByMarketIdQueryParams } from "@/lib/api-client/types/market-controller-find-by-market-id";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { marketControllerFindByMarketId } from "@/lib/api-client/client/market-controller-find-by-market-id";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const marketControllerFindByMarketIdSuspenseQueryKey = (marketId: MarketControllerFindByMarketIdPathParams["marketId"], params: MarketControllerFindByMarketIdQueryParams = {}) => [{ url: '/api/markets/by-market-id/:marketId', params: {marketId:marketId} }, ...(params ? [params] : [])] as const

export type MarketControllerFindByMarketIdSuspenseQueryKey = ReturnType<typeof marketControllerFindByMarketIdSuspenseQueryKey>

export function marketControllerFindByMarketIdSuspenseQueryOptions(marketId: MarketControllerFindByMarketIdPathParams["marketId"], params?: MarketControllerFindByMarketIdQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = marketControllerFindByMarketIdSuspenseQueryKey(marketId, params)
        return queryOptions<MarketControllerFindByMarketIdQueryResponse, ResponseErrorConfig<Error>, MarketControllerFindByMarketIdQueryResponse, typeof queryKey>({
         enabled: !!(marketId),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return marketControllerFindByMarketId(marketId, params, config)
         },
        })

}

/**
 * @summary Get a market by external marketId (auto-creates if not found)
 * {@link /api/markets/by-market-id/:marketId}
 */
export function useMarketControllerFindByMarketIdSuspense<TData = MarketControllerFindByMarketIdQueryResponse, TQueryKey extends QueryKey = MarketControllerFindByMarketIdSuspenseQueryKey>(marketId: MarketControllerFindByMarketIdPathParams["marketId"], params?: MarketControllerFindByMarketIdQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<MarketControllerFindByMarketIdQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? marketControllerFindByMarketIdSuspenseQueryKey(marketId, params)
         

         const query = useSuspenseQuery({
          ...marketControllerFindByMarketIdSuspenseQueryOptions(marketId, params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}