/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerDeleteNoteMutationResponse, ZkControllerDeleteNotePathParams } from "@/lib/api-client/types/zk-controller-delete-note";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { zkControllerDeleteNote } from "@/lib/api-client/client/zk-controller-delete-note";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const zkControllerDeleteNoteMutationKey = () => [{ url: '/api/zk/notes/:commitment' }] as const

export type ZkControllerDeleteNoteMutationKey = ReturnType<typeof zkControllerDeleteNoteMutationKey>

export function zkControllerDeleteNoteMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = zkControllerDeleteNoteMutationKey()
        return mutationOptions<ZkControllerDeleteNoteMutationResponse, ResponseErrorConfig<Error>, {commitment: ZkControllerDeleteNotePathParams["commitment"]}, TContext>({
          mutationKey,
          mutationFn: async({ commitment }) => {
            return zkControllerDeleteNote(commitment, config)
          },
        })

}

/**
 * @summary Delete a note
 * {@link /api/zk/notes/:commitment}
 */
export function useZkControllerDeleteNote<TContext>(options: 
{
  mutation?: UseMutationOptions<ZkControllerDeleteNoteMutationResponse, ResponseErrorConfig<Error>, {commitment: ZkControllerDeleteNotePathParams["commitment"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? zkControllerDeleteNoteMutationKey()

          const baseOptions = zkControllerDeleteNoteMutationOptions(config) as UseMutationOptions<ZkControllerDeleteNoteMutationResponse, ResponseErrorConfig<Error>, {commitment: ZkControllerDeleteNotePathParams["commitment"]}, TContext>
          

          return useMutation<ZkControllerDeleteNoteMutationResponse, ResponseErrorConfig<Error>, {commitment: ZkControllerDeleteNotePathParams["commitment"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ZkControllerDeleteNoteMutationResponse, ResponseErrorConfig<Error>, {commitment: ZkControllerDeleteNotePathParams["commitment"]}, TContext>
      
}