/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ZkControllerMarkNoteSpentMutationResponse, ZkControllerMarkNoteSpentPathParams } from "@/lib/api-client/types/zk-controller-mark-note-spent";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { zkControllerMarkNoteSpent } from "@/lib/api-client/client/zk-controller-mark-note-spent";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const zkControllerMarkNoteSpentMutationKey = () => [{ url: '/api/zk/notes/:commitment/spent' }] as const

export type ZkControllerMarkNoteSpentMutationKey = ReturnType<typeof zkControllerMarkNoteSpentMutationKey>

export function zkControllerMarkNoteSpentMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = zkControllerMarkNoteSpentMutationKey()
        return mutationOptions<ZkControllerMarkNoteSpentMutationResponse, ResponseErrorConfig<Error>, {commitment: ZkControllerMarkNoteSpentPathParams["commitment"]}, TContext>({
          mutationKey,
          mutationFn: async({ commitment }) => {
            return zkControllerMarkNoteSpent(commitment, config)
          },
        })

}

/**
 * @summary Mark a note as spent
 * {@link /api/zk/notes/:commitment/spent}
 */
export function useZkControllerMarkNoteSpent<TContext>(options: 
{
  mutation?: UseMutationOptions<ZkControllerMarkNoteSpentMutationResponse, ResponseErrorConfig<Error>, {commitment: ZkControllerMarkNoteSpentPathParams["commitment"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? zkControllerMarkNoteSpentMutationKey()

          const baseOptions = zkControllerMarkNoteSpentMutationOptions(config) as UseMutationOptions<ZkControllerMarkNoteSpentMutationResponse, ResponseErrorConfig<Error>, {commitment: ZkControllerMarkNoteSpentPathParams["commitment"]}, TContext>
          

          return useMutation<ZkControllerMarkNoteSpentMutationResponse, ResponseErrorConfig<Error>, {commitment: ZkControllerMarkNoteSpentPathParams["commitment"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<ZkControllerMarkNoteSpentMutationResponse, ResponseErrorConfig<Error>, {commitment: ZkControllerMarkNoteSpentPathParams["commitment"]}, TContext>
      
}