/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { BlogControllerFindFeaturedQueryResponse } from "@/lib/api-client/types/blog-controller-find-featured";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { blogControllerFindFeatured } from "@/lib/api-client/client/blog-controller-find-featured";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const blogControllerFindFeaturedSuspenseQueryKey = () => [{ url: '/api/blogs/featured' }] as const

export type BlogControllerFindFeaturedSuspenseQueryKey = ReturnType<typeof blogControllerFindFeaturedSuspenseQueryKey>

export function blogControllerFindFeaturedSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = blogControllerFindFeaturedSuspenseQueryKey()
        return queryOptions<BlogControllerFindFeaturedQueryResponse, ResponseErrorConfig<Error>, BlogControllerFindFeaturedQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return blogControllerFindFeatured(config)
         },
        })

}

/**
 * @summary Get featured blog posts
 * {@link /api/blogs/featured}
 */
export function useBlogControllerFindFeaturedSuspense<TData = BlogControllerFindFeaturedQueryResponse, TQueryKey extends QueryKey = BlogControllerFindFeaturedSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<BlogControllerFindFeaturedQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? blogControllerFindFeaturedSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...blogControllerFindFeaturedSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}