/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { AdminControllerAddAdminMutationResponse, AdminControllerAddAdminPathParams, AdminControllerAddAdmin403 } from "@/lib/api-client/types/admin-controller-add-admin";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getAdminControllerAddAdminUrl(walletAddress: AdminControllerAddAdminPathParams["walletAddress"]) {
  const res = { method: 'POST', url: `/api/admin/add/${walletAddress}` as const }
  return res
}

/**
 * @summary Add a new admin (requires admin)
 * {@link /api/admin/add/:walletAddress}
 */
export async function adminControllerAddAdmin(walletAddress: AdminControllerAddAdminPathParams["walletAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminControllerAddAdminMutationResponse, ResponseErrorConfig<AdminControllerAddAdmin403>, unknown>({ method : "POST", url : getAdminControllerAddAdminUrl(walletAddress).url.toString(), ... requestConfig })
  return res.data
}