/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { AdminControllerRemoveAdminMutationResponse, AdminControllerRemoveAdminPathParams, AdminControllerRemoveAdmin403 } from "@/lib/api-client/types/admin-controller-remove-admin";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getAdminControllerRemoveAdminUrl(walletAddress: AdminControllerRemoveAdminPathParams["walletAddress"]) {
  const res = { method: 'DELETE', url: `/api/admin/remove/${walletAddress}` as const }
  return res
}

/**
 * @summary Remove an admin (requires admin)
 * {@link /api/admin/remove/:walletAddress}
 */
export async function adminControllerRemoveAdmin(walletAddress: AdminControllerRemoveAdminPathParams["walletAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AdminControllerRemoveAdminMutationResponse, ResponseErrorConfig<AdminControllerRemoveAdmin403>, unknown>({ method : "DELETE", url : getAdminControllerRemoveAdminUrl(walletAddress).url.toString(), ... requestConfig })
  return res.data
}