/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ArticleControllerFindAllQueryResponse, ArticleControllerFindAllQueryParams } from "@/lib/api-client/types/article-controller-find-all";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getArticleControllerFindAllUrl() {
  const res = { method: 'GET', url: `/api/articles` as const }
  return res
}

/**
 * @summary List articles (paginated)
 * {@link /api/articles}
 */
export async function articleControllerFindAll(params?: ArticleControllerFindAllQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ArticleControllerFindAllQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getArticleControllerFindAllUrl().url.toString(), params, ... requestConfig })
  return res.data
}