/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ArticleControllerFindBySlugQueryResponse, ArticleControllerFindBySlugPathParams } from "@/lib/api-client/types/article-controller-find-by-slug";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getArticleControllerFindBySlugUrl(slug: ArticleControllerFindBySlugPathParams["slug"]) {
  const res = { method: 'GET', url: `/api/articles/${slug}` as const }
  return res
}

/**
 * @summary Get an article by slug
 * {@link /api/articles/:slug}
 */
export async function articleControllerFindBySlug(slug: ArticleControllerFindBySlugPathParams["slug"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ArticleControllerFindBySlugQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getArticleControllerFindBySlugUrl(slug).url.toString(), ... requestConfig })
  return res.data
}