/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ArticleControllerCreateMutationRequest, ArticleControllerCreateMutationResponse } from "@/lib/api-client/types/article-controller-create";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getArticleControllerCreateUrl() {
  const res = { method: 'POST', url: `/api/articles` as const }
  return res
}

/**
 * @summary Create a new article (admin only)
 * {@link /api/articles}
 */
export async function articleControllerCreate(data: ArticleControllerCreateMutationRequest, config: Partial<RequestConfig<ArticleControllerCreateMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<ArticleControllerCreateMutationResponse, ResponseErrorConfig<Error>, ArticleControllerCreateMutationRequest>({ method : "POST", url : getArticleControllerCreateUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}