/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { AuthControllerLogoutMutationResponse } from "@/lib/api-client/types/auth-controller-logout";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getAuthControllerLogoutUrl() {
  const res = { method: 'POST', url: `/api/auth/logout` as const }
  return res
}

/**
 * @description Rotates the nonce to invalidate all existing tokens
 * @summary Logout and invalidate all sessions
 * {@link /api/auth/logout}
 */
export async function authControllerLogout(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AuthControllerLogoutMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getAuthControllerLogoutUrl().url.toString(), ... requestConfig })
  return res.data
}