/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { AuthControllerRefreshMutationResponse } from "@/lib/api-client/types/auth-controller-refresh";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getAuthControllerRefreshUrl() {
  const res = { method: 'POST', url: `/api/auth/refresh` as const }
  return res
}

/**
 * @description Use refresh token to get new access token
 * @summary Refresh access token
 * {@link /api/auth/refresh}
 */
export async function authControllerRefresh(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<AuthControllerRefreshMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getAuthControllerRefreshUrl().url.toString(), ... requestConfig })
  return res.data
}