/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { AuthControllerVerifyMutationRequest, AuthControllerVerifyMutationResponse } from "@/lib/api-client/types/auth-controller-verify";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getAuthControllerVerifyUrl() {
  const res = { method: 'POST', url: `/api/auth/verify` as const }
  return res
}

/**
 * @description Verifies the wallet signature and returns an access token
 * @summary Verify signed message and get JWT token
 * {@link /api/auth/verify}
 */
export async function authControllerVerify(data: AuthControllerVerifyMutationRequest, config: Partial<RequestConfig<AuthControllerVerifyMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<AuthControllerVerifyMutationResponse, ResponseErrorConfig<Error>, AuthControllerVerifyMutationRequest>({ method : "POST", url : getAuthControllerVerifyUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}