/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { BlogControllerFindAllQueryResponse, BlogControllerFindAllQueryParams } from "@/lib/api-client/types/blog-controller-find-all";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getBlogControllerFindAllUrl() {
  const res = { method: 'GET', url: `/api/blogs` as const }
  return res
}

/**
 * @summary List blog posts (paginated)
 * {@link /api/blogs}
 */
export async function blogControllerFindAll(params?: BlogControllerFindAllQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<BlogControllerFindAllQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getBlogControllerFindAllUrl().url.toString(), params, ... requestConfig })
  return res.data
}