/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { BlogControllerRemoveMutationResponse, BlogControllerRemovePathParams } from "@/lib/api-client/types/blog-controller-remove";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getBlogControllerRemoveUrl(id: BlogControllerRemovePathParams["id"]) {
  const res = { method: 'DELETE', url: `/api/blogs/${id}` as const }
  return res
}

/**
 * @summary Delete a blog post (admin only)
 * {@link /api/blogs/:id}
 */
export async function blogControllerRemove(id: BlogControllerRemovePathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<BlogControllerRemoveMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getBlogControllerRemoveUrl(id).url.toString(), ... requestConfig })
  return res.data
}