/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { BlogControllerFindFeaturedQueryResponse } from "@/lib/api-client/types/blog-controller-find-featured";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getBlogControllerFindFeaturedUrl() {
  const res = { method: 'GET', url: `/api/blogs/featured` as const }
  return res
}

/**
 * @summary Get featured blog posts
 * {@link /api/blogs/featured}
 */
export async function blogControllerFindFeatured(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<BlogControllerFindFeaturedQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getBlogControllerFindFeaturedUrl().url.toString(), ... requestConfig })
  return res.data
}