/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ChatControllerGetConversationsQueryResponse, ChatControllerGetConversationsQueryParams } from "@/lib/api-client/types/chat-controller-get-conversations";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getChatControllerGetConversationsUrl() {
  const res = { method: 'GET', url: `/api/chat/conversations` as const }
  return res
}

/**
 * {@link /api/chat/conversations}
 */
export async function chatControllerGetConversations(params: ChatControllerGetConversationsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ChatControllerGetConversationsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getChatControllerGetConversationsUrl().url.toString(), params, ... requestConfig })
  return res.data
}