/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { CommentControllerFindByMarketQueryResponse, CommentControllerFindByMarketPathParams, CommentControllerFindByMarketQueryParams } from "@/lib/api-client/types/comment-controller-find-by-market";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getCommentControllerFindByMarketUrl(marketId: CommentControllerFindByMarketPathParams["marketId"]) {
  const res = { method: 'GET', url: `/api/comments/market/${marketId}` as const }
  return res
}

/**
 * @summary Get all comments for a market
 * {@link /api/comments/market/:marketId}
 */
export async function commentControllerFindByMarket(marketId: CommentControllerFindByMarketPathParams["marketId"], params?: CommentControllerFindByMarketQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<CommentControllerFindByMarketQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getCommentControllerFindByMarketUrl(marketId).url.toString(), params, ... requestConfig })
  return res.data
}