/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { CommentControllerCreateMutationRequest, CommentControllerCreateMutationResponse } from "@/lib/api-client/types/comment-controller-create";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getCommentControllerCreateUrl() {
  const res = { method: 'POST', url: `/api/comments` as const }
  return res
}

/**
 * @summary Create a new comment with image URLs
 * {@link /api/comments}
 */
export async function commentControllerCreate(data: CommentControllerCreateMutationRequest, config: Partial<RequestConfig<CommentControllerCreateMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<CommentControllerCreateMutationResponse, ResponseErrorConfig<Error>, CommentControllerCreateMutationRequest>({ method : "POST", url : getCommentControllerCreateUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}