/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { CommentControllerFindRepliesQueryResponse, CommentControllerFindRepliesPathParams, CommentControllerFindRepliesQueryParams } from "@/lib/api-client/types/comment-controller-find-replies";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getCommentControllerFindRepliesUrl(commentId: CommentControllerFindRepliesPathParams["commentId"]) {
  const res = { method: 'GET', url: `/api/comments/replies/${commentId}` as const }
  return res
}

/**
 * @summary Get all replies for a comment
 * {@link /api/comments/replies/:commentId}
 */
export async function commentControllerFindReplies(commentId: CommentControllerFindRepliesPathParams["commentId"], params?: CommentControllerFindRepliesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<CommentControllerFindRepliesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getCommentControllerFindRepliesUrl(commentId).url.toString(), params, ... requestConfig })
  return res.data
}