/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { CommentControllerRemoveMutationResponse, CommentControllerRemovePathParams } from "@/lib/api-client/types/comment-controller-remove";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getCommentControllerRemoveUrl(id: CommentControllerRemovePathParams["id"]) {
  const res = { method: 'DELETE', url: `/api/comments/${id}` as const }
  return res
}

/**
 * @summary Delete a comment (also deletes images from R2)
 * {@link /api/comments/:id}
 */
export async function commentControllerRemove(id: CommentControllerRemovePathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<CommentControllerRemoveMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getCommentControllerRemoveUrl(id).url.toString(), ... requestConfig })
  return res.data
}