/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { GraduationControllerGetTrendingQueryResponse, GraduationControllerGetTrendingQueryParams } from "@/lib/api-client/types/graduation-controller-get-trending";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getGraduationControllerGetTrendingUrl() {
  const res = { method: 'GET', url: `/api/graduation/trending` as const }
  return res
}

/**
 * @summary Get trending pump.fun tokens on bonding curve
 * {@link /api/graduation/trending}
 */
export async function graduationControllerGetTrending(params?: GraduationControllerGetTrendingQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GraduationControllerGetTrendingQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGraduationControllerGetTrendingUrl().url.toString(), params, ... requestConfig })
  return res.data
}