/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { KalshiControllerGetEventsQueryResponse, KalshiControllerGetEventsQueryParams } from "@/lib/api-client/types/kalshi-controller-get-events";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getKalshiControllerGetEventsUrl() {
  const res = { method: 'GET', url: `/api/kalshi/events` as const }
  return res
}

/**
 * @summary Get trending Kalshi events
 * {@link /api/kalshi/events}
 */
export async function kalshiControllerGetEvents(params?: KalshiControllerGetEventsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<KalshiControllerGetEventsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getKalshiControllerGetEventsUrl().url.toString(), params, ... requestConfig })
  return res.data
}