/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { MarketControllerCreateMutationRequest, MarketControllerCreateMutationResponse } from "@/lib/api-client/types/market-controller-create";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getMarketControllerCreateUrl() {
  const res = { method: 'POST', url: `/api/markets` as const }
  return res
}

/**
 * @summary Create a new market
 * {@link /api/markets}
 */
export async function marketControllerCreate(data: MarketControllerCreateMutationRequest, config: Partial<RequestConfig<MarketControllerCreateMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<MarketControllerCreateMutationResponse, ResponseErrorConfig<Error>, MarketControllerCreateMutationRequest>({ method : "POST", url : getMarketControllerCreateUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}