/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { MarketControllerRemoveMutationResponse, MarketControllerRemovePathParams } from "@/lib/api-client/types/market-controller-remove";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getMarketControllerRemoveUrl(id: MarketControllerRemovePathParams["id"]) {
  const res = { method: 'DELETE', url: `/api/markets/${id}` as const }
  return res
}

/**
 * @summary Delete a market
 * {@link /api/markets/:id}
 */
export async function marketControllerRemove(id: MarketControllerRemovePathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketControllerRemoveMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getMarketControllerRemoveUrl(id).url.toString(), ... requestConfig })
  return res.data
}