/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { MarketControllerFindByMarketIdQueryResponse, MarketControllerFindByMarketIdPathParams, MarketControllerFindByMarketIdQueryParams } from "@/lib/api-client/types/market-controller-find-by-market-id";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getMarketControllerFindByMarketIdUrl(marketId: MarketControllerFindByMarketIdPathParams["marketId"]) {
  const res = { method: 'GET', url: `/api/markets/by-market-id/${marketId}` as const }
  return res
}

/**
 * @summary Get a market by external marketId (auto-creates if not found)
 * {@link /api/markets/by-market-id/:marketId}
 */
export async function marketControllerFindByMarketId(marketId: MarketControllerFindByMarketIdPathParams["marketId"], params?: MarketControllerFindByMarketIdQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketControllerFindByMarketIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getMarketControllerFindByMarketIdUrl(marketId).url.toString(), params, ... requestConfig })
  return res.data
}