/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { MarketControllerGetRecentTradesQueryResponse, MarketControllerGetRecentTradesQueryParams } from "@/lib/api-client/types/market-controller-get-recent-trades";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getMarketControllerGetRecentTradesUrl() {
  const res = { method: 'GET', url: `/api/markets/recent-trades` as const }
  return res
}

/**
 * @summary Get recent trades across all markets
 * {@link /api/markets/recent-trades}
 */
export async function marketControllerGetRecentTrades(params?: MarketControllerGetRecentTradesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketControllerGetRecentTradesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getMarketControllerGetRecentTradesUrl().url.toString(), params, ... requestConfig })
  return res.data
}