/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { MarketControllerFindBySlugQueryResponse, MarketControllerFindBySlugPathParams } from "@/lib/api-client/types/market-controller-find-by-slug";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getMarketControllerFindBySlugUrl(slug: MarketControllerFindBySlugPathParams["slug"]) {
  const res = { method: 'GET', url: `/api/markets/by-slug/${slug}` as const }
  return res
}

/**
 * @summary Get a market by slug
 * {@link /api/markets/by-slug/:slug}
 */
export async function marketControllerFindBySlug(slug: MarketControllerFindBySlugPathParams["slug"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MarketControllerFindBySlugQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getMarketControllerFindBySlugUrl(slug).url.toString(), ... requestConfig })
  return res.data
}