/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { MetricsControllerGetMetricsSummaryQueryResponse, MetricsControllerGetMetricsSummaryQueryParams, MetricsControllerGetMetricsSummary403 } from "@/lib/api-client/types/metrics-controller-get-metrics-summary";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getMetricsControllerGetMetricsSummaryUrl() {
  const res = { method: 'GET', url: `/api/metrics/summary` as const }
  return res
}

/**
 * @summary Get metrics summary (requires admin)
 * {@link /api/metrics/summary}
 */
export async function metricsControllerGetMetricsSummary(params?: MetricsControllerGetMetricsSummaryQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<MetricsControllerGetMetricsSummaryQueryResponse, ResponseErrorConfig<MetricsControllerGetMetricsSummary403>, unknown>({ method : "GET", url : getMetricsControllerGetMetricsSummaryUrl().url.toString(), params, ... requestConfig })
  return res.data
}