/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { NotificationControllerSetEmailMutationRequest, NotificationControllerSetEmailMutationResponse } from "@/lib/api-client/types/notification-controller-set-email";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getNotificationControllerSetEmailUrl() {
  const res = { method: 'PATCH', url: `/api/notifications/email` as const }
  return res
}

/**
 * @summary Set or update email for notifications (triggers verification)
 * {@link /api/notifications/email}
 */
export async function notificationControllerSetEmail(data: NotificationControllerSetEmailMutationRequest, config: Partial<RequestConfig<NotificationControllerSetEmailMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<NotificationControllerSetEmailMutationResponse, ResponseErrorConfig<Error>, NotificationControllerSetEmailMutationRequest>({ method : "PATCH", url : getNotificationControllerSetEmailUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}