/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { NotificationControllerVerifyEmailQueryResponse, NotificationControllerVerifyEmailQueryParams } from "@/lib/api-client/types/notification-controller-verify-email";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getNotificationControllerVerifyEmailUrl() {
  const res = { method: 'GET', url: `/api/notifications/email/verify` as const }
  return res
}

/**
 * @summary Verify email via signed token
 * {@link /api/notifications/email/verify}
 */
export async function notificationControllerVerifyEmail(params: NotificationControllerVerifyEmailQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<NotificationControllerVerifyEmailQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getNotificationControllerVerifyEmailUrl().url.toString(), params, ... requestConfig })
  return res.data
}