/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { NotificationControllerGetUnreadCountQueryResponse } from "@/lib/api-client/types/notification-controller-get-unread-count";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getNotificationControllerGetUnreadCountUrl() {
  const res = { method: 'GET', url: `/api/notifications/unread-count` as const }
  return res
}

/**
 * @summary Get unread notification count (for badge)
 * {@link /api/notifications/unread-count}
 */
export async function notificationControllerGetUnreadCount(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<NotificationControllerGetUnreadCountQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getNotificationControllerGetUnreadCountUrl().url.toString(), ... requestConfig })
  return res.data
}