/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { NotificationControllerGetHistoryQueryResponse, NotificationControllerGetHistoryQueryParams } from "@/lib/api-client/types/notification-controller-get-history";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getNotificationControllerGetHistoryUrl() {
  const res = { method: 'GET', url: `/api/notifications/history` as const }
  return res
}

/**
 * @summary Get paginated notification history
 * {@link /api/notifications/history}
 */
export async function notificationControllerGetHistory(params?: NotificationControllerGetHistoryQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<NotificationControllerGetHistoryQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getNotificationControllerGetHistoryUrl().url.toString(), params, ... requestConfig })
  return res.data
}