/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { NotificationControllerMarkAsReadMutationResponse, NotificationControllerMarkAsReadPathParams } from "@/lib/api-client/types/notification-controller-mark-as-read";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getNotificationControllerMarkAsReadUrl(id: NotificationControllerMarkAsReadPathParams["id"]) {
  const res = { method: 'PATCH', url: `/api/notifications/${id}/read` as const }
  return res
}

/**
 * @summary Mark a single notification as read
 * {@link /api/notifications/:id/read}
 */
export async function notificationControllerMarkAsRead(id: NotificationControllerMarkAsReadPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<NotificationControllerMarkAsReadMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "PATCH", url : getNotificationControllerMarkAsReadUrl(id).url.toString(), ... requestConfig })
  return res.data
}