/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { PolymarketControllerGetEventsQueryResponse, PolymarketControllerGetEventsQueryParams } from "@/lib/api-client/types/polymarket-controller-get-events";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getPolymarketControllerGetEventsUrl() {
  const res = { method: 'GET', url: `/api/polymarket/events` as const }
  return res
}

/**
 * @summary Get trending Polymarket events
 * {@link /api/polymarket/events}
 */
export async function polymarketControllerGetEvents(params?: PolymarketControllerGetEventsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PolymarketControllerGetEventsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPolymarketControllerGetEventsUrl().url.toString(), params, ... requestConfig })
  return res.data
}