/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { PolymarketControllerForceResolveMutationResponse, PolymarketControllerForceResolvePathParams } from "@/lib/api-client/types/polymarket-controller-force-resolve";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getPolymarketControllerForceResolveUrl(marketId: PolymarketControllerForceResolvePathParams["marketId"]) {
  const res = { method: 'POST', url: `/api/polymarket/force-resolve/${marketId}` as const }
  return res
}

/**
 * @summary Force-resolve a specific market
 * {@link /api/polymarket/force-resolve/:marketId}
 */
export async function polymarketControllerForceResolve(marketId: PolymarketControllerForceResolvePathParams["marketId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PolymarketControllerForceResolveMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPolymarketControllerForceResolveUrl(marketId).url.toString(), ... requestConfig })
  return res.data
}