/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { PolymarketControllerTriggerResolutionCheckMutationResponse } from "@/lib/api-client/types/polymarket-controller-trigger-resolution-check";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getPolymarketControllerTriggerResolutionCheckUrl() {
  const res = { method: 'POST', url: `/api/polymarket/resolution-check` as const }
  return res
}

/**
 * @summary Trigger manual Polymarket resolution check
 * {@link /api/polymarket/resolution-check}
 */
export async function polymarketControllerTriggerResolutionCheck(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PolymarketControllerTriggerResolutionCheckMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPolymarketControllerTriggerResolutionCheckUrl().url.toString(), ... requestConfig })
  return res.data
}