/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { PolymarketControllerGetEventBySlugQueryResponse, PolymarketControllerGetEventBySlugPathParams } from "@/lib/api-client/types/polymarket-controller-get-event-by-slug";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getPolymarketControllerGetEventBySlugUrl(slug: PolymarketControllerGetEventBySlugPathParams["slug"]) {
  const res = { method: 'GET', url: `/api/polymarket/events/${slug}` as const }
  return res
}

/**
 * @summary Get a single Polymarket event by slug
 * {@link /api/polymarket/events/:slug}
 */
export async function polymarketControllerGetEventBySlug(slug: PolymarketControllerGetEventBySlugPathParams["slug"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PolymarketControllerGetEventBySlugQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPolymarketControllerGetEventBySlugUrl(slug).url.toString(), ... requestConfig })
  return res.data
}