/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { PortfolioControllerGetCostBasisQueryResponse, PortfolioControllerGetCostBasisPathParams } from "@/lib/api-client/types/portfolio-controller-get-cost-basis";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getPortfolioControllerGetCostBasisUrl(wallet: PortfolioControllerGetCostBasisPathParams["wallet"]) {
  const res = { method: 'GET', url: `/api/portfolio/${wallet}/cost-basis` as const }
  return res
}

/**
 * @summary Get cost basis (total SOL spent on BUY trades) per market for a wallet
 * {@link /api/portfolio/:wallet/cost-basis}
 */
export async function portfolioControllerGetCostBasis(wallet: PortfolioControllerGetCostBasisPathParams["wallet"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PortfolioControllerGetCostBasisQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPortfolioControllerGetCostBasisUrl(wallet).url.toString(), ... requestConfig })
  return res.data
}