/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { PortfolioControllerGetHistoryQueryResponse, PortfolioControllerGetHistoryPathParams, PortfolioControllerGetHistoryQueryParams } from "@/lib/api-client/types/portfolio-controller-get-history";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getPortfolioControllerGetHistoryUrl(wallet: PortfolioControllerGetHistoryPathParams["wallet"]) {
  const res = { method: 'GET', url: `/api/portfolio/${wallet}/history` as const }
  return res
}

/**
 * @summary Get transaction history for a wallet address
 * {@link /api/portfolio/:wallet/history}
 */
export async function portfolioControllerGetHistory(wallet: PortfolioControllerGetHistoryPathParams["wallet"], params?: PortfolioControllerGetHistoryQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PortfolioControllerGetHistoryQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPortfolioControllerGetHistoryUrl(wallet).url.toString(), params, ... requestConfig })
  return res.data
}