/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { PortfolioControllerGetStatsQueryResponse, PortfolioControllerGetStatsPathParams } from "@/lib/api-client/types/portfolio-controller-get-stats";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getPortfolioControllerGetStatsUrl(wallet: PortfolioControllerGetStatsPathParams["wallet"]) {
  const res = { method: 'GET', url: `/api/portfolio/${wallet}/stats` as const }
  return res
}

/**
 * @summary Get portfolio statistics for a wallet address
 * {@link /api/portfolio/:wallet/stats}
 */
export async function portfolioControllerGetStats(wallet: PortfolioControllerGetStatsPathParams["wallet"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PortfolioControllerGetStatsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPortfolioControllerGetStatsUrl(wallet).url.toString(), ... requestConfig })
  return res.data
}