/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { PortfolioControllerGetWatchlistQueryResponse } from "@/lib/api-client/types/portfolio-controller-get-watchlist";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getPortfolioControllerGetWatchlistUrl() {
  const res = { method: 'GET', url: `/api/portfolio/watchlist` as const }
  return res
}

/**
 * @summary Get user watchlist
 * {@link /api/portfolio/watchlist}
 */
export async function portfolioControllerGetWatchlist(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PortfolioControllerGetWatchlistQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getPortfolioControllerGetWatchlistUrl().url.toString(), ... requestConfig })
  return res.data
}