/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { SnapshotControllerFindByMarketQueryResponse, SnapshotControllerFindByMarketPathParams, SnapshotControllerFindByMarketQueryParams } from "@/lib/api-client/types/snapshot-controller-find-by-market";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getSnapshotControllerFindByMarketUrl(marketId: SnapshotControllerFindByMarketPathParams["marketId"]) {
  const res = { method: 'GET', url: `/api/snapshots/${marketId}` as const }
  return res
}

/**
 * @summary Get probability history for a market
 * {@link /api/snapshots/:marketId}
 */
export async function snapshotControllerFindByMarket(marketId: SnapshotControllerFindByMarketPathParams["marketId"], params?: SnapshotControllerFindByMarketQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<SnapshotControllerFindByMarketQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getSnapshotControllerFindByMarketUrl(marketId).url.toString(), params, ... requestConfig })
  return res.data
}