/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { SnapshotControllerCreateMutationRequest, SnapshotControllerCreateMutationResponse } from "@/lib/api-client/types/snapshot-controller-create";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getSnapshotControllerCreateUrl() {
  const res = { method: 'POST', url: `/api/snapshots` as const }
  return res
}

/**
 * @summary Record a market probability snapshot
 * {@link /api/snapshots}
 */
export async function snapshotControllerCreate(data: SnapshotControllerCreateMutationRequest, config: Partial<RequestConfig<SnapshotControllerCreateMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<SnapshotControllerCreateMutationResponse, ResponseErrorConfig<Error>, SnapshotControllerCreateMutationRequest>({ method : "POST", url : getSnapshotControllerCreateUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}