/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { TokenDataControllerGetGlobalStatsQueryResponse } from "@/lib/api-client/types/token-data-controller-get-global-stats";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getTokenDataControllerGetGlobalStatsUrl() {
  const res = { method: 'GET', url: `/api/token-data/global/stats` as const }
  return res
}

/**
 * @summary Get global crypto market stats
 * {@link /api/token-data/global/stats}
 */
export async function tokenDataControllerGetGlobalStats(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TokenDataControllerGetGlobalStatsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getTokenDataControllerGetGlobalStatsUrl().url.toString(), ... requestConfig })
  return res.data
}