/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { TokenDataControllerGetOhlcvQueryResponse, TokenDataControllerGetOhlcvPathParams, TokenDataControllerGetOhlcvQueryParams } from "@/lib/api-client/types/token-data-controller-get-ohlcv";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getTokenDataControllerGetOhlcvUrl(mint: TokenDataControllerGetOhlcvPathParams["mint"]) {
  const res = { method: 'GET', url: `/api/token-data/${mint}/ohlcv` as const }
  return res
}

/**
 * @summary Get OHLCV candlestick data
 * {@link /api/token-data/:mint/ohlcv}
 */
export async function tokenDataControllerGetOhlcv(mint: TokenDataControllerGetOhlcvPathParams["mint"], params?: TokenDataControllerGetOhlcvQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TokenDataControllerGetOhlcvQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getTokenDataControllerGetOhlcvUrl(mint).url.toString(), params, ... requestConfig })
  return res.data
}