/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { TokenDataControllerGetBinanceTokensQueryResponse } from "@/lib/api-client/types/token-data-controller-get-binance-tokens";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getTokenDataControllerGetBinanceTokensUrl() {
  const res = { method: 'GET', url: `/api/token-data/binance/tokens` as const }
  return res
}

/**
 * @summary Get all Binance USDT trading pairs with token names
 * {@link /api/token-data/binance/tokens}
 */
export async function tokenDataControllerGetBinanceTokens(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TokenDataControllerGetBinanceTokensQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getTokenDataControllerGetBinanceTokensUrl().url.toString(), ... requestConfig })
  return res.data
}