/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { UploadControllerUploadImagesMutationResponse } from "@/lib/api-client/types/upload-controller-upload-images";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getUploadControllerUploadImagesUrl() {
  const res = { method: 'POST', url: `/api/r2/upload` as const }
  return res
}

/**
 * @description Upload up to 5 images and receive their public URLs. Use these URLs when creating comments.
 * @summary Upload images to R2 and get URLs
 * {@link /api/r2/upload}
 */
export async function uploadControllerUploadImages(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<UploadControllerUploadImagesMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getUploadControllerUploadImagesUrl().url.toString(), ... requestConfig })
  return res.data
}