/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { UserControllerGetCurrentUserQueryResponse, UserControllerGetCurrentUser401 } from "@/lib/api-client/types/user-controller-get-current-user";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getUserControllerGetCurrentUserUrl() {
  const res = { method: 'GET', url: `/api/users/me` as const }
  return res
}

/**
 * @summary Get current user profile
 * {@link /api/users/me}
 */
export async function userControllerGetCurrentUser(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<UserControllerGetCurrentUserQueryResponse, ResponseErrorConfig<UserControllerGetCurrentUser401>, unknown>({ method : "GET", url : getUserControllerGetCurrentUserUrl().url.toString(), ... requestConfig })
  return res.data
}