/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { X402ControllerGetX402InfoQueryResponse } from "@/lib/api-client/types/x402-controller-get-x402-info";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getX402ControllerGetX402InfoUrl() {
  const res = { method: 'GET', url: `/api/x402-info` as const }
  return res
}

/**
 * @description Lists all available paid endpoints with their prices. No payment required. Use this to discover the API.
 * @summary x402 endpoint information (free)
 * {@link /api/x402-info}
 */
export async function x402ControllerGetX402Info(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<X402ControllerGetX402InfoQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getX402ControllerGetX402InfoUrl().url.toString(), ... requestConfig })
  return res.data
}