/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { X402ControllerGetPriceHistoryQueryResponse, X402ControllerGetPriceHistoryPathParams, X402ControllerGetPriceHistoryQueryParams } from "@/lib/api-client/types/x402-controller-get-price-history";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getX402ControllerGetPriceHistoryUrl(id: X402ControllerGetPriceHistoryPathParams["id"]) {
  const res = { method: 'GET', url: `/api/v1/markets/${id}/history` as const }
  return res
}

/**
 * @description Returns historical price snapshots for chart rendering.
 * @summary Get market price history (free)
 * {@link /api/v1/markets/:id/history}
 */
export async function x402ControllerGetPriceHistory(id: X402ControllerGetPriceHistoryPathParams["id"], params?: X402ControllerGetPriceHistoryQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<X402ControllerGetPriceHistoryQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getX402ControllerGetPriceHistoryUrl(id).url.toString(), params, ... requestConfig })
  return res.data
}