/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { X402ControllerCreateMarketMutationRequest, X402ControllerCreateMarketMutationResponse, X402ControllerCreateMarket400, X402ControllerCreateMarket402 } from "@/lib/api-client/types/x402-controller-create-market";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getX402ControllerCreateMarketUrl() {
  const res = { method: 'POST', url: `/api/v1/markets/create` as const }
  return res
}

/**
 * @description Creates a new prediction market on-chain for a PumpFun token. Requires x402 USDC payment of $0.50.
 * @summary Create a prediction market (x402 paid: $0.50)
 * {@link /api/v1/markets/create}
 */
export async function x402ControllerCreateMarket(data: X402ControllerCreateMarketMutationRequest, config: Partial<RequestConfig<X402ControllerCreateMarketMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<X402ControllerCreateMarketMutationResponse, ResponseErrorConfig<X402ControllerCreateMarket400 | X402ControllerCreateMarket402>, X402ControllerCreateMarketMutationRequest>({ method : "POST", url : getX402ControllerCreateMarketUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}