/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { X402ControllerGetMarketCommentsQueryResponse, X402ControllerGetMarketCommentsPathParams } from "@/lib/api-client/types/x402-controller-get-market-comments";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getX402ControllerGetMarketCommentsUrl(id: X402ControllerGetMarketCommentsPathParams["id"]) {
  const res = { method: 'GET', url: `/api/v1/markets/${id}/comments` as const }
  return res
}

/**
 * @description Returns community comments and replies for a market.
 * @summary Get market comments (free)
 * {@link /api/v1/markets/:id/comments}
 */
export async function x402ControllerGetMarketComments(id: X402ControllerGetMarketCommentsPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<X402ControllerGetMarketCommentsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getX402ControllerGetMarketCommentsUrl(id).url.toString(), ... requestConfig })
  return res.data
}