/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { X402ControllerListMarketsQueryResponse } from "@/lib/api-client/types/x402-controller-list-markets";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getX402ControllerListMarketsUrl() {
  const res = { method: 'GET', url: `/api/v1/markets` as const }
  return res
}

/**
 * @description Returns all prediction markets with current prices computed from on-chain reserves.
 * @summary List all markets (free)
 * {@link /api/v1/markets}
 */
export async function x402ControllerListMarkets(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<X402ControllerListMarketsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getX402ControllerListMarketsUrl().url.toString(), ... requestConfig })
  return res.data
}