/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { X402ControllerHealthQueryResponse } from "@/lib/api-client/types/x402-controller-health";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getX402ControllerHealthUrl() {
  const res = { method: 'GET', url: `/api/health` as const }
  return res
}

/**
 * @description Returns server health status, uptime, network, and active market count. No payment required.
 * @summary Health check (free)
 * {@link /api/health}
 */
export async function x402ControllerHealth(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<X402ControllerHealthQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getX402ControllerHealthUrl().url.toString(), ... requestConfig })
  return res.data
}