/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { X402ControllerResolveMarketQueryResponse, X402ControllerResolveMarketPathParams, X402ControllerResolveMarket400, X402ControllerResolveMarket402 } from "@/lib/api-client/types/x402-controller-resolve-market";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getX402ControllerResolveMarketUrl(id: X402ControllerResolveMarketPathParams["id"]) {
  const res = { method: 'GET', url: `/api/v1/markets/${id}/resolve` as const }
  return res
}

/**
 * @description Triggers oracle-based market resolution. Returns resolution result or reason if not yet resolvable.
 * @summary Resolve a market via oracle (x402 paid: $0.05)
 * {@link /api/v1/markets/:id/resolve}
 */
export async function x402ControllerResolveMarket(id: X402ControllerResolveMarketPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<X402ControllerResolveMarketQueryResponse, ResponseErrorConfig<X402ControllerResolveMarket400 | X402ControllerResolveMarket402>, unknown>({ method : "GET", url : getX402ControllerResolveMarketUrl(id).url.toString(), ... requestConfig })
  return res.data
}