/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ZkControllerStoreNoteMutationRequest, ZkControllerStoreNoteMutationResponse } from "@/lib/api-client/types/zk-controller-store-note";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getZkControllerStoreNoteUrl() {
  const res = { method: 'POST', url: `/api/zk/notes` as const }
  return res
}

/**
 * @summary Store an encrypted note
 * {@link /api/zk/notes}
 */
export async function zkControllerStoreNote(data: ZkControllerStoreNoteMutationRequest, config: Partial<RequestConfig<ZkControllerStoreNoteMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<ZkControllerStoreNoteMutationResponse, ResponseErrorConfig<Error>, ZkControllerStoreNoteMutationRequest>({ method : "POST", url : getZkControllerStoreNoteUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}