/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ZkControllerStoreCommitmentsMutationRequest, ZkControllerStoreCommitmentsMutationResponse } from "@/lib/api-client/types/zk-controller-store-commitments";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getZkControllerStoreCommitmentsUrl() {
  const res = { method: 'POST', url: `/api/zk/commitments/batch` as const }
  return res
}

/**
 * @summary Index multiple commitments at once
 * {@link /api/zk/commitments/batch}
 */
export async function zkControllerStoreCommitments(data?: ZkControllerStoreCommitmentsMutationRequest, config: Partial<RequestConfig<ZkControllerStoreCommitmentsMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<ZkControllerStoreCommitmentsMutationResponse, ResponseErrorConfig<Error>, ZkControllerStoreCommitmentsMutationRequest>({ method : "POST", url : getZkControllerStoreCommitmentsUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}