/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ZkControllerGetMerkleProofQueryResponse, ZkControllerGetMerkleProofPathParams } from "@/lib/api-client/types/zk-controller-get-merkle-proof";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getZkControllerGetMerkleProofUrl(poolAddress: ZkControllerGetMerkleProofPathParams["poolAddress"], commitment: ZkControllerGetMerkleProofPathParams["commitment"]) {
  const res = { method: 'GET', url: `/api/zk/merkle-proof/${poolAddress}/${commitment}` as const }
  return res
}

/**
 * @summary Get Merkle proof data for a specific commitment
 * {@link /api/zk/merkle-proof/:poolAddress/:commitment}
 */
export async function zkControllerGetMerkleProof(poolAddress: ZkControllerGetMerkleProofPathParams["poolAddress"], commitment: ZkControllerGetMerkleProofPathParams["commitment"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ZkControllerGetMerkleProofQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getZkControllerGetMerkleProofUrl(poolAddress, commitment).url.toString(), ... requestConfig })
  return res.data
}