/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ZkControllerStoreBatchSnapshotMutationRequest, ZkControllerStoreBatchSnapshotMutationResponse } from "@/lib/api-client/types/zk-controller-store-batch-snapshot";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getZkControllerStoreBatchSnapshotUrl() {
  const res = { method: 'POST', url: `/api/zk/batch-snapshots` as const }
  return res
}

/**
 * @summary Store a batch snapshot (called when batch is finalized on-chain)
 * {@link /api/zk/batch-snapshots}
 */
export async function zkControllerStoreBatchSnapshot(data: ZkControllerStoreBatchSnapshotMutationRequest, config: Partial<RequestConfig<ZkControllerStoreBatchSnapshotMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<ZkControllerStoreBatchSnapshotMutationResponse, ResponseErrorConfig<Error>, ZkControllerStoreBatchSnapshotMutationRequest>({ method : "POST", url : getZkControllerStoreBatchSnapshotUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}