/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ZkControllerGetPoolStatsQueryResponse, ZkControllerGetPoolStatsPathParams } from "@/lib/api-client/types/zk-controller-get-pool-stats";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getZkControllerGetPoolStatsUrl(poolAddress: ZkControllerGetPoolStatsPathParams["poolAddress"]) {
  const res = { method: 'GET', url: `/api/zk/stats/${poolAddress}` as const }
  return res
}

/**
 * @summary Get statistics for a pool
 * {@link /api/zk/stats/:poolAddress}
 */
export async function zkControllerGetPoolStats(poolAddress: ZkControllerGetPoolStatsPathParams["poolAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ZkControllerGetPoolStatsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getZkControllerGetPoolStatsUrl(poolAddress).url.toString(), ... requestConfig })
  return res.data
}