/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ZkControllerGetNoteByCommitmentQueryResponse, ZkControllerGetNoteByCommitmentPathParams } from "@/lib/api-client/types/zk-controller-get-note-by-commitment";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getZkControllerGetNoteByCommitmentUrl(commitment: ZkControllerGetNoteByCommitmentPathParams["commitment"]) {
  const res = { method: 'GET', url: `/api/zk/notes/${commitment}` as const }
  return res
}

/**
 * @summary Get a specific note by commitment
 * {@link /api/zk/notes/:commitment}
 */
export async function zkControllerGetNoteByCommitment(commitment: ZkControllerGetNoteByCommitmentPathParams["commitment"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ZkControllerGetNoteByCommitmentQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getZkControllerGetNoteByCommitmentUrl(commitment).url.toString(), ... requestConfig })
  return res.data
}