/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ZkControllerUpdateNoteMutationRequest, ZkControllerUpdateNoteMutationResponse, ZkControllerUpdateNotePathParams } from "@/lib/api-client/types/zk-controller-update-note";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getZkControllerUpdateNoteUrl(commitment: ZkControllerUpdateNotePathParams["commitment"]) {
  const res = { method: 'PATCH', url: `/api/zk/notes/${commitment}` as const }
  return res
}

/**
 * @summary Update a note (e.g., mark as spent)
 * {@link /api/zk/notes/:commitment}
 */
export async function zkControllerUpdateNote(commitment: ZkControllerUpdateNotePathParams["commitment"], data?: ZkControllerUpdateNoteMutationRequest, config: Partial<RequestConfig<ZkControllerUpdateNoteMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<ZkControllerUpdateNoteMutationResponse, ResponseErrorConfig<Error>, ZkControllerUpdateNoteMutationRequest>({ method : "PATCH", url : getZkControllerUpdateNoteUrl(commitment).url.toString(), data : requestData, ... requestConfig })
  return res.data
}