/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ZkControllerIsNullifierUsedQueryResponse, ZkControllerIsNullifierUsedPathParams } from "@/lib/api-client/types/zk-controller-is-nullifier-used";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getZkControllerIsNullifierUsedUrl(poolAddress: ZkControllerIsNullifierUsedPathParams["poolAddress"], nullifierHash: ZkControllerIsNullifierUsedPathParams["nullifierHash"]) {
  const res = { method: 'GET', url: `/api/zk/nullifiers/${poolAddress}/${nullifierHash}` as const }
  return res
}

/**
 * @summary Check if a nullifier has been used
 * {@link /api/zk/nullifiers/:poolAddress/:nullifierHash}
 */
export async function zkControllerIsNullifierUsed(poolAddress: ZkControllerIsNullifierUsedPathParams["poolAddress"], nullifierHash: ZkControllerIsNullifierUsedPathParams["nullifierHash"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ZkControllerIsNullifierUsedQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getZkControllerIsNullifierUsedUrl(poolAddress, nullifierHash).url.toString(), ... requestConfig })
  return res.data
}