/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ZkControllerGetNotesQueryResponse, ZkControllerGetNotesQueryParams } from "@/lib/api-client/types/zk-controller-get-notes";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getZkControllerGetNotesUrl() {
  const res = { method: 'GET', url: `/api/zk/notes` as const }
  return res
}

/**
 * @summary Get user's encrypted notes
 * {@link /api/zk/notes}
 */
export async function zkControllerGetNotes(params?: ZkControllerGetNotesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ZkControllerGetNotesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getZkControllerGetNotesUrl().url.toString(), params, ... requestConfig })
  return res.data
}