/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ZkControllerGetBatchSnapshotsQueryResponse, ZkControllerGetBatchSnapshotsPathParams } from "@/lib/api-client/types/zk-controller-get-batch-snapshots";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getZkControllerGetBatchSnapshotsUrl(poolAddress: ZkControllerGetBatchSnapshotsPathParams["poolAddress"]) {
  const res = { method: 'GET', url: `/api/zk/batch-snapshots/${poolAddress}` as const }
  return res
}

/**
 * @summary Get all batch snapshots for a pool
 * {@link /api/zk/batch-snapshots/:poolAddress}
 */
export async function zkControllerGetBatchSnapshots(poolAddress: ZkControllerGetBatchSnapshotsPathParams["poolAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ZkControllerGetBatchSnapshotsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getZkControllerGetBatchSnapshotsUrl(poolAddress).url.toString(), ... requestConfig })
  return res.data
}