/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb";
import type { ZkControllerGetMerkleTreeQueryResponse, ZkControllerGetMerkleTreePathParams } from "@/lib/api-client/types/zk-controller-get-merkle-tree";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb";

function getZkControllerGetMerkleTreeUrl(poolAddress: ZkControllerGetMerkleTreePathParams["poolAddress"]) {
  const res = { method: 'GET', url: `/api/zk/merkle-tree/${poolAddress}` as const }
  return res
}

/**
 * @summary Get reconstructed Merkle tree data for a pool
 * {@link /api/zk/merkle-tree/:poolAddress}
 */
export async function zkControllerGetMerkleTree(poolAddress: ZkControllerGetMerkleTreePathParams["poolAddress"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ZkControllerGetMerkleTreeQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getZkControllerGetMerkleTreeUrl(poolAddress).url.toString(), ... requestConfig })
  return res.data
}